### ISSUE TITLE
kfctl build and apply do not appear to detect the project variable in KFDef

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4240] opened 2019-10-07 06:55 UTC
/kind bug

**What steps did you take and what happened:**
Download kfctl_gcp_iap.yaml , replace the email key with my e-mail username, add project: <PROJECT NAME> as the last key as indicated in the "Project should be set to the GCP project you want to use." comment. Run kfctl apply. Receive error project is not configured.

**What did you expect to happen:**

Either applying of kubeflow, or at least an error indicating where to configure the project.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): N/A (did not get that far)
- kfctl version: (use `kfctl version`): 2395c5fc
- Kubernetes platform: (e.g. `minikube`): GCP
- Kubernetes version: (use `kubectl version`): N/A (did not get that far)
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3

**Comment by jlewi** [comment] 2019-10-07 22:54
@holdenk can you provide your KFDef File?

**Comment by jlewi** [comment] 2019-10-07 23:06
@gabrielwen @lluunn  Are we not attempting to get the default values from gcloud?

**Comment by lluunn** [comment] 2019-10-08 00:03
dup of this one: https://github.com/kubeflow/kubeflow/issues/3923

**Comment by jlewi** [comment] 2019-10-08 00:09
Duplicate of #3923

**Comment by jlewi** [comment] 2019-10-08 00:47
See #4246 
The problem appears to be different from #3923 
In particular, kfctl doesn't appear to respect the email, project, and zone set in the KFDef.

The E2E test is setting the EMAIL and PROJECT environment variable which isn't what it should be doing
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py#L211

This was changed in #4040 which defined the new "-f" flag.

/assign @swiftdiaries

**Comment by jlewi** [comment] 2019-10-08 00:52
Here's where its getting PROJECT,ZONE, EMAIL from environment variables
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/bootstrap/pkg/kfapp/gcp/gcp.go#L1964

**Comment by jlewi** [comment] 2019-10-08 00:53
This was added recently in #4040

**Closed** 2019-10-08 23:09 UTC
Labels: area/kfctl, kind/bug, platform/gcp, priority/p0
