### ISSUE TITLE
Jupyter -  Http 503 - upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by jcurlier** [kubeflow/kubeflow#1710] opened 2018-10-04 04:20 UTC
**Step by step**

1. Installation following the instructions here:
https://www.kubeflow.org/docs/started/getting-started-gke/

2. Connect to Kubeflow homepage:

![image](https://user-images.githubusercontent.com/2846867/46452537-2e6d6600-c751-11e8-833f-78c8a0f3b30c.png)

3. Click JupyterHub and start a new Notebook container

4. The user container is properly created

![image](https://user-images.githubusercontent.com/2846867/46452604-8310e100-c751-11e8-8e98-2865a2962d27.png)

5. I am being redirected to `https://gde-ai-test-kubeflow.endpoints.gde-core-dev.cloud.goog/hub/api/oauth2/authorize?client_id=jupyterhub-user-accounts.google.com%253Ajerome%2540gigster.com&redirect_uri=%2Fuser%2Faccounts.google.com%253Ajerome%40gigster.com%2Foauth_callback&response_type=code&state=eyJ..`  and getting the error
`upstream connect error or disconnect/reset before headers`

When refreshing, different request get a `503`:
![image](https://user-images.githubusercontent.com/2846867/46512720-4bb23b00-c80a-11e8-9e53-d2493d23cae0.png)

**Note:**
- Any URl after to `/hub` or `/user` gives the same error: `HTTP 503`
- Tried also with RC 3

**Comment by suensummit** [comment] 2018-10-04 10:46
It seems like that the connections on GKE was quite unstable recently? My environment as follows:
- GKE version: `1.10.7-gke.2`
- GKE location: `asia-east1-a`

---
I encountered the same issue during these hours:

<img width="861" alt="screen shot 2018-10-04 at 6 32 37 pm" src="https://user-images.githubusercontent.com/5906989/46469063-df810880-c804-11e8-8883-e59dd0abe504.png">

---
Sometimes it is OK to show the jupyter UI **BUT** with server error:

<img width="1168" alt="screen shot 2018-10-04 at 6 26 38 pm" src="https://user-images.githubusercontent.com/5906989/46469089-ee67bb00-c804-11e8-9345-eb0c71710238.png">

---
Or, after create a new notebook it still get error while performing some operations:

<img width="1168" alt="screen shot 2018-10-04 at 6 24 01 pm" src="https://user-images.githubusercontent.com/5906989/46469133-19520f00-c805-11e8-8098-265c14ca449a.png">

**Comment by leoncamel** [comment] 2018-10-04 14:32
+1

Same for AWS

**Comment by richardsliu** [comment] 2018-10-05 01:11
I saw this as well. Refreshing the page a couple of times seems to fix the issue.

**Comment by leoncamel** [comment] 2018-10-05 15:35
@richardsliu Refreshing does not work here.

But, surprisingly, after I set replica to 1 for `ambassadorDeployment`, things become better.

So, I guess, it is something related with `lb_type`?

**Comment by jcurlier** [comment] 2018-10-05 19:08
In my configuration, following the documentation for the GKE, it seems to be using Envoy in front of the JupyterHub.

Adding the Envoy log for twice the exact same request:

Not working
```
[debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:99] queueing request due to no available connections
[trace][http] external/envoy/source/common/http/conn_manager_impl.cc:644] [C358][S13463747193362273593] decode headers called: filter=0x3dafa80 status=1
[trace][http] external/envoy/source/common/http/http1/codec_impl.cc:315] [C358] parsed 1740 bytes
[trace][connection] external/envoy/source/common/network/connection_impl.cc:229] [C358] readDisable: enabled=true disable=true
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C358] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C358] write ready
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C359] socket event: 3
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C359] write ready
[debug][connection] external/envoy/source/common/network/connection_impl.cc:464] [C359] delayed connection error: 111
[debug][connection] external/envoy/source/common/network/connection_impl.cc:134] [C359] closing socket: 0
```

working
```
[trace][http] external/envoy/source/common/http/conn_manager_impl.cc:644] [C352][S9918074447228879897] decode headers called: filter=0x3daf3c0 status=1
[trace][http] external/envoy/source/common/http/http1/codec_impl.cc:315] [C352] parsed 1740 bytes
[trace][connection] external/envoy/source/common/network/connection_impl.cc:229] [C352] readDisable: enabled=true disable=true
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C357] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C357] write ready
[debug][connection] external/envoy/source/common/network/connection_impl.cc:455] [C357] connected
[debug][client] external/envoy/source/common/http/codec_client.cc:52] [C357] connected
[debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:225] [C357] attaching to next request
[debug][router] external/envoy/source/common/router/router.cc:948] [C352][S9918074447228879897] pool ready
[trace][connection] external/envoy/source/common/network/connection_impl.cc:314] [C357] writing 1794 bytes, end_stream false
[trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:67] [C357] write returns: 1794
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C352] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C352] write ready
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C357] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C357] write ready
[trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C357] socket event: 3
[trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C357] write ready
[trace][connection] external/envoy/source/common/network/connection_impl.cc:415] [C357] read ready
```

**Comment by leoncamel** [comment] 2018-10-07 16:02
Just FYI, expose `jupyterhub-0` service can be a walk-around:

```sh
kubectl port-forward -n kubeflow jupyterhub-0 8000:8000
```

**Comment by jlewi** [comment] 2018-10-09 13:19
The error

```
upstream connect error or disconnect/reset before headers
```

Typically means that the service the reverse proxy (Ambassador) is using as backend is unavailable.

**Comment by leoncamel** [comment] 2018-10-10 06:45
@jlewi I guess this issue is **not** related with #1721. 

Since, the #1721 issue will only affect the `jupyter notebook`. This issue happened between `ambassador` and `jupyterhub`.

I will check it later today.

**Comment by jcurlier** [comment] 2018-10-10 07:18
@leoncamel - thanks for looking into this. I added the following to the cluster configuration and it might have helped - not sure.

```
  cleanup_interval_ms: 30000,
  dns_refresh_rate_ms: 30000,
```

yes it seems to be happening between `envoy` and `jupyter/configurable-http-proxy` where `envoy` cannot connect sometimes

**Comment by jcurlier** [comment] 2018-10-10 17:29
Also to add tracing for Envoy and JupyterHub:

**Envoy:**

File: `ks_app/vendor/kubeflow/core/iap.libsonnet`

```
        command: [
          "/usr/local/bin/envoy",
          "-c",
          params.configPath,
          "--log-level",
          "trace",
          // Since we are running multiple instances of envoy on the same host we need to set a unique baseId
          "--base-id",
          params.baseId,
        ],
```

File: `ks_app/vendor/kubeflow/core/jupyterhub.libsonnet`

```
                command: [
                  "jupyterhub",
                  "-f",
                  "/etc/config/jupyterhub_config.py",
                  "--ConfigurableHTTPProxy.debug=True",
                  "--log-level=DEBUG"
                ],
```

**Comment by leoncamel** [comment] 2018-10-21 04:13
This seems to be fixed on branch `v0.3.1`.

**Comment by jlewi** [comment] 2018-10-22 20:40
503 typically means the backend is crashing. In this case I think the backend is the Jupyter notebook.

It looks like your notebooks is crashing. If you look at the original screenshot you showed, the Jupyter notebook "jupyter-jerome-40gigster-2ecom"  shows 1 restart. 

Can you provide the logs for your Jupyter notebook to see what it exited?

Has your Jupyter notebook been restarted more times since then?

**Comment by connected-bsamadi** [comment] 2018-10-22 21:29
Jupyterhub is of type: Stateful Set. I have Pods 2/1. It has restarted once. I have this in the log:
{
insertId:  “1deig33fgwpp6f”
labels: {
 compute.googleapis.com/resource_name:  “fluentd-gcp-v3.1.0-x4g7j”
 container.googleapis.com/namespace_name:  “kubeflow”
 container.googleapis.com/pod_name:  “jupyterhub-0"
 container.googleapis.com/stream:  “stderr”
}
logName:  “projects/[project]/logs/jupyterhub”
receiveTimestamp:  “2018-10-22T21:17:07.257677778Z”
resource: {
 labels: {
  cluster_name:  “kubeflow”
  container_name:  “jupyterhub”
  instance_id:  “1164804470171994269"
  namespace_id:  “kubeflow”
  pod_id:  “jupyterhub-0"
  project_id:  “[project]”
  zone:  “us-central1-c”
 }
 type:  “container”
}
severity:  “ERROR”
textPayload:  “[I 2018-10-22 21:17:03.710 JupyterHub proxy:299] Checking routes
”
timestamp:  “2018-10-22T21:17:03Z”
}

**Comment by jlewi** [comment] 2018-10-22 21:57
Can you provide the complete logs for the JupyterHub and Jupyter pods?

You can fetch them with gcloud like so

```
gcloud --project=${PROJECT} logging read --format="table(timestamp, resource.labels.container_name, textPayload)" --freshness=24h      --order asc         "resource.type=\"container\" resource.labels.cluster_name=\"${CLUSTER}\"  resource.labels.pod_id=\"${POD}\"  "
```
Please attach the logs for the JupyterHub and Jupyter pods as separate files to this issue.

**Comment by connected-bsamadi** [comment] 2018-10-23 13:39
I just deployed a fresh Kubeflow. It's been quite a few minutes after the setup process finished. For some reason, I still get a 404 error when I try the main URL of the cluster.

The log for jupyterhub-0 is here:
https://gist.github.com/connected-bsamadi/21fabab6d755133e5a70ab44263da93e

**Comment by connected-bsamadi** [comment] 2018-10-23 15:18
There three pods for envoy. I often have a couple of them restarting 8 times. Here is the log of an envoy pod that has restarted twice:
https://gist.github.com/connected-bsamadi/2d494016fefb0e0cb9a1f59918939d74

**Comment by connected-bsamadi** [comment] 2018-10-26 14:36
@leoncamel I have run out of ideas. I will create a new issue.

**Comment by jlewi** [comment] 2018-10-29 13:38
@leoncamel It seems like you are hitting a different issue then the 503 Jupyter issue listed in this issue. A 404 would suggest a problem with the main central dashboard. Did you open up a separate issue for that?

**Comment by leoncamel** [comment] 2018-10-30 06:19
@jlewi OK. I will re-test later tonight, and open another issue if it is still existed.

**Comment by jlewi** [comment] 2018-11-19 04:52
@leoncamel Were you able to resolve this? Were you running into #1900?

**Comment by changchuming** [comment] 2019-02-22 01:46
It seems that I am still having this issue intermittently. When I refresh the page a few times, the error message goes away and the endpoint loads.

**Comment by ChrisMagnuson** [comment] 2019-05-03 14:20
Envoy upstream had an [issue](https://github.com/envoyproxy/envoy/issues/6190) that only recently was fixed in dev but not yet fixed in any stable version where if the service it was proxying to ended the connection with a FIN/ACK envoy would still leave it in its connection pool and would send the next request to that service using that connection.

The service would receive it, say a get request, and then send a RST as since it had already FIN/ACKed it doens't have a way to reply to the request.

Maybe related to what your seeing, to confirm if you have a way to capture packets on the service side you should see the weird behavoir of the service doing a FIN/ACK but envoy only responding with ACK and then sometime later sending another request on that TCP stream triggering the service to send a RST.

**Comment by jlewi** [comment] 2019-06-02 17:10
Duplicate of #2852 

Closing this one in favor of #2852

**Comment by jlewi** [comment] 2019-06-02 17:11
Duplicate of #2852

**Closed by jlewi** 2019-06-02 17:10 UTC
Labels: area/jupyter
