### ISSUE TITLE
Bootstrapper throwing error when deployed on GKE

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/kubeflow#961] opened 2018-06-09 04:27 UTC
Used https://github.com/kubeflow/kubeflow/blob/master/docs/gke/gke_setup.md to deploy kubeflow in GCP. 

Bootstrapper is throwing the following error:
```
{"filename":"app/server.go:529","level":"info","msg":"stderr \u003e\u003e\u003e exit status 1: unable to recognize \"STDIN\": no matches for kind \"Issuer\" in version \"certmanager.k8s.io/v1alpha1\"
unable to recognize \"STDIN\": no matches for kind \"LambdaController\" in version \"metacontroller.k8s.io/v1alpha1\"
unable to recognize \"STDIN\": no matches for kind \"Certificate\" in version \"certmanager.k8s.io/v1alpha1\"
unable to recognize \"STDIN\": no matches for kind \"CloudEndpoint\" in version \"ctl.isla.solutions/v1\"
","time":"2018-06-09T01:18:57Z"}
```

I am unable to do a `ks apply` in the bootstrapper pod either - looks like KUBECONFIG is not set correctly inside the pod.

**Comment by jlewi** [comment] 2018-06-09 21:00
Duplicate of #954

**Closed by jlewi** 2018-06-09 21:00 UTC
Labels: priority/p1, release/0.2.0, sprint/2018-06-11-to-06-22
