### ISSUE TITLE
Profile to include contributors to the namespace 

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/kubeflow#4896] opened 2020-03-26 16:19 UTC
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
Currently, after a profile is created, users need to go to the managing contributors UI to add contributors individually. It would be nice if we can include the contributors to the profile via a plugin. 

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
I imagine that we can have a Contributor plugin and config corresponding rbac and istio service roles for the contributors. The following is an example of the profile with this feature. 

```yaml
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: test
spec:
  owner:
    kind: User
    name: owner@example.com
  plugins:
  - kind: WorkloadIdentity
    spec:
      gcpServiceAccount: sa@example.com
  - kind: Contributor
    spec:
      contributors:
      - kind: Group
        name: contributors@example.com
      - kind: User
        name: contributor@example.com
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by daikeshi** [comment] 2020-03-26 16:26
cc @jlewi @Bobgy

**Comment by jlewi** [comment] 2020-03-27 14:59
This seems like a duplicate of #4885.
Also see discussion in:
https://groups.google.com/forum/m/#!topic/kubeflow-discuss/whS_j4RlEJo

This seems to be moving profiles in the direction of managing ACLs and I'm not sure we want to go in that direction.

**Comment by jlewi** [comment] 2020-04-06 14:20
Duplicate #4855

**Closed by jlewi** 2020-04-06 14:20 UTC
Labels: area/multiuser, kind/feature, priority/p2
