### ISSUE TITLE
Is there a plan for Kubeflow to replace ksonnet with something else like helm?

### ISSUE THREAD

**Issue by rp4fx12** [kubeflow/kubeflow#2738] opened 2019-03-19 13:29 UTC

**Comment by kkasravi** [comment] 2019-03-19 13:33
We are replacing ksonnet with kustomize. kfctl has a plugin design, so additional package managers may also be considered and could be added between scheduled releases.

**Comment by govindKAG** [comment] 2019-03-20 07:34
relevant issues page : https://github.com/kubeflow/kubeflow/issues/2412

**Comment by jlewi** [comment] 2019-03-31 22:15
Duplicate of #2412

**Closed by jlewi** 2019-03-31 22:15 UTC
