### ISSUE TITLE
kfctl should use config file in current if not specified by -f

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4377] opened 2019-10-23 18:59 UTC
/kind bug

**What steps did you take and what happened:**
```
kfctl build -f ...
kfctl apply
```

**What did you expect to happen:**
Kfctl should support 
```
build -f config_file
make custom changes
apply
```

**Environment:**

- Kubeflow version: afeb8a5919c7d402fb7d22bdaa9fb4f87ec1aba8
- kfctl version: afeb8a5919c7d402fb7d22bdaa9fb4f87ec1aba8

**Comment by gabrielwen** [comment] 2019-10-23 19:04
@lluunn @jlewi 
I thought we discussed this a bit before and agreed we should always use `-f`?

**Comment by lluunn** [comment] 2019-10-23 20:19
yeah this is intended.
The file name is not always app.yaml, so users should specify it.

**Comment by jlewi** [comment] 2019-10-23 23:11
Closing this as working as intended.

**Closed by jlewi** 2019-10-23 23:11 UTC
Labels: kind/bug
