### ISSUE TITLE
kfctl latest 0.7 error: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#4427] opened 2019-10-30 01:33 UTC
/kind bug

**What steps did you take and what happened:**
kfctl apply has error:
```
INFO[0559] Downloading secret user-gcp-sa from namespace kubeflow  filename="gcp/gcp.go:1812"
INFO[0559] Creating secret user-gcp-sa to namespace kubeflow-lunkai  filename="gcp/gcp.go:1818"
INFO[0559] Generating PodDefault in namespace kubeflow-lunkai; APIVersion kubeflow.org/v1alpha1  filename="gcp/gcp.go:1753"
E1029 18:31:21.134882   47418 memcache.go:135] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

Has anyone seen this before?
cc @jlewi @richardsliu 

**Environment:**
kfctl from 0.7rc6,  with https://raw.githubusercontent.com/kubeflow/manifests/fccc0ac/kfdef/kfctl_gcp_iap.0.7.0.yaml

**Comment by jlewi** [comment] 2019-10-31 11:55
Duplicate of #4414

**Closed by jlewi** 2019-10-31 11:55 UTC
Labels: kind/bug

**Comment by Dhull442** [comment] 2022-09-21 10:13
This solution mentioned [here ](https://github.com/kubeflow/kubeflow/issues/5230#issuecomment-817889782)worked!
