### ISSUE TITLE
kfctl apply all -V errors with Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/kubeflow#4198] opened 2019-09-27 08:21 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
 kfctl apply all -V
errors with

INFO[0009] creating Service/zipkin                       filename="kustomize/kustomize.go:447"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: no matches for kind "Deployment" in version "extensions/v1beta1"
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: no matches for kind "Deployment" in version "extensions/v1beta1"

**What did you expect to happen:**

kubeflow to complete installation and configuration of all the remaining pods

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
kfctl v0.6.2-0-g47a0e4c7
- Kubernetes platform: (e.g. `minikube`)
kubernetes
- Kubernetes version: (use `kubectl version`):
kubeflow@masternode:/nfsroot/kf-poc$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04.3 LTS
kubeflow@masternode:/nfsroot/kf-poc$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   coredns-5644d7b6d9-s8zk8                 1/1     Running   2          20h
kube-system   coredns-5644d7b6d9-x7wf9                 1/1     Running   2          20h
kube-system   etcd-masternode.com                      1/1     Running   2          20h
kube-system   kube-apiserver-masternode.com            1/1     Running   2          20h
kube-system   kube-controller-manager-masternode.com   1/1     Running   2          20h
kube-system   kube-flannel-ds-amd64-8584j              1/1     Running   3          20h
kube-system   kube-flannel-ds-amd64-zmxvm              1/1     Running   2          20h
kube-system   kube-proxy-msrjp                         1/1     Running   3          20h
kube-system   kube-proxy-s7ql9                         1/1     Running   2          20h
kube-system   kube-scheduler-masternode.com            1/1     Running   2          20h

**Comment by cyrilthank** [comment] 2019-09-27 08:22
[kubeflow_error_trace.txt](https://github.com/kubeflow/kubeflow/files/3661700/kubeflow_error_trace.txt)

**Comment by cyrilthank** [comment] 2019-09-27 08:22
Please help as this is now a show stopper for us

**Comment by apatsekin** [comment] 2019-09-28 18:45
Running into exactly the same issue while trying this official manual:
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Steps to reproduce on clean Ubuntu 16 AWS instance:

sudo snap install microk8s --classic
sudo usermod -a -G microk8s [username]
microk8s.enable dashboard dns storage

**Comment by MostafaGazar** [comment] 2019-10-03 17:38
> UPDATE:
> The problem is described here:
> https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/
> Apparently config file with extensions/v1beta1 for `Deployment` is not suppose to work anymore. Although it works in Kubernetes 1.14.

A quick workaround if you are using [multipass](http://multipass.run/) with [microk8s](http://microk8s.io/) is to install v1.14. I just tried it and it worked fine. 

Follow the steps in https://tutorials.ubuntu.com/tutorial/get-started-kubeflow but install microk8s via `sudo snap install microk8s --classic --channel=1.14/stable` instead.

**Comment by cyrilthank** [comment] 2019-10-03 17:52
Can you please share if this work around works for Kubernetes ( ie the non micro/mini) as well
    On Thursday, October 3, 2019, 11:09:20 PM GMT+5:30, Mostafa Gazar <notifications@github.com> wrote:  
 
 

UPDATE:
The problem is described here:
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/
Apparently config file with extensions/v1beta1 for Deployment is not suppose to work anymore. Although it works in Kubernetes 1.14.


A quick workaround if you are using multipass with microk8s is to install v1.14. I just tried it and it worked fine.

Follow the steps in https://tutorials.ubuntu.com/tutorial/get-started-kubeflow but install microk8s via sudo snap install microk8s --classic --channel=1.14/stable instead.

**Comment by jlewi** [comment] 2019-11-04 23:59
Kubeflow doesn't support Kubernetes 1.16 yet.
We are tracking it in kubeflow/manifests#375

Duplicate of kubeflow/manifests#375

**Closed by jlewi** 2019-11-04 23:59 UTC
Labels: area/kfctl, kind/bug, priority/p1, problems/k8s

**Comment by smalhot9464** [comment] 2022-07-04 18:59
any luck anyone, same error I am getting , I am using Mac OS
