### ISSUE TITLE
Argo UI doesn't work when Ambassador is scaled to more than 1 replicas

### ISSUE THREAD

**Issue by naz19** [kubeflow/kubeflow#2222] opened 2019-01-05 04:06 UTC
Argo UI started working behind ambassador after adding BASE_HREF.

It worked well on my local minikube installation but when deployed on GKE, the behavior was inconsistent. Argo UI home page is blank sometimes (loads after refreshing a few times). Workflows don't load sometimes (again refreshing works once in a while).

Looks like a LB issue? Ambassador is by default deployed as 3 replicas on GKE. Scaling ambassador down to 1 seemed to fix the issue. Argo UI is working fine after the scale down.

Does anyone else have the same issue or is it specific to my GCP installation?

**Comment by jlewi** [comment] 2019-01-06 20:15
Did you try accessing it via kubectl port-forward?

Kubeflow's CI system runs Argo UI directly behind a GCP LB and that works just fine.
http://testing-argo.kubeflow.org

If it works behind kubectl port-forward then something might be going on with Ambassador.

Some things to look at 

* Logs for Argo Pod
* Logs for Ambassador pod
* Javascript console (in chrome or equivalent in other browsers) to see if there are errors

If there are a lot of workflows in your cluster then the K8s master can become unresponsive trying to return them all to Argo which is why you might not see workflows showing up in the UI.

/cc @jessesuen

**Comment by andreyvelich** [comment] 2019-01-08 22:54
I tried to deploy Ambassador and Argo on GKE and it worked fine for me.
I also had 3 replicas of Ambassador. 
After port-forwarding one of the Ambassador pod, I can access to ArgoUI on /argo/ URL path.

**Comment by jlewi** [comment] 2019-01-13 23:55
@naz19 Can you provide any additional information about what the problem is?

**Comment by jlewi** [comment] 2019-01-13 23:56
One possibility is that not all of the Argo pods observed the service and added the route. I would try deleting all the Ambassador pods. The deployment will then recreate them and this should force the pod to reload all the K8s service mappings.

**Comment by hamedhsn** [comment] 2019-02-15 19:12
@jlewi your last suggestion worked for me. And I can see the ui through ambassador `/argo/` path. 
however direct port-forwarding of ui pod is not working and I see a blank page.

**Comment by jlewi** [comment] 2019-02-19 19:00
@hamedhsn Argo takes a parameter which specifies the base path it is serving on. This argument is configured based on the reverse proxy. So if you try to port-forward you might need to add the same base path that Ambassador is using "/argo/" as @andreyvelich mentioned above

see
https://github.com/kubeflow/kubeflow/blob/82295a8421bd80d1caf6b8c36a055eeb10ec6af2/kubeflow/argo/argo.libsonnet#L208

I'm going to close this issue since it looks like its been resolved.

**Closed by jlewi** 2019-02-19 19:00 UTC
Labels: area/ambassador, community/question, platform/gcp
