### ISSUE TITLE
Option to disable self-serve profile creation flow in CentralDashboard

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#4942] opened 2020-04-10 20:46 UTC
/kind question

**Question:**
In multi-user environment, If user logged in doesn't have a profile, central dashboard pops the page to create a namespace for that user. Is there's a configuration to disable this option? In some cases, we don't want user to visit cluster until admin create profile for them.

**Comment by yanniszark** [comment] 2020-04-15 14:22
@Jeffwan I am adding this issue in the ROADMAP for 1.1.
My understanding is that we want to have an option to disable the Profile creation flow.
Should we rename the issue to reflect that a bit better? (e.g., `Option to disable self-serve profile creation flow in CentralDashboard`)

cc @avdaredevil 
/priority p1
/area centraldashboard

**Comment by Jeffwan** [comment] 2020-04-16 05:45
@yanniszark Sounds good. Update the title

**Comment by jlewi** [comment] 2020-04-20 14:28
Duplicate of #4889

**Closed by jlewi** 2020-04-20 14:28 UTC
Labels: area/centraldashboard, kind/feature, kind/question, priority/p1
