### ISSUE TITLE
Stop/Pause Notebook Servers

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/kubeflow#4951] opened 2020-04-14 06:31 UTC
/kind feature

**Describe the solution you'd like:**
Currently we force users to delete notebook servers entirely if they want to free up resources, we should let users stop/pause a notebook server (without deleting it). A paused notebook server should be able to start again without loosing the local disk of the notebook server, but I think it would be acceptable to lose unsaved notebook changes (if the user is warned of this behaviour before they stop/pause).

This will also reduce the creation of unneeded PVC's in the users namespace.

**Comment by jlewi** [comment] 2020-04-14 17:26
@kimwnasptd @thesuperzapper Do we have an existing issue for this?

**Comment by jlewi** [comment] 2020-04-20 14:56
Duplicate of #4857

**Closed by jlewi** 2020-04-20 14:56 UTC
Labels: area/jupyter, kind/feature, priority/p2
