### ISSUE TITLE
Unable to access UI for kubeflow

### ISSUE THREAD

**Issue by wallwind** [kubeflow/kubeflow#5360] opened 2020-10-24 14:41 UTC
all is running

root@VM-2-5-ubuntu:~/kustomize# kubectl get po -n kubeflowNAME                                                           READY   STATUS    RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                     1/1     Running   0          13m
admission-webhook-deployment-768574d56b-dm7lh                  1/1     Running   0          13m
application-controller-stateful-set-0                          1/1     Running   0          90m
argo-ui-5f845464d7-mcnh7                                       1/1     Running   0          28h
centraldashboard-d5c6d6bf-8rhmr                                1/1     Running   0          28h
jupyter-web-app-deployment-77856f4d7d-5d6n7                    1/1     Running   0          62m
katib-controller-64584b8dc6-rrsdb                              1/1     Running   1          28h
katib-db-manager-54b64f99b-577m7                               1/1     Running   0          28h
katib-mysql-57b7578569-2f5c5                                   1/1     Running   0          28h
katib-ui-76f84754b6-thwsv                                      1/1     Running   0          28h
kfserving-controller-manager-0                                 2/2     Running   1          109m
metacontroller-0                                               1/1     Running   0          3h53m
metadata-db-6956c8bb7b-r4zn9                                   1/1     Running   0          28h
metadata-deployment-5dd4c9d4cf-p8hps                           1/1     Running   0          28h
metadata-envoy-deployment-5b9f9466d9-9wcgb                     1/1     Running   0          28h
metadata-grpc-deployment-74f69954dc-cwhb7                      1/1     Running   4          28h
metadata-ui-8968fc7d9-g2bll                                    1/1     Running   0          28h
minio-7d5598946f-f52hf                                         1/1     Running   0          28h
ml-pipeline-5c44458999-t8tqq                                   1/1     Running   0          28h
ml-pipeline-ml-pipeline-visualizationserver-675656df79-9gqpf   1/1     Running   0          28h
ml-pipeline-persistenceagent-7785884886-kzj8x                  1/1     Running   0          28h
ml-pipeline-scheduledworkflow-7b4cb5d959-jflg9                 1/1     Running   0          28h
ml-pipeline-ui-5fbd94b9fb-ngdbv                                1/1     Running   0          28h
ml-pipeline-viewer-controller-deployment-67bc6bfc9c-frwgj      1/1     Running   0          3h51m
mysql-7b786d6896-jpv7j                                         1/1     Running   0          28h
notebook-controller-deployment-78468f4f68-vzlpg                1/1     Running   0          3h51m
profiles-deployment-645df6d5c-wrtp8                            2/2     Running   0          3h51m

and 

NAME                                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
admission-webhook-service                      ClusterIP   172.16.254.115   <none>        443/TCP             28h
application-controller-service                 ClusterIP   172.16.254.26    <none>        443/TCP             28h
argo-ui                                        NodePort    172.16.254.28    <none>        80:31620/TCP        28h
centraldashboard                               ClusterIP   172.16.253.93    <none>        80/TCP              28h
jupyter-web-app-service                        ClusterIP   172.16.252.216   <none>        80/TCP              28h
katib-controller                               ClusterIP   172.16.252.226   <none>        443/TCP,8080/TCP    28h
katib-db-manager                               ClusterIP   172.16.252.30    <none>        6789/TCP            28h
katib-mysql                                    ClusterIP   172.16.252.167   <none>        3306/TCP            28h
katib-ui                                       ClusterIP   172.16.254.110   <none>        80/TCP              28h
kfserving-controller-manager-metrics-service   ClusterIP   172.16.255.76    <none>        8443/TCP            28h
kfserving-controller-manager-service           ClusterIP   172.16.254.29    <none>        443/TCP             28h
kfserving-webhook-server-service               ClusterIP   172.16.254.87    <none>        443/TCP             128m
metadata-db                                    ClusterIP   172.16.252.247   <none>        3306/TCP            28h
metadata-envoy-service                         ClusterIP   172.16.253.213   <none>        9090/TCP            28h
metadata-grpc-service                          ClusterIP   172.16.253.208   <none>        8080/TCP            28h
metadata-service                               ClusterIP   172.16.252.14    <none>        8080/TCP            28h
metadata-ui                                    ClusterIP   172.16.253.106   <none>        80/TCP              28h
minio-service                                  ClusterIP   172.16.255.227   <none>        9000/TCP            28h
ml-pipeline                                    ClusterIP   172.16.252.209   <none>        8888/TCP,8887/TCP   28h
ml-pipeline-ml-pipeline-visualizationserver    ClusterIP   172.16.255.119   <none>        8888/TCP            28h
ml-pipeline-tensorboard-ui                     ClusterIP   172.16.254.172   <none>        80/TCP              28h
ml-pipeline-ui                                 ClusterIP   172.16.254.112   <none>        80/TCP              28h
mysql                                          ClusterIP   172.16.252.162   <none>        3306/TCP            28h
notebook-controller-service                    ClusterIP   172.16.252.207   <none>        443/TCP             28h
profiles-kfam                                  ClusterIP   172.16.253.177   <none>        8081/TCP            28h
pytorch-operator                               ClusterIP   172.16.254.185   <none>        8443/TCP            28h
seldon-webhook-service                         ClusterIP   172.16.254.156   <none>        443/TCP             28h
tensorboard                                    ClusterIP   172.16.252.194   <none>        9000/TCP            28h
tf-job-operator                                ClusterIP   172.16.253.181   <none>        8443/TCP            28h
/kind question

**Question:**
[You can ask any question about this project.]
![image](https://user-images.githubusercontent.com/1772992/97084442-a44f0d80-1649-11eb-9480-f3b6aa9148df.png)

 nohup kubectl port-forward -n istio-system svc/istio-ingressgateway 8088:80 &

and  And then try to access the UI by pointing a web browser at

http://127.0.0.1:8088/

can not open

**Comment by AdeshKhandait** [comment] 2020-10-25 06:14
Hi,Adesh I am Beginner I don't know where to start can any body help me out????

**Comment by jbottum** [comment] 2020-10-25 22:51
@wallwind Hi, can you please confirm which platform that you are using i.e. On-Prem or is this in a public cloud like AWS ?

**Comment by wallwind** [comment] 2020-10-31 08:59
> @wallwind Hi, can you please confirm which platform that you are using i.e. On-Prem or is this in a public cloud like AWS ?

in my env,centos

**Comment by iancoffey** [comment] 2020-11-04 15:59
Not sure if its helpful, feel free to ignore if not, but something I have run into myself is - I noticed you hadnt set `--address` in your port-forward command. Not sure if your installation is on your local system or not, but if this is a VM youll need to set that - 0.0.0.0 would bind to all interfaces, for example.

**Comment by DavidSpek** [comment] 2021-03-20 16:07
Given that this issue hasn't been active for a while and this seems like a general setup error I am closing this issue. Feel free to reopen or create a new issue if the problem is still present. 
/close

**Closed by DavidSpek** 2021-03-20 16:07 UTC
Labels: area/front-end, area/katib, kind/bug, kind/question, priority/p2
