### ISSUE TITLE
Error while updating iap-ingress for custom domains

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#1689] opened 2018-10-01 21:28 UTC
When following the instructions for using custom domains (https://www.kubeflow.org/docs/guides/gke/custom-domain/), I ran into this error:

```
ks apply default -c iap-ingress
INFO Updating backendconfigs kf-latest3.envoy-iap 
INFO Updating serviceaccounts kf-latest3.envoy    
INFO Updating clusterrolebindings envoy           
INFO Updating clusterroles kf-latest3.envoy       
INFO Updating certificates kf-latest3.envoy-ingress-tls 
INFO Updating ingresses kf-latest3.envoy-ingress  
INFO Updating configmaps kf-latest3.envoy-config  
INFO Updating services kf-latest3.whoami-app      
INFO Updating configmaps kf-latest3.ingress-bootstrap-config 
ERROR handle object: merging object with existing state: Service "envoy" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable] 

```

**Comment by richardsliu** [comment] 2018-10-03 00:05
Looks like this is already opened as #1145

**Comment by jlewi** [comment] 2018-10-09 13:28
I think the work around is to delete the existing components before updating them.

Duplicate of #1145

**Closed by jlewi** 2018-10-09 13:28 UTC
Labels: area/0.3.0
