### ISSUE TITLE
Notebook servers renders a blank page

### ISSUE THREAD

**Issue by tianhaoz95** [kubeflow/kubeflow#5480] opened 2020-12-22 06:59 UTC
/kind bug

**What steps did you take and what happened:**
I installed Kubeflow with steps in https://www.kubeflow.org/docs/started/workstation/getting-started-multipass, but the notebook servers tab is empty.

**What did you expect to happen:**

It should show a button for adding notebooks.

**Anything else you would like to add:**

![Screenshot from 2020-12-21 22-54-59](https://user-images.githubusercontent.com/16887772/102859031-1b054e80-43e0-11eb-93cd-813bbabc77d5.png)

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version dev_local
- kfctl version: (use `kfctl version`): kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: (e.g. `minikube`) microk8s
- Kubernetes version: (use `kubectl version`): 

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

- OS (e.g. from `/etc/os-release`):

```bash
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by unijoy** [comment] 2020-12-28 23:58
+1

**Comment by k402xxxcenxxx** [comment] 2020-12-29 01:45
+1

**Comment by Dottorepoloni** [comment] 2020-12-30 14:23
I have same SW-configuration and same error...

**Comment by Dottorepoloni** [comment] 2020-12-30 14:25
btw any workaround? I'm a bit stuck...

**Comment by tianhaoz95** [comment] 2020-12-30 20:48
@Dottorepoloni doing it with minikube worked for me if you are in a hurry, but still no luck with microk8s.

**Comment by DavidSpek** [comment] 2021-01-02 17:13
microk8s uses the Kubeflow charms. It might be worth creating an issue at https://github.com/juju-solutions/bundle-kubeflow.

**Comment by Dottorepoloni** [comment] 2021-01-03 18:32
With minikube I had no luck, but miniKF is running fine... even if miniKF is actually built with minikube 🤔

**Comment by k402xxxcenxxx** [comment] 2021-01-05 06:50
I think the root cause is the routing problem to jupyter-web

I install the kubeflow on Ubuntu 20.04 using microk8s and follow the installation steps on [official doc](https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/)

I found that after it finished the installation, the virtual service configuration for jupyter-web isn't there.
So I do the walk around (referenced by [istio example](https://istio.io/latest/docs/examples/microservices-istio/istio-ingress-gateway/) and [manifist yaml files](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/overlays/istio/virtual-service.yaml)) to manually setup the virtual service configuration.

the command I use:
```
microk8s kubectl patch virtualservices jupyter-web -n kubeflow --patch "$(cat patch-jupyter-web.yaml)" --type=merge
```
the patch-jupyter-web.yaml I use:
```yaml
# patch-jupyter-web.yaml
spec:
  gateways:
  - kubeflow
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /jupyter
    match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: jupyter-web.kubeflow.svc.cluster.local
        port:
          number: 5000
```

It should make notebook server comeback and you can create/delete jupyter notebook container.

But still has trouble when you press the CONNECT button, it will show  `/notebook/{namespace}/{jupyter-name}` is not a valid page even if the jupyter notebook container is really created.
I think it could be solved by correct the istio gateway configuration in jupyter-controller(some bundle will call it notebook-controller).

I'm not sure it is a good way to solve this problem. Please give me some response.

**Comment by k402xxxcenxxx** [comment] 2021-01-06 02:10
The "`/notebook/{namespace}/{jupyter-name}` is not a valid page" problem can be solved by doing the workaround that manually add the new gateway named `kubeflow-gateway`. 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: null
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Comment by thor3333** [comment] 2021-01-07 02:16
@k402xxxcenxxx Thanks for your help. 
How do you create a gateway? Can you send the commands ?

**Comment by k402xxxcenxxx** [comment] 2021-01-08 03:05
@thor3333 It could be just create a new redundant one.
```
microk8s kubectl create -f kubeflow-gateway.yaml
```

**Comment by ArVar** [comment] 2021-01-13 19:16
Same here. Unfortunately the mentioned workarounds didn't work for me. I'm using microk8s setup (multipass with 1.20/latest microk8s snap).

**Comment by k402xxxcenxxx** [comment] 2021-01-14 04:44
@ArVar 
Could you check your virtual service configuration? It should be easy to point out the problem.
```
microk8s kubectl get virtualservice -A
```
If `jupyter-web` is there, you can check the setting by printing out the message with yaml format.
```
microk8s kubectl get virtualservice -n kubeflow jupyter-web -o yaml
```

**Comment by ArVar** [comment] 2021-01-14 11:04
@k402xxxcenxxx 
The virtual service does exist and settings (after patching) are:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    juju.io/controller: 157ce4c1-db45-4e76-8e09-0c4494fb00b6
    juju.io/model: 6eb94a10-7a2f-4873-80a0-b98455a213af
  creationTimestamp: "2021-01-13T13:34:42Z"
  generation: 4
  labels:
    juju-app: istio-pilot
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:juju.io/controller: {}
          f:juju.io/model: {}
        f:labels:
          .: {}
          f:juju-app: {}
      f:spec:
        .: {}
        f:gateways: {}
        f:hosts: {}
    manager: jujud
    operation: Update
    time: "2021-01-14T07:45:16Z"
  - apiVersion: networking.istio.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:http: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-01-14T08:25:46Z"
  name: jupyter-web
  namespace: kubeflow
  resourceVersion: "111277"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/kubeflow/virtualservices/jupyter-web
  uid: a756bb8c-53ec-45e7-a875-4e63119d7c48
spec:
  gateways:
  - kubeflow
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /jupyter
    match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: jupyter-web.kubeflow.svc.cluster.local
        port:
          number: 5000
```

**Comment by k402xxxcenxxx** [comment] 2021-01-15 01:54
@ArVar 
Your yaml file seems to be OK for me.
Could you check the log of `jupyter-web`? 
```
microk8s kubectl logs deployment/jupyter-web -n kubeflow -c jupyter-web -f
```
This command will continuously print the log. And you switch to the browser and refresh the notebook server page.

Before the workaround I mention, it should be something like that:
```
2021-01-15 01:42:19,903 | kubeflow_jupyter.default.app | INFO | Sending file '/static/jupyter/styles.56d86be2ce72e09364f3.css' for path: /jupyter/styles.56d86be2ce72e09364f3.css
2021-01-15 01:42:19,905 | kubeflow_jupyter.default.app | INFO | Sending file '/static/jupyter/polyfills.33be5ef0e73aeb02f33c.js' for path: /jupyter/polyfills.33be5ef0e73aeb02f33c.js
2021-01-15 01:42:19,907 | kubeflow_jupyter.default.app | INFO | Sending file '/static/jupyter/runtime.5a09a3ce9d0d6e716b47.js' for path: /jupyter/runtime.5a09a3ce9d0d6e716b47.js
```
Actually, the file `/static/jupyter/styles.56d86be2ce72e09364f3.css` doesn't exist in the server, so it will return a default `index.html` for the request. This is why it will show the error that @tianhaoz95 post. 

After I do the rewrite rule, it should be like this:
```
2021-01-15 01:42:19,903 | kubeflow_jupyter.default.app | INFO | Sending file '/static/styles.56d86be2ce72e09364f3.css' for path: styles.56d86be2ce72e09364f3.css
2021-01-15 01:42:19,905 | kubeflow_jupyter.default.app | INFO | Sending file '/static/polyfills.33be5ef0e73aeb02f33c.js' for path: polyfills.33be5ef0e73aeb02f33c.js
2021-01-15 01:42:19,907 | kubeflow_jupyter.default.app | INFO | Sending file '/static/runtime.5a09a3ce9d0d6e716b47.js' for path: runtime.5a09a3ce9d0d6e716b47.js
```
It can find the right file and work well.

So check the log and that we can find out if your problem is same as mine.

**Comment by dgess** [comment] 2021-01-15 15:59
I am having a similar issue after the workarounds...
In the JS console, a CSS file is not loaded due to an improper MIME type...
![image](https://user-images.githubusercontent.com/51414890/104749302-4138b880-5718-11eb-824e-f21fbfc93276.png)
I am thinking that issue is not allowing the JS components for interacting with the notebook server vis Kubeflow UI to not load.

**Comment by dgess** [comment] 2021-01-15 17:12
After updating the patch file, logging out of Kubeflow, and logging back into Kubeflow, the issue was resolved.

**Comment by ArVar** [comment] 2021-01-15 18:22
@k402xxxcenxxx
I had to restart my vm. The kubeflow pods didn't start up as expected, thus, I disabled and enabled kubeflow.
At this point, I noticed that the file `/var/snap/microk8s/1910/juju/share/juju/controllers.yaml` (and the temp file `/tmp/juju-store-lock-3734303161326635` ) had wrong user (root instead of ubuntu) preventing kubeflow from starting up properly.
After changing that, I could enable kubeflow. However, jupyter-web had an issue with the security token.
Due to the kubeflow "restart" I had to reapply the patch from above (again with `microk8s kubectl patch virtualservices jupyter-web -n kubeflow --patch "$(cat patch-jupyter-web.yaml)" --type=merge`).

After redeploying `jupyter-web` (and re-setting the dashboard credentials, redeploying dex-auth) everything worked fine.
I think, this problem occurs during some processes due to wrong set file ownership AND the yaml misconfiguration.

It might be related to https://github.com/ubuntu/microk8s/issues/1763.

**Comment by VariableDeclared** [comment] 2021-01-19 08:23
Hi @tianhaoz95 i've raised an issue on the Kubeflow Bundle page this is an issue with [charms](https://github.com/juju-solutions/bundle-kubeflow/issues/297). Comment https://github.com/kubeflow/kubeflow/issues/5480#issuecomment-754439487 worked for me.

**Comment by k402xxxcenxxx** [comment] 2021-01-21 06:43
Hi everyone,
I tried the juju bundle `cs:kubeflow-245` that the latest update of microk8s used and the notebook server problem is gone.

Currently, we can enable kubeflow with specified bundle option to get this update.
```
microk8s enable kubeflow --bundle=cs:kubeflow-245
```

**Comment by DavidSpek** [comment] 2021-01-21 09:22
Are there any objections to closing this issue? It seems to have been fixed and is related to Canonical's charms and therefore not relevant to the code in this repo.

**Comment by tianhaoz95** [comment] 2021-01-24 20:51
Thanks everyone! The solution is working.

**Closed** 2021-01-24 20:52 UTC
Labels: area/jupyter, kind/bug, priority/p2

**Comment by ankita4AI** [comment] 2021-02-02 06:29
@k402xxxcenxxx hey, it did not work for me with cs:kubeflow-245.
Are there some other prerequisites too?

**Comment by k402xxxcenxxx** [comment] 2021-02-02 06:46
@ankita4AI 
In my case, I use Ubuntu 20.04 and install microk8s (1910) by snap using
```
sudo install microk8s --classic --channel=1.20/stable
 ```
No other prerequisite for me.
