### ISSUE TITLE
Can't start pods sucessfully through kubeflow UI on local kubernetes cluster - PV provisioner not working

### ISSUE THREAD

**Issue by dwang55** [kubeflow/kubeflow#5082] opened 2020-06-19 03:33 UTC
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have installed kubeflow on existing kubernets cluster locally. I encoutered this problem when start a notebook server through kubeflow UI. Kubectl describe information  of this pod is below: 
Name:               my-first-notebook-0
Namespace:          test1
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=my-first-notebook
                    controller-revision-hash=my-first-notebook-c54c6b6d8
                    notebook-name=my-first-notebook
                    statefulset=my-first-notebook
                    statefulset.kubernetes.io/pod-name=my-first-notebook-0
Annotations:        sidecar.istio.io/status:
                      {"version":"5f3ae3613c7945ef767cb9fd594596bc001ff3ab915f12e4379c0cb5648d2729","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:             Pending
IP:                 
Controlled By:      StatefulSet/my-first-notebook
Init Containers:
  istio-init:
    Image:      docker.io/istio/proxy_init:1.1.6
    Port:       <none>
    Host Port:  <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      8888
      -d
      15020
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:       <none>
Containers:
  my-first-notebook:
    Image:      gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v-base-ef41372-1177829795472347138
    Port:       8888/TCP
    Host Port:  0/TCP
    Requests:
      cpu:     500m
      memory:  1Gi
    Environment:
      NB_PREFIX:  /notebook/test1/my-first-notebook
    Mounts:
      /dev/shm from dshm (rw)
      /home/jovyan from workspace-my-first-notebook (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-editor-token-8cpc6 (ro)
  istio-proxy:
    Image:      docker.io/istio/proxyv2:1.1.6
    Port:       15090/TCP
    Host Port:  0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      my-first-notebook.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.istio-system:9411
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts
      8888
    Limits:
      cpu:     2
      memory:  128Mi
    Requests:
      cpu:      10m
      memory:   40Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                      my-first-notebook-0 (v1:metadata.name)
      POD_NAMESPACE:                 test1 (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           my-first-notebook-0 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   test1 (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_LABELS:         {"app":"my-first-notebook","controller-revision-hash":"my-first-notebook-c54c6b6d8","notebook-name":"my-first-notebook","statefulset":"my-first-notebook","statefulset.kubernetes.io/pod-name":"my-first-notebook-0"}
                                     
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-editor-token-8cpc6 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  workspace-my-first-notebook:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  workspace-my-first-notebook
    ReadOnly:   false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  default-editor-token-8cpc6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-editor-token-8cpc6
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.default-editor
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                      From               Message
  ----     ------            ----                     ----               -------
  Warning  FailedScheduling  3m40s (x208 over 5h13m)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) didn't find available persistent volumes to bind.

**What did you expect to happen:**
Run the notebook server sucessfully in the kubernetes cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I create a local StorageClass as default StorageClass. I guess the cause of bug is that local StorageClass does not have a internal provisioner. The StorageClass configuration is below(following the offical website):
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0
- kfctl version: (use `kfctl version`): v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`) kubeadm
- Kubernetes version: (use `kubectl version`): 1.14.1
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

**Comment by jlewi** [comment] 2020-06-19 12:13
I believe the UI has an option not to attach a PV; you could try that.

Otherwise it looks like you will need to fix your cluster to properly provision PVs.

/cc @kimwnasptd

**Comment by dwang55** [comment] 2020-06-22 06:12
> I believe the UI has an option not to attach a PV; you could try that.
> 
> Otherwise it looks like you will need to fix your cluster to properly provision PVs.
> 
> /cc @kimwnasptd

Thanks for replying!
It seems that there is not an option about attaching PV in kubeflow UI.
I will try the second option and update here if I have any results.

**Comment by dwang55** [comment] 2020-06-27 09:02
There is an option 

> I believe the UI has an option not to attach a PV; you could try that.
> 
> Otherwise it looks like you will need to fix your cluster to properly provision PVs.
> 
> /cc @kimwnasptd

Sorry, I find there is an option in kubeflow UI that not to attach PV and have tried it. But I encountered another problem. After launch the notebook server, the container in this pod have error logs below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1766, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1380, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'

**Comment by jlewi** [comment] 2020-06-29 14:14
Looks like kubeflow/kubeflow#4863

Closing in favor of that issue.

Duplicate of #4863

**Closed by jlewi** 2020-06-29 14:14 UTC
Labels: area/jupyter, kind/bug, priority/p2
