### ISSUE TITLE
Unified Serving Endpoint

### ISSUE THREAD

**Issue by amalow** [kubeflow/kubeflow#1947] opened 2018-11-13 06:28 UTC
Hi All,

Love the project. I was reviewing the documentation and saw a number of different guides for serving a model depending on the framework being used, this is a necessary evil to some degree but it seems to me that to some degree the Ingestion interface (be it gRPC or REST) could be a single service and then redirect the traffic to required route.

e.g
For a TF Serving Job
`Inference Service -> Service Proxy -> TFServing`
or for a Seldon Core Job
`Inference Service -> Ambassador -> Seldon serving`
or for any other service 
` Inference Service -> Service Proxy -> Framework serving interface`

To the consumer the underlying framework is (somewhat) transparent. Considering Seldon already does this with Ambassador to some degree perhaps it could be used?

**Comment by jlewi** [comment] 2018-11-17 23:15
Is the issue hiding gRPC vs. REST from the user?

TFServing already exposes REST and gRPC endpoints. Seldon core I believe does the same.

We already have a reverse proxy with Ambassador that allows serving multiple endpoints behind a common ingress and we are investigating using ISTIO more.

Does envoy provide some generic support for proxying gRPC to REST and vice versa?

The different frameworks all have different APIs for serving. How would you deal with that?  There is a long standing issue (#102) to define a common inference API but I don't see that gaining much traction.

**Comment by amalow** [comment] 2018-11-18 22:04
Not so much hiding gRPC vs REST from the user but the frameworks underlying the service, does an end-user need to know a model is being served out of Seldon Core vs TF Serving. That being said it would be troublesome from a common interface standpoint if some endpoints could do both and others could do only REST.

It appears that envoy [does](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/grpc) have some of that generic support through `gRPC-web` and `gRPC-JSON`. Perhaps this is worth investigating further, I'm happy to dive into this if you'd like?

**Comment by amalow** [comment] 2018-11-19 03:32
Agreed, is it worth moving this to #102 to revive discussion?

**Comment by cliveseldon** [comment] 2018-11-19 06:59
There are two obvious options. Keep the same different APIs and have a unified API in front and then a translation step to forward requests. This is what we have done so far in Seldon which supports [OpenVINO](https://github.com/SeldonIO/seldon-core/tree/master/examples/models/openvino), [TensorRT](https://github.com/SeldonIO/seldon-core/tree/master/integrations/nvidia-inference-server), [TFServing](https://github.com/SeldonIO/seldon-core/tree/master/integrations/tfserving), as well as [Intel ngraph](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/onnx_resnet50/onnx_resnet50.ipynb) for ONNX. Seldon also supports both REST and gRPC with proto buffer and OpenAPI specs.

A second step would be to create a generic API and have each product provide an integration to it but that is obviously more difficult and more long term and depends on something like https://www.linuxfoundation.org/projects/deep-learning/ coalesing on an industry wide set of APIs and individual projects working on integrations.

**Comment by Jeffwan** [comment] 2018-12-11 07:20
@jlewi  Since TF has native REST API support, is `http-proxy` in k8s-model-server still helpful?  Looks like only Tensorflow projects use it for historical reason. If this is needed, I can help clean them up.

**Comment by jlewi** [comment] 2018-12-27 02:50
@Jeffwan I think http-proxy in k8s-model-server is no longer used except for older versions of TFServing. If you're willing to clean it up I think that would be useful but double check with @lluunn first and I'd suggest filing a separate issue.

@amalow per your comment I'm marking this as a duplicate and closing it.

Duplicate of #102

**Comment by jlewi** [comment] 2018-12-27 02:50
Duplicate of #102

**Closed by jlewi** 2018-12-27 02:50 UTC
Labels: area/inference, community/discussion
