### ISSUE TITLE
Support custom namespaces

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/kubeflow#3967] opened 2019-08-21 14:35 UTC
/kind feature

**Why you need this feature:**
In shared infrastructure it's often, like in our case, not possible to use arbitrary namespaces but they need to follow a specific schema. That makes it impossible to deploy kubeflow right now since it has various assumptions about the namespaces it runs in.

While kubeflow config already has a namespace field, setting it leads to errors when applying the manifests:
```
ERRO[0163] Failed to create Istio Gateway: namespaces "kubeflow" not found  filename="existing_arrikto/existing.go:457"
```

**Describe the solution you'd like:**
kubeflow should use the namespace as defined in the config. There should be also an option added for the namespace of the istio (and other namespaces that kubeflow might need).

**Comment by discordianfish** [comment] 2019-11-26 10:16
Can somebody make the bot ignore issue that are already triaged?

**Comment by DavidSpek** [comment] 2021-01-13 12:35
@yanniszark Maybe this can be implemented in the installation method for release 1.3?

**Comment by davemaung** [comment] 2021-04-29 19:21
This doesnt seemed to support release Kubeflow 1.3. i tried this steps. it would be great. if somebody can take a look at this? This is one of the issues item that is blocking Kubeflow from being deploy in our Production environment due to  our company policy and cost saving to share multiple kubeflow version in single shared Kubernetes cluster.


1. download https://github.com/kubeflow/manifests/tree/v1.3.0
2. replace **namespace** : kubeflow with **namespace : mykf** in all file in manifests folder
3. run while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
4. All pods are running except metadata pods 
kubectl get pods -n mykf
NAME                                                        READY   STATUS             RESTARTS   AGE
metadata-grpc-deployment-9d547547d-72qsj                    1/2     CrashLoopBackOff   11         34m
metadata-writer-6cbc87bf5-h977z                             1/2     CrashLoopBackOff   9          41m
5. When i checked error on metadata-writer-6cbc87bf5-h977z pods
                                                                                                                                                   │
│ Failed to access the Metadata store. Exception: "no healthy upstream"                                                                                                                                                     │
│ Traceback (most recent call last):                                                                                                                                                                                        │
│   File "/kfp/metadata_writer/metadata_writer.py", line 63, in <module>                                                                                                                                                    │
│     mlmd_store = connect_to_mlmd()                                                                                                                                                                                        │
│   File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd                                                                                                                                            │
│     raise RuntimeError('Could not connect to the Metadata store.')                                                                                                                                                        │
│ RuntimeError: Could not connect to the Metadata store.                                                                                                                                                                    │
│ stream closed                           

6. When i check mysql database  metadb db is not created. where and how metadb is created?

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+

**Comment by andreyvelich** [comment] 2024-10-17 16:26
Duplicate of: https://github.com/kubeflow/kubeflow/issues/5449

**Closed by andreyvelich** 2024-10-17 16:26 UTC
Labels: kind/feature, priority/p2, area/kfctl, lifecycle/frozen
