### ISSUE TITLE
Need confirmation on kubeflow on kubernetes 1.16

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/kubeflow#4228] opened 2019-10-04 06:24 UTC
/kind bug
What steps did you take and what happened:
[A clear and concise description of what the bug is.]
 Installed kubeflow on kubernetes 1.15 
using
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/ you apply https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml 

This brought manifests with different version

get errors like the below
no matches for kind "deployment" in version "extensions/v1beta1"
error: unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta2"
What did you expect to happen:
all the pods to show up in
kubectl get pods -n kubeflow
Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
Environment:
Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
kfctl version: (use kfctl version):
kfctl v0.6.2-0-g47a0e4c7
Kubernetes platform: (e.g. minikube)
Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by cyrilthank** [comment] 2019-10-04 06:25
Currently our poc is stalled 
due to issues
https://github.com/kubeflow/kubeflow/issues/4184

we need direction on which version of kubernetes and kubeflow to use to get a working poc to demonstrate the viability of kubeflow as a platform of choice for us

**Comment by cyrilthank** [comment] 2019-10-04 09:12
Please note we are getting errors like

error: unable to recognize "STDIN": no matches for kind "Deployment" in version "extensions/v1beta1"

unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta2"

The CustomResourceDefinition "seldondeployments.machinelearning.seldon.io" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[children].items: Required value: must be specified
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[children].items.type: Required value: must not be empty for specified array items
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.properties[endpoint].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.type: Required value: must not be empty for specified array items
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[endpoint].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[configMapKeyRef].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[fieldRef].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[resourceFieldRef].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].properties[secretKeyRef].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.properties[valueFrom].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[env].items.type: Required value: must not be empty for specified array items
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[svcOrchSpec].properties[resources].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.type: Required value: must not be empty for specified array items
* spec.validation.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root


when we attempt the kubeflow 0.6.2 install on kubernetes 1.16.1

kindly advise

[kubernetes_upgrade_to_1_16_01_kubeflow_deploy_error_04Oct.txt](https://github.com/kubeflow/kubeflow/files/3689790/kubernetes_upgrade_to_1_16_01_kubeflow_deploy_error_04Oct.txt)

**Comment by cyrilthank** [comment] 2019-10-09 08:47
Any updates on this please?

**Comment by yanniszark** [comment] 2019-10-09 12:41
Hi @cyrilthank.
It seems that K8s 1.16 has deprecated "extensions/v1beta1" and the v0.6.2 release depends on them.
Can you try with an earlier version, like K8s 1.14?
Kubeflow v0.7 should work with 1.16.

**Comment by cyrilthank** [comment] 2019-10-09 12:51
Thanks @yanniszark  for diligently chasing this down for me.

Question:
can you please share the steps to downgrade our 1.16 version k8s to 1.14

also can you please share around when is kubeflow0.7 due?

**Comment by jlewi** [comment] 2019-10-23 05:17
@cyrilthank Downgrading Kubernetes will really depend on how you are installing managing Kubeflow.
Kubeflow 0.7.0 should be available next week.

**Comment by jlewi** [comment] 2019-10-24 14:28
Duplicate of kubeflow/manifests#375

**Closed** 2019-10-24 14:28 UTC
Labels: area/testing, kind/feature, priority/p1, problems/k8s

**Comment by cyrilthank** [comment] 2019-10-29 09:07
> 
> 
> @cyrilthank Downgrading Kubernetes will really depend on how you are installing managing Kubeflow.
> Kubeflow 0.7.0 should be available next week.

can you please update this issue when KubeFlow 0.7.0 is available

Also much appreciate it if you could also advise the Kubernetes version on which  KubeFlow 0.7.0 is tested

**Comment by cyrilthank** [comment] 2019-10-29 09:09
also created separate issue https://github.com/kubeflow/kubeflow/issues/4423 since the issue https://github.com/kubeflow/kubeflow/issues/4228 is closed
