### ISSUE TITLE
Kubeflow upgrade from 1.0 to 1.1

### ISSUE THREAD

**Issue by estrellafelipe** [kubeflow/kubeflow#5278] opened 2020-09-04 22:22 UTC
/kind question

Hello,

is there a guide to upgrade kubeflow from version 1.0 to 1.1 in GKE?

Regards,

**Comment by Luke035** [comment] 2020-09-08 14:01
It'd be very helpful to have a guide for upgrading kubeflow without having to re-install it!

**Comment by jbottum** [comment] 2020-09-09 01:23
@jlewi is there someone on the GCP that would like to respond to this issue?

**Comment by jlewi** [comment] 2020-09-09 14:20
Duplicate of kubeflow/gcp-blueprints#103

**Closed by jlewi** 2020-09-09 14:20 UTC
Labels: area/gcp, kind/question, priority/p2
