### ISSUE TITLE
Installation errors with kfctl.sh

### ISSUE THREAD

**Issue by mgyong** [kubeflow/kubeflow#1733] opened 2018-10-09 01:40 UTC
Started the installation process with 
../ scripts/kfctl.sh init ${KFAPP} --platform gcp

When i tried to run the ./scripts/kfctl.sh generate k8s
I am getting error
ERROR Registries using protocol 'github' must provide URIs beginning with 'github.com' (optionally prefaced with 'http', 'https', 'www', and so on

When i tried ../scripts/kfctl.sh apply k8s
I am getting errors
ERROR Could not create "default"

Installation script failed to create any kubeflow installation in my gke cluster
```
[kubeflow (⎈ |gke-central:default)]$ ../scripts/kfctl.sh generate k8s
+ COMMAND=generate
+ WHAT=k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname ../scripts/kfctl.sh
++ cd ../scripts
++ pwd
+ DIR=/home/mgyong/code/kubeflow-src/scripts
+ source /home/mgyong/code/kubeflow-src/scripts/util.sh
+ source /home/mgyong/code/kubeflow-src/scripts/gke/util.sh
++ set -xe
+ source /home/mgyong/code/kubeflow-src/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' generate == init ']'
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' -z generate ']'
+ '[' -z k8s ']'
+ check_install ks
+ which ks
+ check_install kubectl
+ which kubectl
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' generate == generate ']'
+ '[' k8s == platform ']'
+ '[' k8s == all ']'
+ '[' k8s == k8s ']'
+ createKsApp
+ pushd .
~/code/kubeflow-src/kubeflow ~/code/kubeflow-src/kubeflow
++ dirname /home/mgyong/code/kubeflow-src/kubeflow/ks_app
+ cd /home/mgyong/code/kubeflow-src/kubeflow
++ basename /home/mgyong/code/kubeflow-src/kubeflow/ks_app
+ ks init ks_app
INFO  Using context 'gke-central' from the kubeconfig file specified at the environment variable $KUBECONFIG
INFO  Creating environment "default" with namespace "default", pointing to cluster at address "https://35.232.23.14"
INFO  Generating ksonnet-lib data at path '/home/mgyong/code/kubeflow-src/kubeflow/ks_app/lib/v1.7.0'
INFO  ksonnet app successfully created! Next, try creating a component with `ks generate`.
+ cd /home/mgyong/code/kubeflow-src/kubeflow/ks_app
+ ks env rm default
INFO  Deleting environment "default" with metadata at path "/home/mgyong/code/kubeflow-src/kubeflow/ks_app/environments/default"
INFO  Successfully removed environment 'default'
+ ks registry add kubeflow /home/mgyong/code/kubeflow-src/kubeflow
ERROR Registries using protocol 'github' must provide URIs beginning with 'github.com' (optionally prefaced with 'http', 'https', 'www', and so on
```

```
[kubeflow (⎈ |gke-central:default)]$ ../scripts/kfctl.sh apply k8s
+ COMMAND=apply
+ WHAT=k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname ../scripts/kfctl.sh
++ cd ../scripts
++ pwd
+ DIR=/home/mgyong/code/kubeflow-src/scripts
+ source /home/mgyong/code/kubeflow-src/scripts/util.sh
+ source /home/mgyong/code/kubeflow-src/scripts/gke/util.sh
++ set -xe
+ source /home/mgyong/code/kubeflow-src/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' apply == init ']'
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' -z apply ']'
+ '[' -z k8s ']'
+ check_install ks
+ which ks
+ check_install kubectl
+ which kubectl
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' apply == generate ']'
+ '[' apply == apply ']'
+ '[' k8s == platform ']'
+ '[' k8s == all ']'
+ '[' k8s == k8s ']'
+ ksApply
+ pushd /home/mgyong/code/kubeflow-src/kubeflow/ks_app
~/code/kubeflow-src/kubeflow/ks_app ~/code/kubeflow-src/kubeflow
+ '[' gcp == minikube ']'
+ set +e
++ ks env describe default
+ O='describe default is not a valid subcommand

Usage:
  ks env [flags]
  ks env [command]

Available Commands:
  add         Add a new environment to a ksonnet application
  list        List all environments in a ksonnet application
  rm          Delete an environment from a ksonnet application
  set         Set environment-specific fields (name, namespace, server)

Flags:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -h, --help                           help for env
      --insecure-skip-tls-verify       If true, the server'\''s certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to a kubeconfig file. Alternative to env var $KUBECONFIG.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --password string                Password for basic authentication to the API server
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don'\''t timeout requests. (default "0")
      --server string                  The address and port of the Kubernetes API server
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
      --username string                Username for basic authentication to the API server

Global Flags:
  -v, --verbose count[=-1]   Increase verbosity. May be given multiple times.

Use "ks env [command] --help" for more information about a command.'
+ RESULT=1
+ set -e
+ '[' 1 -eq 0 ']'
+ ks env add default --namespace kubeflow
INFO  Using context 'gke-central' from the kubeconfig file specified at the environment variable $KUBECONFIG
INFO  Creating environment "default" with namespace "kubeflow", pointing to cluster at address "https://35.232.23.14"
+ ks apply default -c ambassador
+ ks apply default -c jupyterhub
+ ks apply default -c centraldashboard
+ ks apply default -c tf-job-operator
+ ks apply default -c argo
+ ks apply default -c katib
+ ks apply default -c spartakus
+ popd
~/code/kubeflow-src/kubeflow
+ set +x
+ '[' gcp == gcp ']'
+ gcpKsApply
+ pushd .
~/code/kubeflow-src/kubeflow ~/code/kubeflow-src/kubeflow
+ cd /home/mgyong/code/kubeflow-src/kubeflow/ks_app
+ set +e
++ ks env describe default
+ O='describe default is not a valid subcommand

Usage:
  ks env [flags]
  ks env [command]

Available Commands:
  add         Add a new environment to a ksonnet application
  list        List all environments in a ksonnet application
  rm          Delete an environment from a ksonnet application
  set         Set environment-specific fields (name, namespace, server)

Flags:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -h, --help                           help for env
      --insecure-skip-tls-verify       If true, the server'\''s certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to a kubeconfig file. Alternative to env var $KUBECONFIG.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --password string                Password for basic authentication to the API server
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don'\''t timeout requests. (default "0")
      --server string                  The address and port of the Kubernetes API server
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
      --username string                Username for basic authentication to the API server

Global Flags:
  -v, --verbose count[=-1]   Increase verbosity. May be given multiple times.

Use "ks env [command] --help" for more information about a command.'
+ RESULT=1
+ set -e
+ '[' 1 -eq 0 ']'
+ ks env add default --namespace kubeflow
INFO  Using context 'gke-central' from the kubeconfig file specified at the environment variable $KUBECONFIG
ERROR Could not create "default"
```

**Comment by jlewi** [comment] 2018-10-09 13:06
Which version of ksonnet are you using

```
ks version
```

I believe we currently test with the 0.11 and have high confidence it works with 0.12. Haven't checked with ksonnet 0.13.

It looks like its try to interpret a local registry as a GitHub registry. I suspect this is due to an older ksonnet version which didn't support local registries.

```
+ ks registry add kubeflow /home/mgyong/code/kubeflow-src/kubeflow
ERROR Registries using protocol 'github' must provide URIs beginning with 'github.com' (optionally prefaced with 'http', 'https', 'www', and so on
```

**Comment by mgyong** [comment] 2018-10-10 21:34
The error is ksonnet 0.9.2. I upgraded to ksonnet 0.13. The generate k8s step works but there is still error with the apply ks step
ERROR handle object: creating object: creating object: namespaces "kubeflow" not found 

```
[kubeflow (⎈ |gke-central:default)]$ ks version
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

```
[kubeflow (⎈ |gke-central:default)]$ ../scripts/kfctl.sh apply k8s
+ COMMAND=apply
+ WHAT=k8s
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ MIN_CLUSTER_VERSION=1.10.7-gke.2
+++ dirname ../scripts/kfctl.sh
++ cd ../scripts
++ pwd
+ DIR=/home/mgyong/code/kubeflow-src/scripts
+ source /home/mgyong/code/kubeflow-src/scripts/util.sh
+ source /home/mgyong/code/kubeflow-src/scripts/gke/util.sh
++ set -xe
+ source /home/mgyong/code/kubeflow-src/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=false
+ '[' apply == init ']'
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' -z apply ']'
+ '[' -z k8s ']'
+ check_install ks
+ which ks
+ check_install kubectl
+ which kubectl
+ source env.sh
++ PLATFORM=gke
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=null
++ PLATFORM=gcp
++ KUBEFLOW_REPO=/home/mgyong/code/kubeflow-src
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_KS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_CLOUD=gke
++ PROJECT=tpu-tutorial
++ DEPLOYMENT_NAME=kubeflow
++ KUBEFLOW_DM_DIR=/home/mgyong/code/kubeflow-src/kubeflow/gcp_config
++ KUBEFLOW_SECRETS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/secrets
++ KUBEFLOW_K8S_MANIFESTS_DIR=/home/mgyong/code/kubeflow-src/kubeflow/k8s_specs
++ KUBEFLOW_K8S_CONTEXT=kubeflow
++ ZONE=europe-west4-a
++ EMAIL=mgyong@google.com
++ KUBEFLOW_IP_NAME=kubeflow-ip
++ KUBEFLOW_ENDPOINT_NAME=kubeflow
++ KUBEFLOW_HOSTNAME=kubeflow.endpoints.tpu-tutorial.cloud.goog
++ CONFIG_FILE=cluster-kubeflow.yaml
++ PROJECT_NUMBER=533303974321
++ CLUSTER_VERSION=1.10.7-gke.2
+ '[' apply == generate ']'
+ '[' apply == apply ']'
+ '[' k8s == platform ']'
+ '[' k8s == all ']'
+ '[' k8s == k8s ']'
+ ksApply
+ pushd /home/mgyong/code/kubeflow-src/kubeflow/ks_app
~/code/kubeflow-src/kubeflow/ks_app ~/code/kubeflow-src/kubeflow
+ '[' gcp == minikube ']'
+ set +e
++ ks env describe default
+ O='name: default
kubernetesversion: v1.10.6
path: default
destination:
  server: https://35.232.23.14
  namespace: kubeflow
targets: []
libraries: {}'
+ RESULT=0
+ set -e
+ '[' 0 -eq 0 ']'
+ echo environment default already exists
environment default already exists
+ ks apply default -c ambassador
INFO Applying services kubeflow.ambassador        
INFO Creating non-existent services kubeflow.ambassador 
ERROR handle object: creating object: creating object: namespaces "kubeflow" not found 
```

**Comment by jlewi** [comment] 2018-10-11 03:43
You should be able to create the namespace kubeflow.

I think this is a bug with the namespace being created during the platform stage and not the k8s stage.

**Comment by jlewi** [comment] 2018-10-11 03:56
Duplicate of #1675

**Closed by jlewi** 2018-10-11 03:56 UTC
Labels: area/ksonnet, community/question, platform/gcp
