### ISSUE TITLE
Attach data volumes to multiple notebook servers

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#5003] opened 2020-05-07 14:29 UTC
/kind question

**Question:**
I noticed that a data volume can only be attached to one notebook server at a time. For example, if I create a server and attach dataVolume1 to it, then I try to create another notebook server and use existing dataVolume1, the creation will keep failing because it cannot mount dataVolume1. It will work only when you delete the first notebook server.

Is this by-design? Seems it is reasonable to re-use the same data volume for multiple running notebook servers. But if by-design, then maybe we need a better failure experience to communicate this clearly to the user, rather than keep waiting for the server to start and then have to dig into logs to understand what is going on.

**Comment by jbottum** [comment] 2020-05-07 14:42
@abdulsalama @cspavlou Hey Abdul, thanks for your question.   Would you please provide a little more on the expected behavior?   Would both users be able to make changes at the same time?  Or could the second user create (and own) a mutable clone of the the volume and make changes to their clone?

**Comment by abdulsalama** [comment] 2020-05-07 16:12
yeah I would expect both users to be able to make changes at the same time.

**Comment by jbottum** [comment] 2020-05-08 17:50
@abdulsalama I spoke to the Arrikto Rok engineers, RWX with notebooks is supported.    I am not sure if other storage solutions / storageclasses can support.   Please let me know if you would like a demo.

**Comment by ConverJens** [comment] 2020-05-11 12:43
@abdulsalama  Do you refer to the workspace volume or the data volume? What kind of volume are you using? Your issue probably depends on which storage class you are using.

I have used the same pvc as data volume for several notebooks simultaneously.

**Comment by abdulsalama** [comment] 2020-05-11 17:21
> @abdulsalama I spoke to the Arrikto Rok engineers, RWX with notebooks is supported. I am not sure if other storage solutions / storageclasses can support. Please let me know if you would like a demo.

@jbottum thanks a lot Josh. yeah a demo would be great :)

**Comment by abdulsalama** [comment] 2020-05-11 17:24
> @abdulsalama Do you refer to the workspace volume or the data volume? What kind of volume are you using? Your issue probably depends on which storage class you are using.
> 
> I have used the same pvc as data volume for several notebooks simultaneously.

Data volume. hmm I don't think kubeflow gives any option to specify the kind of volume? So I'm just going with whatever the default.

Which pvc kind you used? would that depends on our configuration for the kubeflow installation?

**Comment by ConverJens** [comment] 2020-05-12 07:20
@abdulsalama First of all, where are you running KubeFlow (GCP, AWS, on-prem...)?

KubeFlow does not provide any volumes by itself, it is just a collection of services running in kubernetes. So any storage needs to be configured in Kubernetes. You should probably check with whoever is managing you kubernetes cluster what kind of storage you have access to. I think it would be helpful for you to read up a bit in storage in kubernetes to understand the pros and cons of different alternatives: https://kubernetes.io/docs/concepts/storage/persistent-volumes/.

You can't choose which kind of storage class to use when setting up the notebook server, the default for KubeFlow is that is always uses the storage class marked as default in kubernetes. 

I have set up Ranchers local-path-provisioner and also a remote filessytem called Gluster. Using any of these I could access the same volume from multiple locations at once.

Good luck!

**Comment by abdulsalama** [comment] 2020-05-12 17:53
@ConverJens I see, this helps a lot. I will take a deeper look into this. Thanks so much for the guidance :)

**Comment by jbottum** [comment] 2020-05-13 17:50
@abdulsalama I have lined up a SME to discuss the current capability.  From there we can provide a demo and discuss what extensions may be needed.    Often we have time in the early mornings (8am PST).   Please let me know your preference.   josh.bottum@arrikto.com

**Comment by jlewi** [comment] 2020-05-16 22:57
Closing this issue because I think @ConverJens comment above resolved it.

**Closed** 2020-05-16 22:56 UTC
Labels: area/jupyter, kind/question, priority/p2
