### ISSUE TITLE
Kubeflow on K8s - "kfctl apply" throws "Unknown variable: x" error ; ksonnet doesn't support K8s 1.15 or later

### ISSUE THREAD

**Issue by aktivalux** [kubeflow/kubeflow#3544] opened 2019-06-25 08:06 UTC
I tried to install kubeflow v0.5.1 on an existing K8s "cluster" (it is a single node microk8s cluster on an Ubuntu Host) by following the instructions from this page: [https://www.kubeflow.org/docs/started/getting-started-k8s/](https://www.kubeflow.org/docs/started/getting-started-k8s/). At least for me the instructions seem to not work.

I am trying to deploy kubeflow from my laptop onto the microk8s "clsuter" which runs on a dedicated host.

However, the last command from the instructions - `kfctl apply all -V` - outputs just a list of errors. Except for the namespace creation nothing is deployed/created. Below an excerpt of the error which repeats itself and [you can find the full output here](https://gist.github.com/aktivalux/9e8c0d74e6dddea8bbb815799e45ebee).

```
INFO[0000] deploying kubeflow application                filename="cmd/apply.go:35"
INFO[0000] reading from /Users/.../cluster-init/kubeflow/kfapp/app.yaml  filename="coordinator/coordinator.go:341"
INFO[0000] reading from /Users/.../cluster-init/kubeflow/kfapp/app.yaml  filename="coordinator/coordinator.go:341"
INFO[0000] namespace: kubeflow                           filename="ksonnet/ksonnet.go:109"
ERRO[0004] (Will retry) Component ambassador apply failed; Error: find objects: /Users/.../cluster-init/kubeflow/kfapp/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

          "withX-Kubernetes-Embedded-Resource":: self + { "x-kubernetes-embedded-resource": x-kubernetes-embedded-resource },
  filename="ksonnet/ksonnet.go:174"
ERRO[0007] (Will retry) Component argo apply failed; Error: find objects: /Users/.../cluster-init/kubeflow/kfapp/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x


[...]
```

Used kfctl version
```bash
$ kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
```

Used ks version
```bash
$ ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

I slightly changed the commands so i do not have to modify the PATH/set the KFAPP variable:

```bash
./kfctl init mykfapp
cd mykfapp
../kfctl generate all -V
../kfctl apply all -V
```

Additionally I am on macOS Mojave using zsh as shell.

**Comment by aashish-sheshadri** [comment] 2019-06-25 17:53
I am facing the same issue. I am using minikube to get my k8s environment (no VM, driverless).

**Comment by jlewi** [comment] 2019-06-26 14:51
Are you using kubernetes 1.15?

It looks like the error

```
ERRO[0007] (Will retry) Component argo apply failed; Error: find objects: /Users/.../cluster-init/kubeflow/kfapp/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x
```

Is coming from the libsonnet file that ksonnet is auto-generating. I suspect there is an error specific to the 1.15 APis.

Unfortunately since ksonnet is deprecated the fix is probably going to be to wait for 0.6 which replaces ksonnet with kustomize.

**Comment by porterdarby** [comment] 2019-06-26 17:53
Is there a timeline on when that will be happening?

**Comment by aktivalux** [comment] 2019-06-26 19:22
@jlewi yes I am:
```
Server Version: version.Info{
Major:"1", 
Minor:"15", 
GitVersion:"v1.15.0", 
GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", 
GitTreeState:"clean", 
BuildDate:"2019-06-19T16:32:14Z", 
GoVersion:"go1.12.5",
Compiler:"gc", 
Platform:"linux/amd64"}
```

I have also tried using an older version of kubeflow (v0.4.1) and used the instructions available here https://github.com/Azure/kubeflow-labs/tree/master/4-kubeflow . Unfortunately also without luck.

I am actually only interested in the TFJob Ressource. Is there any workaround available except for downgrading the k8s cluster to something below <1.15?

**Comment by porterdarby** [comment] 2019-06-27 02:18
I was able to manage by downgrading to minikube 1.1 and using Kubernetes 1.14.3. This ended up causing the application to deploy but produce an error at the end, so I just re-ran the apply and it worked.

**Comment by rky0930** [comment] 2019-07-01 02:37
I have the same issue. I'm installing Kubeflow on my k8s without virtual machine. 
My cluster version is v1.15.0.  I tried to install KF 0.5.0 and 0.5.1 and i got "Unknown variable: x" Error. 
Any suggestion such as "Downgrade to specific cluster version or use specific ks version something like that" ?

**Comment by aktivalux** [comment] 2019-07-01 05:34
@rky0930 for now you can use an older kubernetes version such as 1.14.3 or 1.14.1 (that are the versions I have tested successfully). For the rest  you can just follow the official installation instructions and use the latest version of kubeflow and ksonnet/ks.

**Comment by aashish-sheshadri** [comment] 2019-07-01 22:35
Works once the Kubernetes version was downgraded.

**Comment by jlewi** [comment] 2019-07-01 23:33
#3559 is the tracking bug for 0.6.

We are working on cutting the RC now.

If you are willing to live on the edge and be a beta tester, we would really appreciate help trying out master and reporting bugs.

We are using #release in kubeflow.slack.com to coordinate.

To try on master check out master and then

```
cd bootstrap
make build-kfctl
```

**Comment by edowson** [comment] 2019-07-06 06:19
I tried building with the current master branch, commit 6f790f8f3b43d8048d9fbeff7e64857da264f83b,
and I get the following error:
```bash
go: finding google.golang.org/api v0.4.0
go: error loading module requirements
Makefile:68: recipe for target 'generate' failed
make: *** [generate] Error 1
```

```bash
$ go version
go version go1.12.6 linux/amd64
```

**Comment by edowson** [comment] 2019-07-06 06:56
I get the following error while trying to create a sample app

```bash
export KFAPP=my-kubeflow
# Default uses IAP.
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V
```

```bash
}  filename="kustomize/kustomize.go:164"
ERRO[0000] Couldn't find component istio-crds            filename="kustomize/kustomize.go:454"
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't find component istio-crds
Usage:
  kfctl generate [all(=default)|k8s|platform] [flags]

Flags:
      --email string      email if '--platform gcp'
  -h, --help              help for generate
      --hostname string   hostname if '--platform gcp'
      --ipName string     ipName if '--platform gcp'
      --mount-local       mount-local if '--platform minikube'
  -V, --verbose           verbose output default is false
      --zone string       zone if '--platform gcp'

couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't find component istio-crds
```

**Comment by QxiaoQ** [comment] 2019-08-06 02:43
> @rky0930 for now you can use an older kubernetes version such as 1.14.3 or 1.14.1 (that are the versions I have tested successfully). For the rest you can just follow the official installation instructions and use the latest version of kubeflow and ksonnet/ks.

Did not work for me when I deploy kubeflow on Kind.
Failed with kubeflow 0.5.1 , k8s 0.14.* /0.15  (Kind)，and ks 0.13.1.  
Still throw this error.

**Comment by QxiaoQ** [comment] 2019-08-06 08:31
I found a workaround way to solve this problem. 
My ENV: kubeflow 0.5.1 , k8s  1.14.4 (kind v0.4.0) ，and ks 0.13.1

Before run command "kfctl apply ..." , run " kind get clusters " . then this error will disappear.

Hope this information can help you with your kubeflow deployment or help us to fix this bug.

**Comment by jlewi** [comment] 2019-08-06 13:52
Thanks @QxiaoQ I'm going to close this issue. 

For folks hitting this error I recommend trying Kubeflow 0.6 because the problem is that ksonnet doesn't support newer versions of Kubernetes.

If you must use an earlier version of Kubeflow you can try the workaround @QxiaoQ mentions above.

**Closed by jlewi** 2019-08-06 13:52 UTC
Labels: community/question, kind/bug

**Comment by fenglixa** [comment] 2019-10-20 13:15
Cannot follow below document because of this issue: https://github.com/kubeflow/examples/blob/master/object_detection/setup.md. 
Wish this issue could be addressed. Thanks
