### ISSUE TITLE
no matches for kind "Profile" in version "kubeflow.org/v1alpha1"

### ISSUE THREAD

**Issue by durch** [kubeflow/kubeflow#4047] opened 2019-09-02 14:22 UTC
/kind bug

**What steps did you take and what happened:**
 Deploying `kubeflow` to a new `aks-engine` k8s cluster.  `kfctl init` and `kfctl generate all` complete successfully, `kfctl apply all` throws:

```
couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create default profile from &{{Profile kubeflow.org/v1alpha1} {kubeflow-anonymous      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{User  anonymous }} { }} Error: no matches for kind "Profile" in version "kubeflow.org/v1alpha1"
```
	
**What did you expect to happen:**
Kubeflow to be deployed

**Environment:**

- kfctl version: `v0.6.2`
- Kubernetes platform: `aks-engine`
- Kubernetes version: 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- OS: Ubuntu 16.04.6 LTS

**Comment by vjrantal** [comment] 2019-09-03 10:18
@durch I can reproduce the same issue.

As a temporary workaround, I have tested that using following config for the init works in AKS:

```
kfctl init ${KFAPP} --config https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.2/bootstrap/config/kfctl_k8s_istio.0.6.2.yaml
```

More details about this installation option from https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/.

In my opinion, it would be a good idea to keep this issue open until running kfctl without any config flag works. I wonder would above configuration be a good default or what is the expected result without user-defined config?

**Comment by durch** [comment] 2019-09-04 08:21
Thank you @vjrantal I can confirm that this fixes the problem, I'd sure take the above as default, or at least update the docs so that its clear that a config needs to be passed in and is not magically inferred from the `kfctl` version.

**Comment by vjrantal** [comment] 2019-09-04 08:26
@durch Today, my PR was merged and this is now included in the docs at https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/.

**Comment by jlewi** [comment] 2019-09-09 01:52
@durch You are correct  --config needs to be provided.

Thanks @vjrantal; I'm going to close this since it looks like your PR fixed this issue.

**Closed by jlewi** 2019-09-09 01:52 UTC
Labels: kind/bug
