### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/kubeflow#2852] opened 2019-03-28 23:20 UTC
I and others have recently been seeing the "upstream connect error or disconnect/reset before headers" error with some frequency.

It doesn't seem to be deterministic, for example, only one of the below requests failed.
<img width="342" alt="Screen Shot 2019-03-28 at 4 13 02 PM" src="https://user-images.githubusercontent.com/34456002/55198731-73101200-5174-11e9-84d3-3a3810b7d37f.png">
and upon refreshing the page, a different one, or more, of those same requests may fail.

The errors seem to dissipate after refreshing the page a few times, and I have not yet encountered this while port-forwarding, as opposed to using the "cluster.endpoints.project.cloud.goog" URL for my deployment.

I wasn't sure if this should be its own issue, or should be added to #1710.

**Comment by jlewi** [comment] 2019-03-31 21:49
I think upstream errors are an issue indicating that Ambassador thinks the backend its forwarding traffic to is unhealthy.

Are there particular backends you are seeing this error with?

**Comment by IronPan** [comment] 2019-04-04 04:18
I have seen the same error. This is happening to me when loading runs for a scheduled pipeline in pipeline UI. @jlewi Do you think this can be caused by pipeline?

**Comment by IronPan** [comment] 2019-04-04 04:20
FWIW this is happening among a batch of requests. the rest of the requests succeeded indicating the backend should be running.

**Comment by Ark-kun** [comment] 2019-04-08 21:12
> I think upstream errors are an issue indicating that Ambassador thinks the backend its forwarding traffic to is unhealthy.
> 
> Are there particular backends you are seeing this error with?

This is happening with the root Kubeflow UX on Kubeflow deploayments with IAM enabled.
It seems to be happening more and more. Previously it was happening after waiting for several hours. Not it can happen after few minutes.

**Comment by jlewi** [comment] 2019-04-16 02:35
@Ark-kun @IronPan @rileyjbauer when you observe this error can you take a look and provide your Ambassador pod logs?

I noticed this and when I looked at the logs (see below) I saw errors like the following

```
2019-04-16 00:40:50 kubewatch 0.37.0 ERROR: could not watch for Kubernetes service changes
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ff7bafb00>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 440, in main
    watch_loop(restarter)
  File "/ambassador/kubewatch.py", line 341, in watch_loop
    for evt in watched:
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 122, in stream
    resp = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 14358, in list_service_for_all_namespaces
    (data) = self.list_service_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 14455, in list_service_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.7.240.1', port=443): Max retries exceeded with url: /api/v1/services?watch=True (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ff7bafb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

If you observe this I might suggest trying to kill all your Ambassador pods.

```
kubectl delete pods -l service=ambassador
```

Ambassador tries to setup a K8s watch on the APIServer to be notified about service changes. It looks like it is having a problem establishing a connection to the APIServer.

The problem might be dependent on Ambassador as well as your APIServer; is your APIServer under a lot of load?

We are using
quay.io/datawire/ambassador:0.37.0

It might be worth trying a newer version of Ambassador.

@ellis-bigelow Do you recall what the performance issues with Ambassador you saw were?
[ambassador-5cf8cd97d5-pqrsw.pods.txt](https://github.com/kubeflow/kubeflow/files/3082778/ambassador-5cf8cd97d5-pqrsw.pods.txt)

**Comment by mcminis1** [comment] 2019-04-16 13:24
I ran into this problem while installing seldon to my cluster. I added it in twice, once as seldon and another time as seldon-core. This might have been the root cause for this issue, as well as argocd not syncing.

**Comment by rileyjbauer** [comment] 2019-04-16 20:46
Thanks for the direction @jlewi 

I tried killing the pods and after the new ones were up, but I continued to see the errors, and there didn't seem to be anything notable in the ambassador or API server pod logs

**Comment by pdmack** [comment] 2019-04-18 19:17
Seeing this too from recent master in EC2. Went down to 1 ambassador replica but no joy.

**Comment by ChrisMagnuson** [comment] 2019-05-03 14:27
Re posting as this thread seems more recent and active.

Envoy upstream had an [issue](https://github.com/envoyproxy/envoy/issues/6190) that only recently was fixed in dev but not yet fixed in any stable version where if the service it was proxying to ended the connection with a FIN/ACK envoy would responding with only an ACK and still leave it in its connection pool and would send the next request to that service using that connection.

The service would receive it, say a get request, and then send a RST as since it had already FIN/ACKed it doens't have a way to reply to the request.

Its a roll of the dice whether your request get loaded to an http connection in the pool that is already dead but envoy doesn't know it or goes to a live one which is why the symptoms of this issue are so intermittent.

May be related to what your seeing, to confirm if you have a way to capture packets on the service side you should see the weird behavoir of the service doing a FIN/ACK but envoy only responding with ACK and then sometime later sending another request on that TCP stream triggering the service to send a RST.

In envoy 1.10 they improved the message you get back so after upstream connect error or disconnect/reset before headers you will get more information, in my case got a message like connection terminated so if you upgrade to the latest envoy you may at least get additional information to confirm this what the source of the problem is even if it isn't this specific envoy issue.

**Comment by jlewi** [comment] 2019-06-02 17:09
Related issue: datawire/ambassador#504

**Comment by jlewi** [comment] 2019-07-28 20:08
0.6 so now available. If you are encountering this issue with a version early then Kubeflow 0.6 please try upgrading to 0.6.

Per the discussion in this thread we think this might have been due to an issue with envoy and/or Ambassador.

With 0.6 we've switched to ISTIO and are using much newer versions of envoy. So we need to see if this problem still reoccurs and then we can try to track it down.

**Comment by xiaohanhuang** [comment] 2019-08-08 01:18
Saw this with 0.6.1 in AWS

**Comment by amygdala** [comment] 2019-08-15 22:44
I saw this with 0.6.1 on GCP, using basic auth IIRC.
<img width="466" alt="63025119-66f3cb00-be5d-11e9-86b2-96135e0ccc8d" src="https://user-images.githubusercontent.com/115093/63131731-8ed55280-bf73-11e9-9f90-5d009439a14a.png">

**Comment by jlewi** [comment] 2019-08-16 03:14
basic auth is still using Ambassador and probably an older version of envoy.

If your seeing this error please clarify whether the error is persistent or whether a refresh fixes it.

**Comment by amygdala** [comment] 2019-08-16 14:07
In my case a few refreshes fixed it.

**Comment by arianyambao** [comment] 2019-10-03 06:39
In my case it is the problem on the resources (memory allocation, cpus, etc).
I didn't follow this one; https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements, that's why it's crushing down

In case you don't wanna look at the link, here are the recommended specs:
```
Minimum system requirements
The Kubernetes cluster must meet the following minimum requirements:

Kubernetes version 1.11 or later.
At least one worker node with a minimum of:
* 4 CPU
* 50 GB storage
* 12 GB memory
```

**Comment by jlewi** [comment] 2019-10-05 05:06
Thanks @arianyambao

I'm going to close this issue.

* upstream connect error or disconnect/reset before headers is a generic error that occurs when envoy is trying to forward traffic to a service that is unavailable.
* Threre's lots of reasons this can happen
* The migration to ISTIO with 0.6 seems to have reduced the general frequency of these errors.

**Closed by jlewi** 2019-10-05 05:06 UTC
Labels: area/ambassador, kind/bug, priority/p2

**Comment by ReggieCarey** [comment] 2021-02-24 23:36
Please upgrade the supported istio in Kubeflow to something supported and new.  Debugging potentially already repaired istio code is a horrible waste of time.

**Comment by dhanisahu** [comment] 2022-07-15 10:37
hi @jlewi @arianyambao @amygdala @xiaohanhuang @ChrisMagnuson

or anyone got the solution for the issue. iam getting as below not able to create notebook
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/88646670/179206834-bcbbdd89-d2c0-447c-9422-19dbe0652b56.png">


iam using kubeflow 1.5 with GKE 1.21

**Comment by jlewi** [comment] 2022-07-15 11:56
@dhanisahu unfortunately I have nothing to add to the thread. As the thread suggests this is usually an issue with ISTIO not being able to route to a healthy backend.

**Comment by dhanisahu** [comment] 2022-07-15 15:10
thank you for your response @jlewi i have resolve that issue from notebook dashboard but now iam getting same issue when i am opening the notebooks
<img width="816" alt="image" src="https://user-images.githubusercontent.com/88646670/179252195-c0b16b0d-40a8-40d7-bf63-ac19360b065e.png">

**Comment by pashtet04** [comment] 2023-07-24 09:47
We have restarted Notebook server pod and after this we got an error
`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111`

```
GET
https://ml.data.lmru.tech/notebook/main/myname/
[HTTP/2 503 Service Unavailable 386ms]
```

But Pod is healthy `2/2     Running`
Istio Proxy container started up

I tried to port-forward to that notebook and got strange output in console:
```
+ kubectl port-forward svc/myname 8080:80
Forwarding from 127.0.0.1:8080 -> 8888
Forwarding from [::1]:8080 -> 8888
Handling connection for 8080
E0724 12:28:48.169692  273925 portforward.go:409] an error occurred forwarding 8080 -> 8888: error forwarding port 8888 to pod 2387a8296929ad8272fddf8f066a5c4e8ec92eb724727
e4de1b36d3a8e888d83, uid : failed to execute portforward in network namespace "/var/run/netns/cni-ad620703-6cbc-c3b8-f71e-92e9ea90bbaf": failed to connect to localhost:8888
 inside namespace "2387a8296929ad8272fddf8f066a5c4e8ec92eb724727e4de1b36d3a8e888d83", IPv4: dial tcp4 127.0.0.1:8888: connect: connection refused IPv6 dial tcp6 [::1]:8888:
 connect: connection refused
error: lost connection to pod
```

In our case there no space left on worker node:
`OSError: [Errno 28] No space left on device: '/home/jovyan/.local/share/jupyter/runtime/jpserver-17066-open.html'`

**Comment by snyaupaneHP** [comment] 2024-12-12 03:43
Currently facing the similar issue frequently and at random:

`upstream connect error or disconnect/reset before headers. reset reason: remote reset
`
I am using[ envoy gateway ](https://gateway.envoyproxy.io/docs/) in my k8s cluster  and my backend runs on both REST and gRPC.

Stack:
protobuf ts, micronaut grpc runtime, envoy gateway
