### ISSUE TITLE
Investigate notebook container sidecar to enable in-notebook container builds

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#312] opened 2018-02-28 02:56 UTC
The issue of how best to build training images is an open question, see https://github.com/kubeflow/kubeflow/issues/300, https://github.com/kubeflow/kubeflow/issues/289

At first take it looks like this could be done from a JupyterHub notebook by attaching a Docker daemon sidecar, configured via [KubeSpawner](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py), similar to [this](https://gist.github.com/cwbeitel/4d0b90fa3b929635ca738c39f92cc6da).

@yuvipanda Do you see any problems with this approach?

**Comment by cwbeitel** [comment] 2018-02-28 20:41
On further investigation this seems to be a lower priority than experimenting with simply sharing code via NFS or another means and avoiding the need to build a new image for each training run.

**Comment by jlewi** [comment] 2018-03-01 00:33
Building Docker images from Jupyter and sharing code from NFS are orthogonal. 

Issue #192 is discussing how to build Docker images from Jupyter. Closing this issue in favor of that one.

Duplicate of #192

**Comment by jlewi** [comment] 2018-03-01 00:33
Duplicate of #192

**Closed by jlewi** 2018-03-01 00:33 UTC
