### ISSUE TITLE
Cannot logout from kubeflow dashboard UI

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#4925] opened 2020-04-06 21:19 UTC
/kind bug

**What steps did you take and what happened:**
I used kubeflow with istio_dex for authentication. User can authenticate and log-in fine. However, I don't see anyway to logout. Clicking on the user profile icon on right side does nothing. The only work-around is to explicitly delete the cookie.

**What did you expect to happen:**
User can log out by clicking the user profile icon on the top right side.

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): dev_local
- kfctl version: v1.0-0-g94c35cf
- Kubernetes platform: eks
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.4

**Comment by yanniszark** [comment] 2020-04-17 14:10
Closing as a duplicate of https://github.com/kubeflow/kubeflow/issues/4702
/close

**Closed by yanniszark** 2020-04-17 14:10 UTC
Labels: area/centraldashboard, kind/bug, kind/feature, priority/p2
