### ISSUE TITLE
Broken links for k8s-model-server docs

### ISSUE THREAD

**Issue by masroorhasan** [kubeflow/kubeflow#2027] opened 2018-12-02 01:38 UTC
I was following the examples on serving examples (specifically [k8s-model-serving](https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server)) and noticed broken links to docker and image components in the doc.

**Comment by lluunn** [comment] 2018-12-06 21:40
The whole dir needs some update, see #2054

**Comment by jlewi** [comment] 2019-01-28 02:52
Duplicate of #2054

**Closed by jlewi** 2019-01-28 02:52 UTC
Labels: area/docs, area/inference, priority/p1
