### ISSUE TITLE
update the version of knative bundled with KF

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#4651] opened 2020-01-14 19:21 UTC
/kind bug

Not sure if this should be a 'bug' or 'feature'.  However, seems that some KFServing integration problems (https://github.com/kubeflow/kfserving/issues/629) could probably be addressed if KF was using knative 0.11.

**Comment by alexwennerberg** [comment] 2020-01-14 19:41
Related KFServing issue: https://github.com/kubeflow/kfserving/pull/630

**Comment by jlewi** [comment] 2020-01-18 01:18
@jtfogarty this issue would probably be better assigned to kfserving
/area inference
/remove-area engprod

**Comment by jlewi** [comment] 2020-01-18 01:19
@animeshsingh @ellis-bigelow is there already an issue tracking this?

**Comment by animeshsingh** [comment] 2020-01-18 07:58
KNative upgrade is an original open issue here 
https://github.com/kubeflow/kfserving/issues/596

**Comment by jlewi** [comment] 2020-02-05 22:52
Duplicate of kubeflow/kfserving#596

**Closed by jlewi** 2020-02-05 22:52 UTC
Labels: area/inference, kind/bug, kind/feature, priority/p1
