### ISSUE TITLE
Kubeflow is not compatible with Kubernetes 1.18 due to Istio version 1.4.10

### ISSUE THREAD

**Issue by benjaminwinokur** [kubeflow/kubeflow#5703] opened 2021-03-16 15:21 UTC
/kind bug

**What steps did you take and what happened:**

Running a kubeflow deployment with kuberentes on v1.18 fails due to anthos istio v1.4.10 being used.

Logs from the istio pilot:

> 2021-03-16T01:42:11.557696Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:15019: connect: connection refused"
2021-03-16T01:42:11.707617Z	error	failed to approve CSR (csr-cae-ku-istio-sy-dns.isti-l9x7k4cmqg8xc957dr): certificatesigningrequests.certificates.k8s.io "csr-cae-ku-istio-sy-dns.isti-l9x7k4cmqg8xc957dr" is forbidden: user not permitted to approve requests with signerName "kubernetes.io/legacy-unknown"
2021-03-16T01:42:11.712397Z	error	failed to generate key and certificate for secret dns.istio-galley-service-account in namespace istio-system (error certificatesigningrequests.certificates.k8s.io "csr-cae-ku-istio-sy-dns.isti-l9x7k4cmqg8xc957dr" is forbidden: user not permitted to approve requests with signerName "kubernetes.io/legacy-unknown")
2021-03-16T01:42:11.712430Z	error	error when upserting secret (dns.istio-galley-service-account) in ns (istio-system): certificatesigningrequests.certificates.k8s.io "csr-cae-ku-istio-sy-dns.isti-l9x7k4cmqg8xc957dr" is forbidden: user not permitted to approve requests with signerName "kubernetes.io/legacy-unknown"

This issue has been documented and fixed in the official istio source 
https://github.com/istio/istio/pull/22084

**What did you expect to happen:**

A successful kubeflow deployment

**Anything else you would like to add:**

Upgrading anthos istio to a newer version with the fix for the breaking updates in the kubernetes v1.18 API will fix the issue. 

**Environment:**

- Kubeflow version: v1.2
- kfctl version: kfctl v1.2.0-0-gbc038f9
- Kubernetes platform: GKE
- Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by Bobgy** [comment] 2021-03-23 06:30
Duplicate of https://github.com/kubeflow/gcp-blueprints/issues/198

**Closed by Bobgy** 2021-03-23 06:30 UTC
Labels: kind/bug
