### ISSUE TITLE
kf 0.6.1 issues with UI for launching notebook server

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#3851] opened 2019-08-08 18:22 UTC
/kind bug

With KF v0.6.1, there are some problematic aspects of the UI.  

- It's possible to click 'new server' without setting the namespace.  Then, in setting up the server config, it's confusing to not be able to edit the namespace field.  The small (unset) pulldown at the top left of the page will probably not be noticed. 
Could we add the pulldown to the namespace field itself?
If not, could we add a caption to the Namespace field indicating what they need to do to fill it?
- If a namespace *is* selected from the server config page, it causes a page reload that bumps the user out to the previous page, which I think causes them to lose all the config info they've filled out?
- [from Sarah]  I did select a namespace from the dropdown (kubeflow-sarahmaddox) before clicking "new server". But now the "Namespace" field is set to "Default" and I can't edit it. I can't create my server either. Then 1/2 hour later: the value in the uneditable "Namespace" field has auto changed without my doing anything.
- [from Sarah] I clicked "Connect" to start the server. First problem: The namespace dropdown has reverted to "Select namespace". So I selected my namespace again.
Second problem: The resulting URL is `https://<name>.endpoints.ml-writers.cloud.goog/notebook/kubeflow-sarahmaddox/my-first-notebook/?ns=kubeflow-sarahmaddox` which gives the following screen:
![image](https://user-images.githubusercontent.com/115093/62727496-793db700-b9ce-11e9-9e2e-c57405514b07.png)

**Comment by kimwnasptd** [comment] 2019-08-09 16:40
hi @amygdala 

Regarding the first bullet I'll add some text + Tooltip in the Namespace field of the Form to inform the user to chose one from the dashboard. @amygdala @avdaredevil @prodonjs would it make sense in terms of UX if a user haven't selected a namespace, to not load the underlying UI and show a relative message? Just like the `Sorry, /notebook/blah/blah is not a valid page`, but with something like `Please select a Namespace from above to continue` or something similar?

Regarding the second bullet, @prodonjs @avdaredevil do you have any more insight in this one? Is this a behavior of the centraldashboard or something with jupyter webapp?

Third. The value of the namespace is passed from the centraldashboard to the jupyter webapp. But, I can't get my head around why it would take so much time to pass this change.

Fourth. I think we might need to open a separate issue for this one as we might need logs etc, so lets discuss it there to not convolute the conversation.

**Comment by prodonjs** [comment] 2019-08-09 17:06
I'm in agreement with the idea that for namespaced applications like Notebooks, it shouldn't be possible to navigate to that UI without first having selected a namespace. I think the dashboard should try to select it for the user by default upon load and have some stickiness to remember the most recently used namespace. At this point, it feels like making the user have to select a namespace before doing anything is an unnecessary first step that we can avoid to streamline the experience.

**Comment by avdaredevil** [comment] 2019-08-09 23:09
@kimwnasptd @prodonjs +1, I think now with MUI, we know what the owned the user's owned namespace is, so we could always default to that, otherwise fallback to `kubeflow` for Basic Auth setups.

**Comment by jlewi** [comment] 2019-09-10 13:41
There are two issues being discussed in the original bug report

1. @amygdala is reporting some possible areas for UX improvement in the interaction between the namespace selector and the notebook creator UI

     * It looks like the behavior is the same in v0.6.2
     * I would classify this as P1 or P2

1. Sarah is reporting issues with selecting namespace in the UI.

     * I suspect this is #3900 which should be fixed in 0.6.2

Since the second issue has been fixed; I'm reclassifying this as a P1 enhancement because the remaining work is to further improve the UI.

**Comment by cyrilthank** [comment] 2019-09-19 04:10
i am encountering this same issue and workraround in https://github.com/kubeflow/kubeflow/issues/3870 is not working
please help with workaround as this is a real show stopper for me

**Comment by jlewi** [comment] 2019-10-13 01:12
@cyrilthank if you are having a problem please open a new issue describing which version of Kubeflow you are using, how you are running it, and what the problem is.

**Comment by cyrilthank** [comment] 2019-10-14 04:26
Thank you Jeremy for your reply 
Short question
Which version of Kubeflow worksWith which version of Kubernetes 
We are trying to get a PoC done and so aren’t picky on the latest features currently we are dead duck due to several issues some pertaining to Kubernetes apiversion issues
Thank you
Cyril 
    On Sunday, October 13, 2019, 6:42:48 AM GMT+5:30, Jeremy Lewi <notifications@github.com> wrote:  
 
 
@cyrilthank if you are having a problem please open a new issue describing which version of Kubeflow you are using, how you are running it, and what the problem is.

**Comment by cyrilthank** [comment] 2019-10-16 08:06
@jlewi  can you please help with the below issues i have created for kubeflow

https://github.com/kubeflow/kubeflow/issues/4184
https://github.com/kubeflow/kubeflow/issues/4228

**Comment by jlewi** [comment] 2019-11-05 01:04
@kimwnasptd @prodonjs @avdaredevil

Which of the issues reported by @amygdala have been fixed in 0.7.0 and which still need to be fix?

* If we think some of the issues have been fixed can we verify that and update the bug?
* if there are some issues that still haven't been fixed can we file one issue per bug to fix them?

**Comment by prodonjs** [comment] 2019-11-05 14:16
> It's possible to click 'new server' without setting the namespace. Then, in setting up the server config, it's confusing to not be able to edit the namespace field. The small (unset) pulldown at the top left of the page will probably not be noticed.
Could we add the pulldown to the namespace field itself?
If not, could we add a caption to the Namespace field indicating what they need to do to fill it?

I think this is still an issue. #3863 accounts for this functionality.

> If a namespace is selected from the server config page, it causes a page reload that bumps the user out to the previous page, which I think causes them to lose all the config info they've filled out?

This issue has been fixed in 0.7.0 ([Screencast](https://screencast.googleplex.com/cast/NTczMTE5NjgyODkwOTU2OHw2NzQ1ZGQzOC0zNQ)).

> [from Sarah] I clicked "Connect" to start the server. First problem: The namespace dropdown has reverted to "Select namespace". So I selected my namespace again.
Second problem: The resulting URL is https://<name>.endpoints.ml-writers.cloud.goog/notebook/kubeflow-sarahmaddox/my-first-notebook/?ns=kubeflow-sarahmaddox which gives the following screen:

I was not able to reproduce this behavior on 0.7.0.

**Comment by jlewi** [comment] 2019-12-16 17:33
Closing this in favor of #3863 which accounts for the remaining work still to be done.

**Closed by jlewi** 2019-12-16 17:33 UTC
Labels: area/jupyter, kind/feature, priority/p1
