### ISSUE TITLE
Jupyter pod stuck at ContainerCreating when spawning

### ISSUE THREAD

**Issue by marcoleewow** [kubeflow/kubeflow#336] opened 2018-03-03 10:24 UTC
I followed instructions from [here](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#bringing-up-a-notebook) to bring up a notebook. 

I entered 
```
image: gcr.io/kubeflow/tensorflow-notebook-gpu:8fbc341245695e482848ac3c2034a99f7c1e5763
CPU: 1.0
memory: 2Gi
Extra Resource Limits: {"nvidia.com/gpu": "1"}
```
and clicked spawn, then the webpage get stuck at 

```
Your server is starting up.

You will be redirected automatically when it's ready for you.
```

The notebook would not spawn, and so I took a look at the pod using `kubectl describe pods jupyter-USER --namespace=kubeflow` and I found an error at the end of the event:

```
  Warning  FailedMount            59s (x2 over 3m)  kubelet, NODE  Unable to mount volumes for pod "jupyter-USER_kubeflow(71f89bcb-1ecb-11e8-911b-309c23286540)": timeout expired waiting for volumes to attach/mount for pod "kubeflow"/"jupyter-USER". list of unattached/unmounted volumes=[volume-USER]
```

What can I do to fix this volume mounting problem? I can run the `tf-cnn` job no problem so I assumed it's something to do with jupyterhub.

**Comment by jlewi** [comment] 2018-03-03 19:16
How are you running Kubernetes? Are you using minikube?

There appears to be a problem creating a default persistent volume for your Jupyter pod.

Can you run 

```
kubectl get pv
kubectl get pvc
```

/cc @inc0

**Comment by marcoleewow** [comment] 2018-03-04 06:30
I get `No resources found.` for both of the commands, seems that the Jupyter pod could not create a PV...

**Comment by jlewi** [comment] 2018-03-05 00:50
I think the problem is that Jupyter's use of persistent volumes requires a default storage class.

Can you check if you have a default storage class?

```
kubectl get storageclass
```

If you have some storage class but none is the default then you could try following the [directions](
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/) to configure a default storage class.

Alternatively as a quick workaround to see if this is in fact the problem you could try modifying the file

```
${KSONNET_APP_DIR}/vendor/kubeflow/core/jupyterhub_spawner.py 
```

And commenting out all the options in persistent volume options so your file looks like

```
# c.KubeSpawner.user_storage_pvc_ensure = True
# How much disk space do we want?
#c.KubeSpawner.user_storage_capacity = '10Gi'
#c.KubeSpawner.pvc_name_template = 'claim-{username}{servername}'
#c.KubeSpawner.volumes = [
#  {
#   'name': 'volume-{username}{servername}',
#    'persistentVolumeClaim': {
#      'claimName': 'claim-{username}{servername}'
#    }
#  }
# ]
#c.KubeSpawner.volume_mounts = [
#  {
#    'mountPath': '/home/jovyan/work',
#    'name': 'volume-{username}{servername}'
#  }
#]
```

**Comment by ogre0403** [comment] 2018-03-05 10:11
I have the same issue when I start a new notebook. 
My pv & pvc is 
```
ogre0403@MBP: ~/Desktop$ ./kubectl --kubeconfig=./config -n=kubeflow get pvc
NAME             STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-ogre       Pending                                                      <invalid>
claim-ogre0403   Pending                                                      <invalid>


ogre0403@MBP: ~/Desktop$ ./kubectl --kubeconfig=./config -n=kubeflow get pv
No resources found.
```

I look into the status of pending pvc, and have 
```
ogre0403@MBP: ~/Desktop$ ./kubectl --kubeconfig=./config -n=kubeflow describe pvc claim-ogre0403
Name:          claim-ogre0403
Namespace:     kubeflow
StorageClass:
Status:        Pending
Volume:
Labels:        app=jupyterhub
               heritage=jupyterhub
               hub.jupyter.org/username=ogre0403
Annotations:   <none>
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type    Reason         Age                              From                         Message
  ----    ------         ----                             ----                         -------
  Normal  FailedBinding  <invalid> (x182 over <invalid>)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

**Comment by inc0** [comment] 2018-03-05 18:19
@ogre0403 do you have any storageclass set up?
@jlewi we probably need to add note to our quickstart that storage is required and/or add flag to disable pvc during ksonnet install

**Comment by ogre0403** [comment] 2018-03-05 23:56
@inc0 I don't have any storageclass, I will try @jlewi method to see if it works.

**Comment by ChanYiLin** [comment] 2018-03-06 04:04
I got the same issue on my own k8s cluster which has two nodes and one master.
How about follow the method in ksonnet redis  line 151 https://github.com/ksonnet/parts/blob/master/incubator/redis/redis.libsonnet

Kubeflow can let user use local volume when there is no StorageClass and PV available.

**Comment by ogre0403** [comment] 2018-03-06 08:30
If I comment out all persistent volume options mentioned by @jlewi , jupyter pod can be created.  



Because there is no storageclass in my cluster, I create a new local storageclass manually and make it default based on [storage-class local provisioner](https://kubernetes.io/docs/concepts/storage/storage-classes/#local)

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

```
NAME              PROVISIONER                    AGE
local (default)   kubernetes.io/no-provisioner   8m
```
After clicking spawn, I found pvc is pending because there is no matched volume plugin.
Is there any recommend way to create a storage class ? 

```
root@vagrant:~/my-kubeflow# kubectl -n=kubeflow get pvc
NAME        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-abc   Pending                                       local          7m

root@vagrant:~/my-kubeflow# kubectl -n=kubeflow describe  pvc
Name:          claim-abc
Namespace:     kubeflow
StorageClass:  local
Status:        Pending
Volume:
Labels:        app=jupyterhub
               heritage=jupyterhub
               hub.jupyter.org/username=abc
Annotations:   <none>
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type     Reason              Age              From                         Message
  ----     ------              ----             ----                         -------
  Warning  ProvisioningFailed  4s (x6 over 1m)  persistentvolume-controller  no volume plugin matched
```

**Comment by jlewi** [comment] 2018-03-06 13:37
@inc0  Yes lets add options to disable the use of PV. 

@ogre0403 I don't have any recommended way of creating a storage class for your own cluster. That is likely highly dependent on how you are running K8s. For example, on GKE the default storage class is persistent disks.

**Comment by jlewi** [comment] 2018-04-04 13:34
Closing this issue because we added an option #365 to enable/disable it and changed the default to disable it #577

**Closed by jlewi** 2018-04-04 13:34 UTC
Labels: question
