### ISSUE TITLE
Deploy CLI `kfctl apply` fails due to `Network "default" requires specifying a subnetwork`.

### ISSUE THREAD

**Issue by garrettwong** [kubeflow/kubeflow#4278] opened 2019-10-11 15:45 UTC
/kind bug

**What steps did you take and what happened:**

- We have a requirement in our organization to use Shared VPC (an attached network that does not exist within the current GCP service project)
- I am following the instructions on https://www.kubeflow.org/docs/gke/deploy/deploy-cli/
- I went through the instructions and made it all the way to the `kfctl apply all -V` step.  
- The apply fails with the error message (below), inferring that the default project network is being referenced (which in my case is deleted).
- I've tried `grep -r "networks/default" ." in the directory to find all references of the `default network` and have replaced them to a Shared VPC network self link (with the full path and the partial paths)
  - https://www.googleapis.com/compute/v1/projects/${PROJECT}/global/networks/${NETWORK}
  - projects/${PROJECT}/global/networks/${NETWORK}
- I replaced the `default` network value in the 3 files that showed up:
  - gcp_config/storage.jinja
  - .cache/kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/testing/test_deploy.py
  - .cache/kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/deployment/gke/deployment_manager_configs/storage.jinja

ERRO[0027] Updating kubeflow-dir2 error: &{Code:RESOURCE_ERROR Location:/deployments/kubeflow-dir2/resources/kubeflow-dir2 Message:{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Network \"default\" requires specifying a subnetwork.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1beta1/projects/clgx-edg-dsa-poc-ed8c/locations/us-central1-a/clusters","httpMethod":"POST"}} ForceSendFields:[] NullFields:[]}  filename="gcp/gcp.go:348"
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kubeflow-dir2 error(400): BAD REQUEST
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Updating kubeflow-dir2 error(400): BAD REQUEST

**What did you expect to happen:**

- I was hoping that it would reference the Shared VPC network (not the default network) and deploy Kubeflow.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- I'm thinking there could be a requirement on permissions into the Shared VPC network, which I will also do a bit more exploration around.
- Are there other Deployment Manager scripts that we are aware of that need to be updated accordingly?
- The error messages suggests specifying a subnet, but unfortunately, I'm not seeing any documentation around this at this time.  

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): N/A... Sourcing from... https://raw.githubusercontent.com/kubeflow/kubeflow/cfb336b7/bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
- kfctl version: kfctl v0.6.2-0-g47a0e4c7
- Kubernetes platform: GKE
- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu

**Comment by jlewi** [comment] 2019-11-07 22:02
Duplicate of kubeflow/kubeflow#3082

**Comment by jlewi** [comment] 2019-11-07 22:02
See also kubeflow/kubeflow#2969

**Closed by jlewi** 2019-11-07 22:02 UTC
Labels: area/gcp, area/kfctl, kind/bug, platform/gcp, priority/p1
