### ISSUE TITLE
deploy.sh should not assume uuidgen is present

### ISSUE THREAD

**Issue by kunallimaye** [kubeflow/kubeflow#2072] opened 2018-12-11 04:26 UTC
# `deploy.sh` wrongly assumes that `uuidgen` util is present (in GCP cloud shell)

## Environment
- Kubeflow version: 0.2.2

**Comment by jlewi** [comment] 2018-12-16 22:39
Duplicate of #1415

This should be fixed in 0.3.

**Closed by jlewi** 2018-12-16 22:39 UTC
