### ISSUE TITLE
Add resource request and limit fields to tf-job ksonnet prototype

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#116] opened 2018-01-12 15:26 UTC
When jobs are run with default or incorrect resource requests they will be evicted if resources cannot be allocated when needed, e.g.

```bash
> kubectl get pods -n rl --show-all
agents-ppo-ant-feedforward-93168c9e-master-...           0/1       Evicted   0          19h
agents-ppo-ant-feedforward-93168c9e-master-...           0/1       Evicted   0          18h
agents-ppo-ant-feedforward-93168c9e-master-...           1/1       Running   0          9h
agents-ppo-ant-feedforward-93168c9e-master-...           0/1       Evicted   0          18h
agents-ppo-ant-feedforward-93168c9e-tensorboard-...   1/1       Running   0          19h
agents-ppo-ant-ee3e499e-master-aiod-0-768ls           1/1       Running   0          18h
agents-ppo-ant-ee3e499e-tensorboard-aiod-76dbf4brlz   1/1       Running   0          18h
...

> kubectl describe pod -n rl agents-ppo-ant-feedforward-93168c9e-master-3ti2-0-9st9r
...
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: memory.
...
```

Proposing to add those fields to tf-job prototype.

**Comment by jlewi** [comment] 2018-01-16 17:29
What would it look like if we didn't expose resource requirements as parameters, but instead people just overloaded the relevant values using jsonnet?

Does ksonnet provide examples of setting container requests/limits on deployments or other templates?

**Comment by cwbeitel** [comment] 2018-01-16 21:46
Yeah so I guess you could distribute the jsonnet generated by `ks generate tf-job agents_ppo_example ...`, having added something like the following,

```bash
local replicas = std.map(function(s)
  s + {
    template+: {
      spec+:  {
        containers: [
          s.template.spec.containers[0] + {
            resources: {
              limits: {
                mem: "1Gi"
              },
              requests: {
                mem: "1Gi"
              }
            },
          },
        ]
      }
    },
  },
  std.prune([workerSpec]));
```

and expect people to parameterize it with `ks param set agents_ppo_example ...`.

Is that what you had in mind? Taking inspiration from the tf-cnn prototype. Having a jsonnet file customized by developer distributed with examples/models as opposed to continually updating the core tf-job component seems like a better option.

**Comment by cwbeitel** [comment] 2018-01-16 21:50
Then of course you could specify in distributing a particular model what resources you expect it to require instead of expecting users to figure this out on their own and this could be constructed programmatically from parameters.

**Comment by jlewi** [comment] 2018-01-17 05:37
Yes. That's along the lines of what I had in mind. My theory is that we won't be able to expose all the customizable options as parameters. So at some point people will just have to take advantage of jsonnet to start setting the things they care about.

I wonder if we can make setting the resources even simpler though.

**Comment by cwbeitel** [comment] 2018-01-17 14:53
Let me know what you think of [rl-app/components/agents-ppo.jsonnet](https://github.com/cwbeitel/kubeflow-rl/blob/master/rl-app/components/agents-ppo.jsonnet) and [rl-app/components/agents-ppo.jsonnet](https://github.com/cwbeitel/kubeflow-rl/blob/master/rl-app/components/params.libsonnet).

Here's what the user's interface to that would be:

```bash
ks param set agents-ppo gcp_project kubeflow-rl
ks param set agents-ppo num_cpu 30
ks param set agents-ppo job_tag ${JOB_SALT}
ks param set agents-ppo log_dir ${LOG_DIR}
ks param set agents-ppo name ${JOB_NAME}
```

See also the [demo notebook](https://github.com/cwbeitel/kubeflow-rl/blob/master/apps/agents_ppo/demo.ipynb).

**Comment by jlewi** [comment] 2018-03-20 17:13
I think it might make sense to try to refactor our ksonnet component for TFJob to make it easier for people to override the parts they care about; e.g. the specifics for each replica type.

With v1alpha2 the replicas will be a map and not a list. So this should go a long way to making it easier for people to override parameters.

We can also rely on [late binding](http://jsonnet.org/language/design.html) in jsonnet to define structs/dicts etc... that can be conveniently overwritten and then use these structs to construct the actual spec using late binding.

For example, in the current setup we could define a map for the replicas to make it easy to override resource specs or volumes for a particular replica. And then rely on latebinding to construct a list of replicas from that map to construct the actual TFJob.

**Comment by jlewi** [comment] 2018-03-20 17:14
Leaving this open for now but I think it will largely be solved by the v1alpha2 API for TFJob.

**Comment by jlewi** [comment] 2018-04-30 00:35
Duplicate of #564 

See #564 I thing we want to move to using `ks generate` give users a complete TFJob spec that they could then easily modify. i.e. we want to use `ks generate` to mimic the experience of copying an example and then modifying it.  So I don't think we should have parameters for specifying resources.

We could have multiple prototypes. One of those prototypes could be an example of specifying requests/limits.

**Closed by jlewi** 2018-04-30 00:35 UTC
Labels: priority/p2
