### ISSUE TITLE
[Proposal] Jupyter Notebook Image Zoo

### ISSUE THREAD

**Issue by tlkh** [kubeflow/kubeflow#1643] opened 2018-09-27 04:27 UTC
Hi everyone, I'm proposing that we work out a way to create a "zoo" of Jupyter notebook images that integrate with Kubeflow/JupyterHub, similar to the collection of [official Jupyter images on Docker Hub](https://hub.docker.com/u/jupyter/). I'll be happy to take this on but I'm not very sure how the current automated build process works.

Examples of notebooks in a "zoo":

- current TF/Kaggle notebooks
- PyTorch or MXNet notebooks
- Image-processing/CV or NLP notebooks
- All-in-one notebook as default (it'll be huge, but need only be pulled once?

We could enable/encourage this two ways:

1. Separating the notebook repository from the main Kubeflow repository, and allowing branches/forks. Perhaps also a generic "`this-repository` to `that-notebook-type`" kind of repository where users can clone to use and build their own custom images that contain some code/content + have certain packages ready to go. This would be fantastic for curating labs or demos as well.
   I'm assuming this could still be integrated into our current build pipeline for notebook images!
2. Add more notebooks as components (I think this is the current approach?)

With regards to automation / build pipeline:

Currently, I'm not 100% sure how things work (if anyone could direct me, that'll be good!). To the best of my understanding:
1. Notebooks are currently under `kubeflow/components`
2. There is `tensorflow-notebook-image` and `contrib/kaggle-notebook-image`
3. There is a (cron job? Argo workflow?) somewhere ([defined here?](https://github.com/kubeflow/kubeflow/blob/master/kubeflow/automation/release.libsonnet)) that automates the build and release process
4. Images get pushed to GCR

Related issues:

- [#1132 Building the Jupyter images took over 4 hours](https://github.com/kubeflow/kubeflow/issues/1132)
- [#1574 Image Auto Release has lots of issues; should we use prow?](https://github.com/kubeflow/kubeflow/issues/1574)
- [Katib #147](https://github.com/kubeflow/katib/pull/174) seems to indicate that we are already moving towards prow?

**Comment by gaocegege** [comment] 2018-09-27 07:45
I am not sure about the build-release process, too. Maybe we could ask for help from @jlewi

**Comment by jlewi** [comment] 2018-09-27 14:13
Did you mean notebooks (ipynb)? Or runtime environments?

See: https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

I think the first step would be to understand and document the requirements for Kubeflow Jupyter images.

Ideally, any Jupyter runtime image should just work with Kubeflow. I think the only tweaks we've made are related to 

1. filesystem permissions
1. support for backing /home/jovyan is backed by PV

I suspect backing /home/joyvan with a PV is the main compatibility issue with most arbitrary Jupyter images. I think we can work around this just by having an option by not mounting the PV at /home/jovyan but instead in a subdirectory. We already have an option at the ksonnet level that configures this for all jupyter instances; but we could potentially surface it in the spawner UI to allow it to be configured on a per instance database.

/cc @pdmack

**Comment by inc0** [comment] 2018-09-27 14:37
> I suspect backing /home/joyvan with a PV is the main compatibility issue

We've used subdirectory before, but we've decided to change it to home, as people were saving things in home and losing their notebooks.

As for main question, one consideration would be maintenance of these images - it's going to be hard to provide high level of confidence for more than a few. We've run into multiple issues with version conflicts or breakages already. Building infra that will allow users to quickly navigate images and see if they're, for example, thoroughly tested by CI and CI is not failing would be possible, but lots of work.

We could create few flavors of batteries included images, like Python and R, maybe something like lightweight-python (fewer libs, not anaconda based), but I wouldn't go further than that in our community. We encourage creating new images and using them, we can list kubeflow-compatible images in doc of some sort, but I would make it clear that we don't support them.

**Comment by tlkh** [comment] 2018-09-27 16:42
> Ideally, any Jupyter runtime image should just work with Kubeflow. 

Yes, indeed this is true, but on one hand, there aren't really pre-made Jupyter runtime images for e.g. PyTorch that are maintained (not that I can find anyway). On the other hand, I'm not sure how things like integration with Kubeflow or Katib will factor in.

I understand that maintaining these images is hard! Hence I was thinking we could have a some kind of defined workflow for users to build these runtime images for themselves. We might start from making a separate repository maybe, for a standalone base/minimal Kubeflow image.

We could then curate a few "community supported" contributed images when they pop up.

**Comment by jlewi** [comment] 2018-09-27 17:11
I think you are right; we will want to have a small number of high quality, curated images and we will want to build out infra to support that.

As the link above shows we already have infra and a process for automatically building and pushing images from postsubmits. There's a lot of improvements to be made.

I think the question what are the concrete next steps.

My suggestion would be to

1. Document what requirements needed to be satisfied for an image to work with Kubeflow
1. Removing/reducing these requirements.

There's already a lot of good solutions for doing source to image workflows. So I think the biggest impact  is reducing the barriers to people being able to reuse existing Jupyter images.

**Comment by jlewi** [comment] 2019-01-04 16:48
Related: #767

**Comment by jlewi** [comment] 2019-01-04 16:54
Going to close this out in favor of #2208 

Duplicate of https://github.com/kubeflow/kubeflow/issues/2208

**Closed by jlewi** 2019-01-04 16:54 UTC
Labels: area/jupyter, priority/p2
