### ISSUE TITLE
Jupyter notebook doesn't got write permission for its home directory.

### ISSUE THREAD

**Issue by thsmfe001** [kubeflow/kubeflow#7621] opened 2024-06-28 08:47 UTC
I got error message when i tried to open notebook icon on jupyter notebook UI.
I tried to resolve this issue with many kinds of tries but i couldn't solve it.
How to deal with it?

Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/home/jovyan/.local'

**Comment by thesuperzapper** [comment] 2024-07-06 18:58
Duplicate of https://github.com/kubeflow/kubeflow/issues/7626

**Closed by thesuperzapper** 2024-07-06 18:58 UTC
