### ISSUE TITLE
[ERROR] Can not ks apply default -c kubeflow-core with ks 0.9.5

### ISSUE THREAD

**Issue by seekyiyi** [kubeflow/kubeflow#453] opened 2018-03-19 02:20 UTC
I am try to Deploy Kubeflow on my kubernetes cluster.

```
Steps
# Initialize a ksonnet APP
APP_NAME=my-kubeflow
ks init ${APP_NAME}
cd ${APP_NAME}

# Install Kubeflow components
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/master/kubeflow
ks pkg install kubeflow/core
ks pkg install kubeflow/tf-serving
ks pkg install kubeflow/tf-job

# Create templates for core components
NAMESPACE=kubeflow
kubectl create namespace ${NAMESPACE}
ks generate core kubeflow-core --name=kubeflow-core --namespace=${NAMESPACE}

# Enable collection of anonymous usage metrics
# Skip this step if you don't want to enable collection.
ks param set kubeflow-core reportUsage true
ks param set kubeflow-core usageId $(uuidgen)

# Deploy Kubeflow
ks apply default -c kubeflow-core
```
**But have environment problem** 

```
# ks apply ${KF_ENV} -c kubeflow-core
WARNING rewriting "nocloud" environment params to not use relative paths
ERROR RUNTIME ERROR: import not available kubeflow/core/all.libsonnet
	/home/ubuntu/yylin/kubeflow-test/my-kubeflow/components/kubeflow-core.jsonnet:4:13-49	thunk <all> from <$>
	/home/ubuntu/yylin/kubeflow-test/my-kubeflow/components/kubeflow-core.jsonnet:6:30-33	thunk from <thunk from <$>>
	k.libsonnet:58:22-27	thunk from <function <anonymous>>
	k.libsonnet:60:36-41	thunk from <function <anonymous>>
	<builtin>	builtin function <type>
	<std>:1165:25-26	thunk from <thunk <ta> from <function <anonymous>>>
	<builtin>	builtin function <type>
	<std>:1167:29-31	thunk from <function <anonymous>>
	<builtin>	builtin function <primitiveEquals>
	<std>:1167:8-36	function <anonymous>
	...
	<builtin>	builtin function <type>
	<std>:1217:8-9	function <anonymous>
	<std>:1165:25-26	thunk from <thunk <ta> from <function <anonymous>>>
	<builtin>	builtin function <type>
	<std>:1167:29-31	thunk from <function <anonymous>>
	<builtin>	builtin function <primitiveEquals>
	<std>:1167:8-36	function <anonymous>
		
	/home/ubuntu/yylin/kubeflow-test/my-kubeflow/components/kubeflow-core.jsonnet:6:1-53	$
	During evaluation

```
**Define :**
$ ks env add nocloud
$ KF_ENV=nocloud

Run 

``ks apply ${KF_ENV} -c kubeflow-core``

**Comment by jlewi** [comment] 2018-03-19 12:49
Which version of ksonnet are you using?

**Comment by jlewi** [comment] 2018-03-20 02:59
I was not able to reproduce this using ksonnet 0.8.

Can you please run 

```
ls -laR vendor/
```

**Comment by kairen** [comment] 2018-03-20 03:03
@seekyiyi I have the same problem using v0.9.1(or dev build) version of ksonnet, but I use v0.8.0 can be solved.

**Comment by pdmack** [comment] 2018-03-20 12:54
I _cannot_ reproduce this with:
```
# ks version
ksonnet version: 0.9.1
jsonnet version: v0.9.5
client-go version: 1.8
```

**Comment by seekyiyi** [comment] 2018-03-20 15:19
Former

```
ks version
jsonnet version: v0.9.5
client-go version: 1.8
```
Thanks, @kairen 
I try to use  v0.8.0 was solved.

**Comment by jlewi** [comment] 2018-03-26 13:54
Closing this issue since the workaround appears to be to use a different version.

**Closed by jlewi** 2018-03-26 13:54 UTC
Labels: priority/p2
