### ISSUE TITLE
[Discussion] Refactor the Registry?

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#306] opened 2018-02-27 18:24 UTC
Insipred by this work (https://github.com/kubeflow/kubeflow/pull/304), we're starting to get multiple components per "ML Stage", I wonder if it makes sense to refactor the registry to more clearly indicate what each component's top level mission is. 

E.g.
Instead of:
ks pkg install kubeflow/tf-serving
ks pkg install kubeflow/seldon

It is:
ks pkg install kubeflow/serve/tf-serving
ks pkg install kubeflow/serve/seldon

I think, top level, there are probably at least 4 major categories:
/data (ingesting, transformation, splitting, etc)
/build (visualization, splitting, etc)
/train (model frameworks)
/serve (including monitoring and events)

I'm not sure if we need the granularity of all the stages of the TFX paper (http://delivery.acm.org/10.1145/3100000/3098021/p1387-baylor.pdf?ip=104.132.154.92&id=3098021&acc=OPENTOC&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E054E54E275136550&__acm__=1519756069_3bb944ca1ca1abdf6f2f6354c24fd2d1), but maybe this is a start?

cc @jlewi @cliveseldon

**Comment by jlewi** [comment] 2018-02-27 20:52
duplicate of #106

**Closed** 2018-02-27 20:53 UTC
