### ISSUE TITLE
ERROR Server is unable to handle tensorflow.org/v1alpha1, Kind=TFJob

### ISSUE THREAD

**Issue by bbarnes52** [kubeflow/kubeflow#200] opened 2018-02-02 18:32 UTC
More information:

kubectl get pods --namespace=${NAMESPACE}
NAME                                READY     STATUS    RESTARTS   AGE
ambassador-1695609295-7d7ml         2/2       Running   0          23m
ambassador-1695609295-dblhh         2/2       Running   0          23m
ambassador-1695609295-m0bzw         2/2       Running   0          23m
tf-hub-0                            1/1       Running   0          23m
tf-job-dashboard-4279538329-vsxl8   1/1       Running   0          23m
tf-job-operator-4193103-6t0rl       1/1       Running   0          23m

kubectl get crd
NAME                    AGE
tfjobs.tensorflow.org   27m

kubectl get deployment tf-job-operator
Error from server (NotFound): deployments.extensions "tf-job-operator" not found

I believe I followed the user guide exactly, any idea why the tf-job-operator is not deployed correctly?

**Comment by jlewi** [comment] 2018-02-02 18:58
Your probably not looking at the right namespace.

Try

```
kubectl get -n ${NAMESPACE} deployment tf-job-operator
```

**Comment by bbarnes52** [comment] 2018-02-02 19:00
Right you are. My apologies - new to k8s.

kubectl get -n ${NAMESPACE} deployment tf-job-operator
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
tf-job-operator   1         1         1            1           6m

Any idea what causes the error (ERROR Server is unable to handle tensorflow.org/v1alpha1, Kind=TFJob)?

**Comment by bbarnes52** [comment] 2018-02-02 19:25
kubectl get crd -o yaml

apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp: 2018-02-02T18:53:31Z
    name: tfjobs.tensorflow.org
    namespace: ""
    resourceVersion: "872"
    selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/tfjobs.tensorflow.org
    uid: 5d3072f6-084a-11e8-bcad-42010a800331
  spec:
    group: tensorflow.org
    names:
      kind: TfJob
      listKind: TfJobList
      plural: tfjobs
      singular: tfjob
    scope: Namespaced
    version: v1alpha1
  status:
    acceptedNames:
      kind: TfJob
      listKind: TfJobList
      plural: tfjobs
      singular: tfjob
    conditions:
    - lastTransitionTime: null
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: 2018-02-02T18:53:31Z
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

Looks like it might be duplicate of https://github.com/tensorflow/k8s/issues/174. But concretely, what do I have to change to resolve this issue?

**Comment by bbarnes52** [comment] 2018-02-02 22:14
Fwiw if I just do something like kubectl create -f job.yaml the job runs successfully.

**Comment by gaocegege** [comment] 2018-02-03 01:32
Hi, @bbarnes52 Could you post your log of the operator:

```
kubectl logs deploy/tf-job-operator -n ${NAMESPACE}

**Comment by bbarnes52** [comment] 2018-02-03 01:57
Attached, it's quite large (10k lines of text)

I used kubectl create -f job.yaml, where job.yaml had "kind" TfJob (as opposed to TFJob). This resulted in a successful job.

Was unable to submit a successful job using ksonnet.

[out.txt](https://github.com/kubeflow/kubeflow/files/1691302/out.txt)

**Comment by gaocegege** [comment] 2018-02-03 02:09
@bbarnes52 

Hi, I think it is caused by the wrong kind in CRD: TfJob, now the name of the custom resource is TFJob, but I am not sure why the operator works well with the wrong CRD, do we have an unchanged image `04425d9-dirty-e3b0c44` in the ksonnet? @jlewi

**Comment by jlewi** [comment] 2018-02-04 19:29
I don't believe the ksonnet config has been updated.

We also don't have an E2E test that verifies we can deploy and submit a TFJob. I think things are out of sync because we updated the ksonnet configs to add the CRD creation and used the new name TFJob but didn't update the corresponding TFJob docker image.

**Comment by elsonrodriguez** [comment] 2018-02-06 18:10
@bbarnes52 This should be fixed now, care to give it another shot?

**Comment by jlewi** [comment] 2018-02-07 13:56
I've tested the fix and thinks appear to be working. @bbarnes52 If you are still having problems please reopen the issue.

**Closed by jlewi** 2018-02-07 13:56 UTC
