### ISSUE TITLE
0.6.1 binary cannot execute

### ISSUE THREAD

**Issue by arun-gupta** [kubeflow/kubeflow#3768] opened 2019-07-26 23:01 UTC
Download kfctl binary from https://github.com/kubeflow/kubeflow/releases/download/v0.6.1-rc.1/kfctl_v0.6.1-rc.1-1-gc8a1da0d_darwin.tar.gz

Tried running and getting:

```
-bash: ./kfctl: cannot execute binary file
```

Seems to work fine for 0.6.0

**Comment by zhenghuiwang** [comment] 2019-07-26 23:10
Thanks for filing it.

Duplicate of https://github.com/kubeflow/kubeflow/issues/3755

/close

**Closed by zhenghuiwang** 2019-07-26 23:10 UTC
Labels: kind/bug

**Comment by wronk** [comment] 2019-09-26 17:55
If it helps anyone in the future, I ran into this issue because I downloaded the tarball for the wrong platform -- make sure you select `linux` or `darwin` properly from [the releases page](https://github.com/kubeflow/kubeflow/releases).
