### ISSUE TITLE
Automated sync of Kubeflow between GCR and DockerHub

### ISSUE THREAD

**Issue by TheJaySmith** [kubeflow/kubeflow#1320] opened 2018-08-06 18:17 UTC
We have a rising popularity in China with Kubeflow however they are unable to access GCR. We also have other users who may prefer using DockerHub over GCR for images as it works better for their workflow. We need to sync Kubeflow Dockerfiles between GCR and DockerHub

**Comment by TheJaySmith** [comment] 2018-08-06 18:19
Created kubeflowrobot account

**Comment by swiftdiaries** [comment] 2018-08-06 20:15
For reference / background: https://github.com/kubeflow/kubeflow/issues/211.

**Comment by jlewi** [comment] 2018-08-24 13:59
Here's Jay's code
https://github.com/TheJaySmith/kubeflowpush/blob/master/push.py

1. Its using docker. which will make this a pain to run on K8s.
1. It looks like it uses a hand written list of images to sync

Jay I suggest putting relevant code here:
https://github.com/kubeflow/kubeflow/tree/master/releasing

Jay I don't think we need to use docker. We can

1. Shell out to gcloud to get a list of images in our GCR registry

   * https://github.com/kubeflow/kubeflow/blob/master/releasing/add_image_shas.py#L43

1. We can use GCB to push from GCR to DockerHub

The GCB workflow could look like this:
https://github.com/jlewi/kubeflow-dev/blob/master/kaggle-image/retag_image.yaml

**Comment by TheJaySmith** [comment] 2018-08-24 17:56
Let me play with it this weekend to use gCloud and I will upload it to the https://github.com/kubeflow/kubeflow/tree/master/releasing location. Will update you before Monday

**Comment by jlewi** [comment] 2018-09-17 17:35
@TheJaySmith Any update/progress on this?

**Comment by TheJaySmith** [comment] 2018-09-18 02:12
#1548

**Comment by jlewi** [comment] 2018-09-25 14:13
Thanks.

Should we mark this issue as a Duplicate of #211 (Publish Docker Images to DockerHub)?

**Comment by jlewi** [comment] 2018-10-14 21:38
Duplicate of #211

**Closed by jlewi** 2018-10-14 21:38 UTC
