### ISSUE TITLE
[0.6.1] Kubeflow UI Error

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/kubeflow#3784] opened 2019-07-30 23:44 UTC
0.6.1 kubeflow UI cannot visit juypter Page with "Sorry, /jupyter/ is not a valid page"
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/10126721/62172993-ec0fb800-b366-11e9-92bb-8e88569dacdf.png">

Pipeline page cannot work well, too
<img width="892" alt="image" src="https://user-images.githubusercontent.com/10126721/62172974-d3070700-b366-11e9-90fe-0c01c201e9c4.png">

**Comment by prodonjs** [comment] 2019-07-31 13:15
It seems like their may be some kind of routing issues. Can you try navigating to the following URLs which bypass the Kubeflow navigation menu?

/pipelines/
/jupyter/
/katib/
/metadata/

Each of those should resolve to the UI for those applications without the top navigation bar. If those work as intended, it will help us isolate the issue.

/cc @prodonjs 
/cc @avdaredevil 
/area centraldashboard
/area frontend

**Comment by jlewi** [comment] 2019-08-12 03:43
How are you connecting to Kubeflow? 

Services are routed through the ISTIO gateway. You need to connect to the gateway

**Comment by elviraux** [comment] 2019-09-09 21:47
Hi, closing a duplicate of https://github.com/kubeflow/kubeflow/issues/3784

**Closed by elviraux** 2019-09-09 21:47 UTC
Labels: area/centraldashboard, area/front-end, area/jupyter, kind/bug, priority/p0
