### ISSUE TITLE
Error: "Sorry, /jupyter/ is not a valid page"

### ISSUE THREAD

**Issue by Eric-Zhang1990** [kubeflow/kubeflow#3615] opened 2019-07-08 11:50 UTC
Anyone can give any solutions for the problem "Sorry, /jupyter/ is not a valid page" ?
Thanks in advance.

**Comment by kimwnasptd** [comment] 2019-07-08 13:06
hi @Eric-Zhang1990 , could you provide some more info regarding your Kubeflow installation?  How did you deploy kubeflow?

**Comment by jlewi** [comment] 2019-07-08 17:55
Based on #3414  It looks like the URLs should be /notebook.
Are you using an old version of Kubeflow?
Where are you seeing this error? i.e. how would we reproduce it?

**Comment by sushkov-r** [comment] 2019-08-09 16:47
Having the same issue. None of the links in the menu bar work for me.
I am accessing the UI by port-forwarding svc/centraldashboard: `kubectl port-forward svc/centraldashboard -n kubeflow 8888:80`. Perhaps I am missing some step here?
----
kfctl version: 0.6.1 [go version]
Cluster: AWS EKS automatically created by kfctl
kfctl config derived from this: [config](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_aws_cognito.yaml)

**Comment by nicklhy** [comment] 2019-09-03 03:37
Same problem here.
kfctl version: 0.6.2
kubeflow is deployed with https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.2/bootstrap/config/kfctl_k8s_istio.yaml

**Comment by elviraux** [comment] 2019-09-09 23:27
Closing, duplicate of https://github.com/kubeflow/kubeflow/issues/3615

**Closed by elviraux** 2019-09-09 23:27 UTC
Labels: area/centraldashboard, duplicate, kind/bug, priority/p1

**Comment by sheep94lion** [comment] 2020-05-26 05:56
I met the same problem.
It seems you should not use kubectl port-forward to access the Kubeflow UI.
Follow the instructions instead. For my case its: 
https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/
You should access the UI through the IngressGateway.

Use kubectl -n istio-system describe svc istio-ingressgateway to find the right address and port.
"http2" is the right port number.
