### ISSUE TITLE
Cannot deploy Kubeflow on GCP: tells me to enable APIs that are already enabled

### ISSUE THREAD

**Issue by BioGeek** [kubeflow/kubeflow#4919] opened 2020-04-06 13:05 UTC
/kind question

**Question:**
I am trying to install Kubeflow on Google Cloud Platform (GCP) and Kubernetes Engine (GKE), following the [GCP deployment guide][1].

I created a GCP project of which I am the owner, I enabled billing, set up OAuth credentials and enabled the following APIs:

 - Compute Engine API
 - Kubernetes Engine API
 - Identity and Access Management (IAM) API
 - Deployment Manager API
 - Cloud Resource Manager API
 - Cloud Filestore API
 - AI Platform Training & Prediction API

However, when I want to [deploy Kubeflow using the UI][2], I get the following error:

[![enter image description here][3]][3]

So I doublechecked and those APIs are already enabled:

[![enter image description here][4]][4]

[![enter image description here][5]][5]

The log messages at the bottom of the screen are:

    2020-03-0614:14:04.629: Getting enabled services for project <projectname>..
    2020-03-0614:14:16.909: Could not configure communication with GCP, exiting

The [`Could not configure communication with GCP, exiting`][6] is triggered when [`_enableGcpServices()`][7] fails. 

The line [`Getting enabled services for project ...`][8] is printed but not the line [`Proceeding with project number: ...`][9], so the error must be triggered somewhere in [the block of code between those lines][10]. 

The call to [`Gapi.cloudresourcemanager.getProjectNumber(project)`](https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L928-L929) has its own try/catch with a slightly different error message and title (only talks about the cloud resource manager API, not the IAM API), so I assume it is the call to [`Gapi.getSignedInEmail()`][11] that fails??

  [1]: https://www.kubeflow.org/docs/gke/deploy/
  [2]: https://www.kubeflow.org/docs/gke/deploy/deploy-ui/
  [3]: https://i.stack.imgur.com/SrSjY.png
  [4]: https://i.stack.imgur.com/MSdhr.png
  [5]: https://i.stack.imgur.com/Fu0Au.png
  [6]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L695
  [7]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L916
  [8]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L922
  [9]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L944
  [10]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L923-L942
  [11]: https://github.com/kubeflow/kubeflow/blob/master/components/gcp-click-to-deploy/src/DeployForm.tsx#L923

Anyway, I want to deploy Kubeflow on GCP, what am I doing wrong?

Also crossposted at [stackoverflow](https://stackoverflow.com/q/61057213/50065).

**Comment by jlewi** [comment] 2020-04-06 14:15
Duplicate of #4670

**Comment by jlewi** [comment] 2020-04-06 14:16
@BioGeek as a work around can you try using the CLI?

**Closed by jlewi** 2020-04-06 14:15 UTC
Labels: kind/question

**Comment by BioGeek** [comment] 2020-04-06 17:45
@jlewi I can confirm that installing Kubeflow via the CLI works!

The only warning I saw during the deployment was `failed calling webhook "webhook.cert-manager.io"`, but after retying five times it finally got through and the installation finnished.

```
namespace/cert-manager unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
serviceaccount/cert-manager unchanged
serviceaccount/cert-manager-cainjector unchanged
serviceaccount/cert-manager-webhook unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-edit unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-view unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator configured
configmap/cert-manager-parameters unchanged
service/cert-manager unchanged
service/cert-manager-webhook unchanged
deployment.apps/cert-manager unchanged
deployment.apps/cert-manager-cainjector configured
deployment.apps/cert-manager-webhook configured
apiservice.apiregistration.k8s.io/v1beta1.webhook.cert-manager.io unchanged
application.app.k8s.io/cert-manager configured
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
WARN[0301] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout650060554": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
WARN[0301] Will retry in 12 seconds.                     filename="kustomize/kustomize.go:203"

```

**Comment by BioGeek** [comment] 2020-04-06 18:02
Upon closer reading the linked issue #4670 I think I realized what I did wrong in the UI: I used the project name instead of the project ID.  So better error handling in `DeployForm.tsx` would probably prevent this issue.
