### ISSUE TITLE
Protect InferenceService with Google IAP

### ISSUE THREAD

**Issue by livneros** [kubeflow/kubeflow#4946] opened 2020-04-12 11:24 UTC
Hey. 
We are trying to enable access for our InferenceService only with an IAP authentication.
Currently, the access is open through the load balancer's public IP. 
Is there any solution for that? maybe similar to the [tfserving solution](https://www.kubeflow.org/docs/components/serving/tfserving_new/#sending-prediction-request-through-ingress-and-iap)
Thanks.

**Comment by Jeffwan** [comment] 2020-04-12 21:09
Check this close https://github.com/kubeflow/kfserving/issues/760

**Comment by jlewi** [comment] 2020-04-19 23:59
Duplicate of kubeflow/kfserving#760

**Closed by jlewi** 2020-04-19 23:59 UTC
Labels: kind/bug, platform/gcp, priority/p1
