### ISSUE TITLE
Local port forward does not work when KF deployed with 1-click app 

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#2883] opened 2019-04-01 07:10 UTC
Repro:
  Deployed a cluster with https://deploy-staging.kubeflow.cloud/#/deploy?version=v0.5.0-rc.1
  Followed the link to Cloud Shell (it brings to the GKE Service UI, not to cloud shell)
  Clicked on port forwarding, copied the CLI command to port forward
  Ran the command locally
  Port forwarding started
  Open the localhost:8080 
  
Result:
  Got an SSL error

Expected:
  KF UI to open

**Comment by jlewi** [comment] 2019-04-01 12:42
Duplicate of #2884

**Closed by jlewi** 2019-04-01 12:42 UTC
