### ISSUE TITLE
issues upgrading 0.5.0 to 0.6.0/0.6.1

### ISSUE THREAD

**Issue by mmuppidi** [kubeflow/kubeflow#3890] opened 2019-08-13 19:34 UTC
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Upgrading Kubeflow from 0.5.0 to 0.6.1 and the following error occurred.

I deployed kubeflow using the UI following the [documentation](https://www.kubeflow.org/docs/gke/deploy/deploy-ui/). The I used the following script to update the Kubeflow deployment

```
#!/bin/bash

set -e 

PWD="$(pwd)"

export KUBEFLOW_VERSION=v0.6.1
export KFAPP=$PWD/kubeflow-dev/v0.5.0/kubeflow-red
export KUBEFLOW_SRC=$PWD/kubeflow
export ZONE=us-central1-a

export KUBEFLOW_TAG=0.6.1
KFCTL_DIR="$PWD/${KUBEFLOW_TAG}"
mkdir -p $KFCTL_DIR
wget -P $KFCTL_DIR https://github.com/kubeflow/kubeflow/releases/download/v${KUBEFLOW_TAG}/kfctl_v${KUBEFLOW_TAG}_darwin.tar.gz
tar -xvf $KFCTL_DIR/kfctl_v${KUBEFLOW_TAG}_darwin.tar.gz -C $KFCTL_DIR

export PATH=$KFCTL_DIR:$PATH


kfctl init ${KFAPP} --version=${KUBEFLOW_VERSION} --package-manager=kustomize@${KUBEFLOW_VERSION}
pushd ${KFAPP}
    kfctl generate all -V --zone ${ZONE}
    kfctl apply -V all
popd

```

```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocated
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for apply
  -V, --verbose   verbose output default is false

couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from istio-install Error: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocated
```

**Environment:**

- Kubeflow version: 0.5.0 (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: 0.6.1 (use `kfctl version`):
- Kubernetes platform: GKE (e.g. `minikube`)
- Kubernetes version: 1.11.10-gke.5 (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment] 2019-08-14 17:06
Upgrades are currently not officially supported. We hope to add upgrade support starting with 0.7
(see [ROADMAP](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md))

The particular problem with apply not working on second run is #3810

Duplicate of #3810

**Comment by jlewi** [comment] 2019-08-14 17:06
Duplicate of #3810

**Closed by jlewi** 2019-08-14 17:06 UTC
Labels: kind/bug
