### ISSUE TITLE
make build-kfctl-container errors with cannot find module providing package

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kubeflow#3883] opened 2019-08-13 13:02 UTC
[Latest master ](https://github.com/kubeflow/kubeflow/commit/7c0932a117f2f2dc232271992d0348c4747021eb)doesn't build when running `make build-kfctl-container` from the bootstrap dir. I get:

```
#19 23.73 go: extracting github.com/kubeflow/kubeflow v0.6.1
#19 24.99 build github.com/kubeflow/kubeflow/bootstrap/v3/cmd/kfctlClient: cannot load github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app: cannot find module providing package github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app
#19 25.00 make: *** [Makefile:61: fmt] Error 1
------
executor failed running [/bin/sh -c make build-kfctl]: exit code: 2
make[1]: *** [Makefile:115: build-kfctl-container] Error 
```

This was working for me a month or so ago.

**Comment by yanniszark** [comment] 2019-08-13 13:20
cc @jlewi @gabrielwen seems related to the new kfctlClient code.

**Comment by jlewi** [comment] 2019-08-13 16:34
Can you try running

```
make clean
make build
```
I think dependencies might be cached somewhere.

Are you doing this on master or v0.6-branch?

Can you also check if postsubmits and periodic runs on master are passing? That would help us determine whether its just you or broken for everybody.

**Comment by jlewi** [comment] 2019-08-13 18:54
I can reproduce on master.

```
build github.com/kubeflow/kubeflow/bootstrap/v3/cmd/kfctlClient: cannot load github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app: cannot find module providing package github.com/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app
make: *** [Makefile:61: fmt] Error 1
```

Test grid isn't showing any results (see kubeflow/testing#438)

Here are some postsubmit jobs though
https://prow.k8s.io/?repo=kubeflow%2Fkubeflow&type=postsubmit

**Comment by jlewi** [comment] 2019-08-13 18:55
Post submit shows the same failure
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1161075475825561601/

**Comment by jlewi** [comment] 2019-08-13 18:57
My conjecture is the problem is

#3786 which changed imports to v3 and #3830

My guess is this wasn't caught in presubmits because #3830 was based on master prior to #3786 being merged.

**Comment by jlewi** [comment] 2019-08-13 18:58
Rollback for #3830 coming

**Closed** 2019-08-16 00:06 UTC
Labels: kind/bug
