### ISSUE TITLE
Why use SHA256 digest for images instead of tags? Can we find out what version of the code is running?

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4654] opened 2020-01-15 17:44 UTC
/kind question

**Question:**

We have noticed that Kubeflow has moved towards using images digest (sha256) instead of tags.
While this is certainly more secure it creates the following issues:

* The only way to get more info about an image's version is for the image to bake that version inside. If it doesn't do that then tracking down what version of the code is used is impossible. For example, in current KF 0.7-branch, we see that the notebook-controller and kfam images use a digest. Is it possible to track what git version they came from?
* It is not apparent what version of a software is installed, where with tag a simple kubectl command would yield comprehensive information of what version is installed.

My question is:

* Is it possible to find out what version (git) of the code is running when using image digests, for images like notebook-controller, kfam and others that don't bake the version in their image?

/cc @jlewi

**Comment by jlewi** [comment] 2020-01-16 07:27
Duplicate of kubeflow/testing#558

**Closed** 2020-01-16 07:27 UTC
Labels: area/engprod, kind/question, priority/p2
