### ISSUE TITLE
Create end-to-end tests for Notebook Manager UI for releases

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4087] opened 2019-09-06 17:06 UTC
/kind feature

**Why you need this feature:**
We need end-to-end tests for Notebook Manager UI to ensure releases are stable. This is an application criteria for Kubeflow 1.0.

**Describe the solution you'd like:**
We should inventory existing tests for the Notebooks manager UI and create any missing test flows.

**Comment by krishnadurai** [comment] 2019-09-10 06:57
Thanks @abhi-g for creating this issue. A couple of questions here for the tests:
1) Which auth provider are we planning to include for the test?
2) Will this test go on to cover multi-user scenarios?

**Comment by jlewi** [comment] 2020-01-06 17:46
Bump to P0 because this is a requirement for 1.0

**Comment by jlewi** [comment] 2020-01-06 17:48
Duplicate of #3657

**Closed by jlewi** 2020-01-06 17:48 UTC
Labels: area/1.0.0, effort/2-weeks, kind/feature, lifecycle/frozen, priority/p0
