### ISSUE TITLE
Error when adding notebook server: "500: There was an error trying to connect to the backend API."

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#3872] opened 2019-08-12 19:00 UTC
/kind bug

**What steps did you take and what happened:**

When I go to the Notebook servers section and click "+ New server" I get the following error at the bottom pf the page:

```
500: There was an error trying to connect to the backend API. Http failure response for https://zzz.endpoints.yyy.cloud.goog/jupyter/api/namespaces/kubeflow-xxx/poddefaults: 500 OK
```

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): "build version v1beta1" (Sounds like 0.6+)

**Comment by kimwnasptd** [comment] 2019-08-12 19:22
Could be duplicate of #3770 ?

@Ark-kun do you have a PodDefault that doesn't have a `desc` field in that namespace? If that's the case then you could either set that field in the PodDefault or use the tag `9419d4d` for the jupyter-web-app.

**Comment by jlewi** [comment] 2019-09-10 13:29
Duplicate of 3770

**Closed by jlewi** 2019-09-10 13:29 UTC
Labels: area/jupyter, kind/bug, priority/p0
