### ISSUE TITLE
 KubeFlow 0.7.0 availability and Kubernetes version

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/kubeflow#4423] opened 2019-10-29 09:08 UTC
can you please update this issue when KubeFlow 0.7.0 is available

Also much appreciate it if you could also advise the Kubernetes version on which KubeFlow 0.7.0 is tested

Follow up to https://github.com/kubeflow/kubeflow/issues/4228
since https://github.com/kubeflow/kubeflow/issues/4228 is closed

**Comment by jlewi** [comment] 2019-10-31 12:00
Kubeflow is tested on 1.14.
This information is now on our docs.
https://www.kubeflow.org/docs/started/k8s/overview/#minimum-system-requirements

#4249 is the tracking bug for 0.7.0

Duplicate of #4249

**Closed by jlewi** 2019-10-31 12:00 UTC
Labels: kind/feature

**Comment by cyrilthank** [comment] 2019-11-01 06:35
Thanks a lot @jlewi for  patiently sharing this information

**Comment by cyrilthank** [comment] 2019-11-04 05:26
Is kubeflow 0.7.0 released?..can you please share how i may subscribe to this information/update?

**Comment by jlewi** [comment] 2019-11-04 20:00
See kubeflow/kubeflow#4249

**Comment by geoantony9** [comment] 2019-12-30 06:57
Hey, @cyrilthank I also faced the same issue while I upgraded to 0.7 of the kubeflow version and 1.17 of Kubernetes version. I have patched the issue and the files regarding the same is put in my repo [https://github.com/geoantony9/kubeflow_patch_seldon] . This fix created worked for me. The issue was with the CRD file of seldonCore. Please do try this patch and let me know the result.
