### ISSUE TITLE
Jupyter notebook fail to start if no PVC is bounded 

### ISSUE THREAD

**Issue by Luke035** [kubeflow/kubeflow#4520] opened 2019-11-22 08:35 UTC
/kind bug

**What steps did you take and what happened:**
If we choose to create a jupyter notebook with no persistent volume attached to the home dir (container image tensorflow 1.14 only cpu), the resulting POD will fail with the following error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1628, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1319, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local' 
```

**What did you expect to happen:**
POD is started correctly

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 0.7
- kfctl version: (use `kfctl version`): 0.7
- Kubernetes platform: (e.g. `minikube`) EKS
- Kubernetes version: (use `kubectl version`): 1.14.7
- OS (e.g. from `/etc/os-release`): Amazon Linux (CENTOS)

**Comment by wjddyd66** [comment] 2019-11-25 08:38
@Luke035 

I have Same Issue....

I rewrite some Dockerfile & start.sh and Run

But Same Issue
```code
root@jyhwang-XPS-15-9570:/home/jyhwang# kubectl logs -n admin custom-jupyter2-0
Error from server (BadRequest): a container name must be specified for pod custom-jupyter2-0, choose one of: [custom-jupyter2 istio-proxy] or one of the init containers: [istio-init]
root@jyhwang-XPS-15-9570:/home/jyhwang# kubectl logs -n admin custom-jupyter2-0 custom-jupyter2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.5/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1717, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1372, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jyhwang/.local'

```
<br>

Do ypu reslove It?

In my Environment
PV and PVC auto created so I can't change pv, pvc....
(container image tensorflow 1.6.0 and gpu)

**Comment by fediazgon** [comment] 2019-11-25 09:58
I will take a look at it

**Comment by fediazgon** [comment] 2019-11-27 20:10
Ok, I am not completely sure about this. When you create a nb-server with a "Workspace Volume", the spawned pod uses a PVC to claim a volume that will be mounted in [/home/jovyan](https://github.com/kubeflow/kubeflow/blob/6f790f8f3b43d8048d9fbeff7e64857da264f83b/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml). When the claim is fulfilled the mount directory acquires the ownership of the `whoami` user in the pod's container: [jovyan](https://github.com/kubeflow/kubeflow/blob/b813c9afaf2b053928935ba8ab8665a261591517/components/tensorflow-notebook-image/Dockerfile#L115). So, when launching `jupyter notebook` the user is allowed to write in '/home/jovyan/.local'.

However, when no volume is claimed, '/home/jovyan' inherits permissions from root:root:

```
tf-docker /tf > whoami
jovyan
tf-docker /tf > ls -lah /home/
total 12K
drwxr-xr-x 1 root root 4.0K Sep 28 06:23 .
drwxr-xr-x 1 root root 4.0K Nov 27 18:50 ..
drwxr-xr-x 1 root root 4.0K Sep 28 06:24 jovyan
tf-docker /tf > 
```

One way to solve it would be to `RUN chown -R ${NB_USER}:users $HOME` before configuring container startup in the tf-image, as it is done in the [rapidai Dockerfile](https://github.com/kubeflow/kubeflow/blob/69fb4ec5909151a3089cb2ee6c2ab269c29f8636/components/contrib/rapidsai-notebook-image/Dockerfile#L56)

**Comment by vaskokj** [comment] 2020-02-04 13:33
There is an option in the UI to not have a persistent storage for the notebook. This error happens when you select that option.

**Comment by jlewi** [comment] 2020-04-12 23:45
Duplicate of #4863

**Closed by jlewi** 2020-04-12 23:45 UTC
Labels: area/jupyter, kind/bug, priority/p2
