### ISSUE TITLE
Notebook UI accepts invalid characters

### ISSUE THREAD

**Issue by DanSanche** [kubeflow/kubeflow#3970] opened 2019-08-21 22:24 UTC
/kind bug

**What steps did you take and what happened:**
I tried to create a notebook called "1.13.1". The site accepted the name, and started the creation UI. After a few minutes of watching a spinning circle, I checked the kubectl logs, and saw "Invalid value: "1.13.1-0": a DNS-1123 label must consist of lower case alphanumeric characters or '-'"

**What did you expect to happen:**
The UI should reject any wrong names. 

It should possibly also show a failure state instead of a progress wheel when creation fails

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: kfctl v0.6.2-rc.1
- Kubernetes platform: GKE
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:37:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.13", GitCommit:"af4778c16fedc428827fa1949c97cf325f4b9f9b", GitTreeState:"clean", BuildDate:"2019-07-26T03:07:52Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- OS: macOS

**Comment by jlewi** [comment] 2019-09-09 13:50
Duplicate of #4003

**Closed by jlewi** 2019-09-09 13:50 UTC
Labels: kind/bug
