### ISSUE TITLE
Fail on the step of Installation of Kubeflow

### ISSUE THREAD

**Issue by chiehpower** [kubeflow/kubeflow#5368] opened 2020-10-29 03:22 UTC
Hi all,

I got stuck in the beginning of installing Kubeflow where I followed the instruction from [official webpage](https://www.kubeflow.org/docs/started/workstation/minikube-linux/). 
I chose the `minikube` tool to install kubeflow. 

I have installed the tools of docker, kubectl, kfctl, and Minikube.
However, I got stuck on [the third step of installing kubeflow](https://www.kubeflow.org/docs/started/workstation/minikube-linux/#installation-of-kubeflow).
I followed the steps except `start minikube` part. I didn't use this command:
```
minikube start --cpus 6 --memory 12288 --disk-size=120g --extra-config=apiserver.service-account-issuer=api --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/apiserver.key --extra-config=apiserver.service-account-api-audiences=api
``` 
I was using `minikube start` only.

Here are my steps.
```
minukube ›› export BASE_DIR=/home/chieh/472GB/minukube                                                    
minukube ›› export KF_NAME=kubeflow-base                                       
minukube ›› export KF_DIR=${BASE_DIR}/${KF_NAME}
minukube ›› export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml" 
minukube ›› mkdir -p ${KF_DIR}                                                                                                               
minukube ›› cd ${KF_DIR}                                                                                                                     
kubeflow-base ›› ls                                                                                                                          
kubeflow-base ›› kfctl apply -V -f ${CONFIG_URI}     
```
The tail of error messages are below:
```
persistentvolumeclaim/katib-mysql unchanged
persistentvolumeclaim/metadata-mysql unchanged
persistentvolumeclaim/minio-pvc unchanged
persistentvolumeclaim/mysql-pv-claim unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/seldon-validating-webhook-configuration-kubeflow configured
WARN[0008] Encountered error applying application kubeflow-apps:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout145256962": CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]  filename="kustomize/kustomize.go:266"
WARN[0008] Will retry in 4 seconds.                      filename="kustomize/kustomize.go:267"
```

I attached my whole log.txt file. 
[whole_log.txt](https://github.com/kubeflow/kubeflow/files/5455918/whole_log.txt)

What I expect is that I hope to do a simple process of running the MNIST on-prem Jupyter notebook.

Thank you so much!!

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): cannot install ...
- kfctl version: (use `kfctl version`): v1.1.0
- Kubernetes platform: (e.g. `minikube`) : minikube
- Kubernetes version: (use `kubectl version`): v1.19.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS

**Comment by DavidSpek** [comment] 2021-03-20 16:10
I believe this issue was caused by an incompatibility of the Seldon manifests and Kubernetes 1.19+, which has since been fixed in newer manifests or Seldon version. Therefore I am closing this issue.
/close

**Closed by DavidSpek** 2021-03-20 16:10 UTC
Labels: area/kfctl, kind/bug, priority/p2
