### ISSUE TITLE
Endpoint not created when reinstalling kubeflow

### ISSUE THREAD

**Issue by devashishshankar** [kubeflow/kubeflow#5117] opened 2020-07-08 13:17 UTC
/kind bug

**What steps did you take and what happened:**

I had installed Kubeflow using the CLI on GKE. First installation generally works out well. However, I had some configuration changes - due to which I did `kfctl delete` followed by `kfctl apply` again. I have tried this multiple times with multiple kubeflow clusters (KF_NAME), but this doesn't seem to work. 

I have tried troubleshooting, and I have the following observations:

1. Going to https://${KF_NAME}.endpoints.${PROJECT}.cloud.goog/ gives me a DNS error (DNS_PROBE_FINISHED_NXDOMAIN)
2. envoy-ingress shows one backend as unhealthy
3. `kubectl describe cloudendpoint -n istio-system` shows an active cloudendpoint
4. No endpoint entry is created in https://console.cloud.google.com/endpoints
5. Cloud IAP (https://console.cloud.google.com/security/iap) shows an "Error" in one of the backends (saying OAuth client is misconfigured). It auto turns off IAP. I have tried manually turning it on and reinstalling with no avail.

If 5 indeed is a real issue, why does it work when I do a fresh installation (with a new ${KF_NAME})? I export the same CLIENT_ID and CLIENT_SECRET in both cases.

Everything else looks okay (looking at various K8s deployments and services)

**What did you expect to happen:**

I expected my cluster to be recreated

**Anything else you would like to add:**

Currently, I workaround by creating a new kubeflow every time. However, that has a major con that all my data (notebooks, Pipelines are gone). We can't keep doing this with a production setup.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): I installed it using `kfctl_gcp_iap.v1.0.2.yaml`
- kfctl version: (use `kfctl version`): kfctl v1.0.2-0-ga476281
- Kubernetes platform: (e.g. `minikube`): GKE 
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.45", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-17T19:54:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
Mac OS 10.14

**Comment by jlewi** [comment] 2020-09-02 03:10
Duplicate of #5048

**Closed by jlewi** 2020-09-02 03:10 UTC
Labels: area/kfctl, kind/bug
