### ISSUE TITLE
Kubeflow notebook cull not stoping notebook after IDLE_TIME. it stops after 24 hours only.

### ISSUE THREAD

**Issue by zeldebro** [kubeflow/kubeflow#7053] opened 2023-03-21 06:18 UTC
I have  enabled kubeflow notebook cull but it is not stoping(culling) pod at specified Idle time.

it only stops pod after 24 hours not before it.

like in below configuration i have added 5 minute Idle time and 1 minute culling check period  but pod not get stop after 5 minute, it stops after 24 hours only.

i have added below environment varibale in controller deployment.yaml.
```
- name: ADD_FSGROUP
   value: "false"
- name: ENABLE_CULLING
   value: "true"
- name: IDLE_TIME
    value: "5"
- name: CULLING_CHECK_PERIOD
   value: "1"
```

even i have added AuthorizationPolicy and enabled istio side car.

 `sidecar.istio.io/inject: "true"`

i don't see any error in logs.

**Comment by jsitu777** [comment] 2023-03-23 00:32
Hi @zeldebro , are you checking out the 1.6.1 release branch for both kubeflow and aws-release?

**Comment by jsitu777** [comment] 2023-03-23 15:57
You mean kubeflow version 1.6.0 but aws-release 1.6.1 right? notebook-culling feature was released in 1.6.1 but not 1.6.0 https://github.com/awslabs/kubeflow-manifests/blob/release-v1.6.1-aws-b1.0.0/awsconfigs/apps/notebook-controller/params.env

**Comment by jsitu777** [comment] 2023-03-23 16:13
Not sure if you are using AWS distribution. I'm reproducing in my end, meanwhile you can read up the doc here maybe helpful. https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide/#optional-configure-culling-for-notebooks
https://github.com/awslabs/kubeflow-manifests/pull/470

**Comment by jsitu777** [comment] 2023-03-23 19:06
Hi @zeldebro I recommend you use the patch release KUBEFLOW v1.6.1
https://github.com/kubeflow/kubeflow/compare/v1.6.0...v1.6.1

You can have notebook culling feature set up with: 

- KUBEFLOW v1.6.1
- AWS Kubeflow Distro release-v1.6.1-aws-b1.0.1

1. Set up v1.23 eks cluster https://awslabs.github.io/kubeflow-manifests/docs/deployment/create-eks-cluster/
2. Since you are using k8s v1.23+, you will first need to set up ebs-csi driver after your eks cluster is ready. https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
  -- set up iam service-account https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
  -- create ebs-addon  https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html
3. Clone github repo https://awslabs.github.io/kubeflow-manifests/docs/deployment/prerequisites/#clone-repository
4. Export Culling parameter as you wish following https://awslabs.github.io/kubeflow-manifests/docs/deployment/configure-notebook-culling/
5. Assuming you are deploying kubeflow vanilla version with kustomize, run one-click deploy kubeflow command in root directory `make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla
`  https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide/#install-with-a-single-command  If you wish to use aws-service to replace default kubeflow components we do have various integration option such as RDS, S3, Cognito; you can also deploy it via Terraform or Helm
6. I was able to cull the notebook after 5 minutes per input configuration https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/apps/notebook-controller/params.env 
```
enableCulling=true
cullIdleTime=5
idlenessCheckPeriod=1
```

**Comment by zeldebro** [comment] 2023-03-24 06:18
Hi @jsitu777 

I am not using AWS Kubeflow Distro. I am using KUBEFLOW (which deployed in my own k8s environment.)

**Comment by farshadghodsian** [comment] 2023-09-13 20:27
Not sure if this is still an issue for you or which exact distrobution you are using, but I am guess you are not using the correct environment variable. If you are using v1.6.0 or v.1.6.1 of the notebook controller the correct Environment variables you should be using are:
``` 
- name: ENABLE_CULLING
    value: "true"
 - name: CULL_IDLE_TIME
    value: "5"
- name: IDLENESS_CHECK_PERIOD
   value: "1"
```

Your use of `IDLE_TIME` is probably the issue. By default if you dont have anything set for `CULL_IDLE_TIME` it defaults to 24hrs or 1 day. Hence why your notebook culler is tagging notebooks and working, but not killing notebooks in the desired time that you have set. Also note sure where you got `CULLING_CHECK_PERIOD`, as I've found that `IDLENESS_CHECK_PERIOD` is the one that works.

The accepted values and defaults are set in the culling_controller.go file.
https://github.com/kubeflow/kubeflow/blob/194a725119e9bf8a16db37a1d23f0e941ab7f1e4/components/notebook-controller/controllers/culling_controller.go#L30-L40

**Closed** 2023-10-02 07:26 UTC
