### ISSUE TITLE
Tensorboard support

### ISSUE THREAD

**Issue by foxish** [kubeflow/kubeflow#17] opened 2017-12-07 16:22 UTC
This issue tracks Tensorboard support in kubeflow.

There is already a plugin installed in some of our images to integrate Tensorboard with Jupyter. 
We require some additional vetting to ensure this works as expected through the proxy.

cc @jlewi @vishh

**Comment by bhack** [comment] 2017-12-17 11:32
There will be any coordination with https://github.com/tensorflow/tensorboard/issues/92?

**Comment by aronchick** [comment] 2017-12-17 18:58
Yes! We know/work with the TF team closely, and want to overlap. Are you
working on that already?

**Comment by bhack** [comment] 2017-12-17 19:42
Still not cause I think that you are still on an internal planning phase so it is hard to avoid overlaps. But I hope that the plan and the internal roadmap will be public soon with contribution welcome labels.

**Comment by aronchick** [comment] 2017-12-17 23:29
I don't think we're doing any internal planning right now - did someone
tell you that? I'm happy to loop back with them.

**Comment by bhack** [comment] 2017-12-17 23:57
I meant on TB side. It is what seems by https://github.com/tensorflow/tensorboard/issues/92#issuecomment-348565800

**Comment by jlewi** [comment] 2018-01-19 05:53
Yes. We talk to @jart regularly and are trying to figure out how to bring TB as a service to Kubeflow.

**Comment by jart** [comment] 2018-01-19 07:40
We're very interested in bringing TensorBoard to Kubeflow. Doing this has raised challenging concerns that caused the TensorFlow team to think more about how it logs and loads data.

Right now we're focusing on taking an openly portable first approach. We want to get a rudimentary SQLite data model off the ground to learn more about how we can meet our requirements. You can see some of the work that's been done in [summary_db_writer.cc](https://github.com/tensorflow/tensorflow/blob/e202188ef741608384a3439fdbc0c4e2fb96e3f1/tensorflow/contrib/tensorboard/db/summary_db_writer.cc) and [schema.cc](https://github.com/tensorflow/tensorflow/blob/e202188ef741608384a3439fdbc0c4e2fb96e3f1/tensorflow/contrib/tensorboard/db/schema.cc).

While ubiquity is of the utmost concern, we have some confidence at this point that SQLite can carry a respectable amount of data when used in conjunction with reservoir sampling and an old school engineering mindset. Most importantly it offers big gains in terms of latency and accessibility.

While I can't speak for Kubeflow, I know SQLite can work in Kubernetes environments. While no single DB can meet the requirements of every organization, please note SQLite is but an appetizer. There are many other possibilities we're looking forward to exploring.

**Comment by jlewi** [comment] 2018-03-20 17:15
Duplicate of #297

**Closed** 2018-03-20 17:15 UTC

**Comment by bigdatamlai** [comment] 2019-04-19 12:24
Tensorboard is not comming up on kubeflow
put this in root /mlpipeline-ui-metadata.json
{
  "version": 1,
  "outputs": [
    {
      "type": "tensorboard",
      "source": "/mnt/share/tflogs"
    }
  ]
}

**Comment by josefkorbel** [comment] 2019-06-18 11:59
Any news regarding tensorboard in KF? We are using KF on GCE, I see it deployed even a TensorBoard pod, but cannot find any straight-forward way how to incorporate it into fairing.
