### ISSUE TITLE
Support Istio 1.6

### ISSUE THREAD

**Issue by axelgobletbdr** [kubeflow/kubeflow#5176] opened 2020-07-31 09:25 UTC
Kubeflow uses Istio as a service mesh. Currently, Kubeflow only supports Istio up to version 1.5. Meanwhile, Istio 1.6 was released, and an experimental 1.7 is available as well. Istio 1.6 contains many improvements over 1.5, which cannot be used in any Kubernetes cluster running Kubeflow. This is very problematic.

It would be great if Kubeflow would support newer versions of Istio, such that the Kubernetes clusters can stay up to date, performant, and secure. In order to support Istio 1.6, the following changes need to be made:
- Kubeflow currently uses Istio RBAC policy for auth. These are no longer supported in Istio 1.6 as described [here](https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/#support-ended-for-v1alpha1-security-policy). They will need to be replaced by the new [RequestAuthentications](https://istio.io/latest/docs/reference/config/security/request_authentication/). Istio RBAC is used [here](https://github.com/kubeflow/kubeflow/search?q=istiorbac&unscoped_q=istiorbac) in kubeflow.
- There was some parameter renaming that needs to be fixed, as described in https://github.com/kubeflow/kubeflow/issues/5070

I do not know if this list is complete, but these are the main issues that need to be solved in order to move to Istio 1.6. Feel free to comment on this issue with additional changes that have to be made.

My team is willing to participate on making these changes happen, as the newer Istio versions are very important to us. Before putting work into making these changes, we would like to work together with the maintainers to make sure the changes we make are valid for incorporation into Kubeflow

**Comment by Jeffwan** [comment] 2020-08-06 15:58
@axelgobletbdr 

Trying to understand any features user want to leverage from 1.6? Currently, most manifest is still on 1.3.x, we probably consider upgrade the version gradually in each major releases but may not to 1.6 directly because if user has workloads on older versions, they have to do force upgrade as well. 

Currently, access management and profile controller in control plane uses istio. We can make the change later

**Comment by axelgobletbdr** [comment] 2020-08-10 07:49
Hi @Jeffwan,

First of all I think it is generally good practice to keep your upstream dependencies up to date. Furthermore, new Istio versions include security related fixes like https://github.com/istio/istio/issues/23715. Keeping dependencies up to date makes Kubeflow overall more suitable for production scenario's.

I understand that several Kubeflow components rely on older versions of Istio. Maybe it is a good starting point to list what needs to change in order to support the latest Istio version. I started a list in my initial comment of this story. Please extend it with additional changes that need to be made.

**Comment by hungrysushi** [comment] 2020-08-17 21:57
Also very interested in seeing support for this, as I am trying to deploy Kubeflow with OIDC to a cluster with an existing Istio 1.6.x deployment for other services, and since authentication is so closely tied to Istio, this has been a bit of an obstacle for us.

The issues we have run into so far, other than the ones mentioned already by @axelgobletbdr, are around authentication using the provided cluster-local-gateway to isolate the kubeflow traffic. The `istio-pilot` svc has gone away meaning that the discovery addresses need to be updated, and the EnvoyFilter needs to be rewritten to follow the new spec.

I would be interested in participating in this work, as well.

**Comment by thesuperzapper** [comment] 2020-10-07 23:58
See UBER issue: #5176

**Comment by jlewi** [comment] 2020-10-28 23:24
Duplicate of #5313

**Closed by jlewi** 2020-10-28 23:24 UTC
Labels: area/istio, kind/feature, priority/p1

**Comment by sdake** [comment] 2020-11-11 11:15
@Jeffwan just a note from an upstream Istio maintainer and wg lead. 1.3 is far out of any upstream support window. would encourage tracking the latest Istio (1.8 is due for release within the week). We release quarterly, and once you make the move to 1.8, updating to 1.9 and onward should be straightforward. Istio has always had a strong focus on upgrade compatibility. We are doubling down on forward compatibility with enhanced testing and more process for externally facing APIs.

If your desire is to upgrade from 1.3 to 1.8, your in for some serious pain. It can be done. I would upgrade from 1.3, to 1.4, to 1.5, then skip-level upgrade to 1.7 with validation off. Note skip-level upgrades are unsupported (as they are not tested), so YMMV.
