### ISSUE TITLE
kubeflow stuck at setup screen

### ISSUE THREAD

**Issue by jmsking** [kubeflow/kubeflow#4410] opened 2019-10-25 06:37 UTC
/kind bug

when i install kubeflow according to this doc: https://v0-6.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/, and there is a kubeflow setup page when i vist kubeflow ui, it can't come into kubeflow ui, and this issue is the same as #4126 

And i according to @jlewi , i create a profile manually follow this doc: https://www.kubeflow.org/docs/other-guides/multi-user-overview/
And my profile yaml is as follows:

_apiVersion: kubeflow.org/v1alpha1
kind: Profile
metadata:
  name: kubeflow-anonymous   # replace with the name of profile you want
spec:
  owner:
    kind: User
    name: anonymous@kubeflow.org   # replace with the email of the user_

but i still can't come into main page, here is my namespace and profile:
**$ kubectl get profile**
```
NAME                 AGE
kubeflow-anonymous   30s
```
**$ kubectl get ns**
```
NAME                 STATUS   AGE
default              Active   8d
istio-system         Active   23h
kube-node-lease      Active   8d
kube-public          Active   8d
kube-system          Active   8d
kubeflow             Active   23h
kubeflow-anonymous   Active   55s
```
Any help i will appreciate!!

my kubeflow's version is 0.6.2

**Comment by jlewi** [comment] 2019-10-25 17:59
@jmsking can you provide the output of

```
kubectl get profiles -o yaml 
```

@avdaredevil How do we debug what identity the UI is using to fetch namespaces?

**Comment by avdaredevil** [comment] 2019-10-25 22:27
It is quickly viewable via the XHR (AJAX) Requests that are made, or even the user that shows on hover over the user logo
![image](https://user-images.githubusercontent.com/5303018/67608134-c9115c00-f73b-11e9-8848-025a858e2c9e.png)

### OR

![image](https://user-images.githubusercontent.com/5303018/67608173-f65e0a00-f73b-11e9-9034-fa16ae32b5f7.png)

**Comment by jmsking** [comment] 2019-10-26 02:24
**$ kubectl get profile -o yaml**
_NAME                 AGE
kubeflow-anonymous   19h
apiVersion: v1
items:
  apiVersion: kubeflow.org/v1alpha1
  kind: Profile
  metadata:
    creationTimestamp: "2019-10-25T06:31:04Z"
    generation: 1
    name: kubeflow-anonymous
    resourceVersion: "1724354"
    selfLink: /apis/kubeflow.org/v1alpha1/profiles/kubeflow-anonymous
    uid: 7695e7e9-27ff-4e4b-8781-3111204ad90b
  spec:
    owner:
      kind: User
      name: anonymous@kubeflow.org
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""_

**Comment by jmsking** [comment] 2019-10-28 02:53
Can anybody solve this question@jlewi @avdaredevil

**Comment by avdaredevil** [comment] 2019-10-28 11:23
@jmsking In your dev console (<kbd>f12</kbd> or <kbd>ctrl + shift + c</kbd> or <kbd>cmd + shift + c</kbd>) can you please navigate to the Network tab, and filter by XHR
![image](https://user-images.githubusercontent.com/5303018/67674734-8b2e5680-f93a-11e9-9ae8-52b4a779942e.png)

Then check for the route `/api/workgroup/exists` and please output the response you have for it, in my case, it looks like:
![image](https://user-images.githubusercontent.com/5303018/67608173-f65e0a00-f73b-11e9-9034-fa16ae32b5f7.png)

**Comment by jmsking** [comment] 2019-10-28 11:39
![image](https://user-images.githubusercontent.com/4349983/67675672-b22c6d00-f9ba-11e9-93ac-76be5488b8c6.png)

**Comment by jmsking** [comment] 2019-10-28 11:42
Thanks for you reply,  this is my presentation:
**exists**:   {hasAuth: false, user: "anonymous", hasWorkgroup: false}
**env-info**: user: "anonymous@kubeflow.org",…}
                         isClusterAdmin: true
                         namespaces: []
                         platform: {kubeflowVersion: "v0.6.2", provider: "other://", providerName: "other"}
                         user: "anonymous@kubeflow.org"

**Comment by jmsking** [comment] 2019-10-28 11:47
![exist](https://user-images.githubusercontent.com/4349983/67676070-b907af80-f9bb-11e9-8220-e1fa1c563691.jpg)

**Comment by jmsking** [comment] 2019-10-30 03:04
I am sorry to bother you, Can someone supply some solutions for this question?@avdaredevil@jlewi

**Comment by jmsking** [comment] 2019-10-30 03:08
![image](https://user-images.githubusercontent.com/4349983/67825809-8964be80-fb05-11e9-8ba8-f5e9099979fe.png)

**Comment by jmsking** [comment] 2019-10-30 03:10
![test](https://user-images.githubusercontent.com/4349983/67825942-ef514600-fb05-11e9-8102-fc2e41a8f2c7.jpg)

**Comment by avdaredevil** [comment] 2019-10-30 05:23
Duplicate of #4415 being fixed via #4015

**Comment by jmsking** [comment] 2019-10-30 06:13
Do i need update kubeflow to  v0.7 or should i change the centerboard image to a new one?
when i execute **"host:port/debug"**, here is my output:
**{"user": 
 {"email":"anonymous@kubeflow.org","username":"anonymous","domain":"kubeflow.org","hasAuth":false},"profilesServiceUrl":"http://profiles-kfam.kubeflow:8081/kfam","codeEnvironment":"production","headersForIdentity":{"USERID_HEADER":"","USERID_PREFIX":""}}**

**Comment by jmsking** [comment] 2019-10-30 06:18
And when i execute **"host:port/api/workgroup/env-info"**, here is my response:
**{"error":"Unable to ascertain user identity from request, cannot access route."}**

**Comment by jmsking** [comment] 2019-10-30 06:46
OK, thanks for you answer!

**Closed** 2019-10-30 06:46 UTC
Labels: area/front-end, kind/question, priority/p1
