### ISSUE TITLE
How to port model developed in Jupyter notebook to TFJobs

### ISSUE THREAD

**Issue by abhishektiwari** [kubeflow/kubeflow#110] opened 2018-01-10 20:38 UTC
I am working on a very comprehensive tutorial for Kubeflow but I am having a hard time to understand how a Tensorflow model developed in a Jupyter notebook can be ported to TFJobs. I see a disconnect. 

It seems one has to containerize the model from Jupyter and submit using Ksonnet but how? How to create a model prototype?

**Comment by foxish** [comment] 2018-01-10 21:08
@abhishektiwari thanks for the report! This is a good discussion to have - we should have a good story around migrating from single-node to multi-node training. One approach that was discussed was using a python library to provide the scaffolding - to enable TFJob to launch from the Jupyter notebook. Open to further discussion here.

cc/ @vishh @aronchick @jlewi @kow3ns

**Comment by amitkumarj441** [comment] 2018-01-11 09:23
@abhishektiwari Actually current model of CRD is straight-out to TF training jobs. As single CRD for multiple TFJob types might not a good choose and I agree with the idea of @foxish about providing a scaffolding.

**Comment by foxish** [comment] 2018-01-11 14:23
Related to https://github.com/google/kubeflow/issues/87

**Comment by jlewi** [comment] 2018-01-12 15:57
My interpretation of the original question was
  * I have a bunch of code in a Jupyter notebook split across multiple cells
  * The code runs "interactively" (i.e. by executing the cells) in jupyter
  * Now you want to submit a TfJob to run the code

So its not necessarily about going from single node to multi-node.

So the first thing you need to do is turn your notebook into an executable program. 

There are lots of ways to do this. Jupyter provides some tooling to do this automatically but oftentimes that's probably not what you want because there's probably a lot of code in your notebook that you don't want to be part of your program.

Typically why I do is refactor the notebook, putting all of the code I need into functions in a python module. I can then import the python module into Jupyter and invoke the functions as needed to verify they work.

You can then add a main function to your python files and not you have a program.

At this point you can build a docker image containing your code. You could use the TensorFlow images as a base image, or if you're running Jupyter in a container whatever docker image you used so that you have the same environment.

You can now create a TfJob from the ksonnet component that specifies your docker image and any command line arguments your program takes.

If you want to run distributed training, you need to make sure TF program a [distributed TF program](https://www.tensorflow.org/deploy/distributed). At this point you can configure your TfJob to run distributed by specifying the number of workers and parameter servers to use.

**Comment by abhishektiwari** [comment] 2018-01-14 07:25
@jlewi Thanks a lot for explaining it so well. 

After a bit of digging, I managed to figure this out but being newbie I was not sure. I initially thought there must be a magical way to take Jupyter notebook's interactive code and convert into a TFJob. I would love to see something like that but for now, I can continue with the workflow you described above.

**Comment by jlewi** [comment] 2018-01-22 23:59
I think we should try to summarize this information and add it to our docs.

**Comment by willb** [comment] 2018-01-23 03:52
@jlewi, I’ve been interested in developing lightweight tools to aid the process of refactoring notebooks into services or jobs for some time. Here’s a crack at part of the problem (identifying modules that a given function depends upon):  https://chapeau.freevariable.com/2017/12/module-frontier.html

**Comment by jlewi** [comment] 2018-08-06 13:32
Duplicate of #1240

**Closed by jlewi** 2018-08-06 13:32 UTC
Labels: area/docs, area/inference
