### ISSUE TITLE
Jupyter-web-app should read Notebook conditions to check its status

### ISSUE THREAD

**Issue by zabbasi** [kubeflow/kubeflow#3405] opened 2019-06-04 20:11 UTC
Jupyter-web-app currently reads notebook.status.containerStatus to check the notebooks status. However [this PR]( https://github.com/kubeflow/kubeflow/pull/3319) adds notebook pod status type and the transition detail in Notebook.status.conditions. Hence, in Jupyter-web-app we should be able to check the notebooks' pods status by reading the latest status written in Notebook.status.conditions. 

/cc @lluunn @kimwnasptd

**Comment by kimwnasptd** [comment] 2019-08-08 08:07
/assign @kimwnasptd 

More info on #3820. By using the `conditions` we can also surface the errors with the Pod's scheduling.

**Comment by jlewi** [comment] 2019-11-26 14:26
@kimwnasptd should we close this as a duplicate of #3637?

**Comment by kimwnasptd** [comment] 2019-12-03 16:27
@jlewi yes, with the fix for #3637 we will be using the Notebook Events to provide more info in case the Notebook cannot start. I believe we can close this issue.

**Comment by jlewi** [comment] 2019-12-05 06:58
Duplicate of #3637

**Closed by jlewi** 2019-12-05 06:58 UTC
Labels: area/jupyter, kind/feature, priority/p2
