### ISSUE TITLE
Recreating Kubeflow 0.5.0 on GCP fails

### ISSUE THREAD

**Issue by yuvaldrori** [kubeflow/kubeflow#3212] opened 2019-05-07 18:05 UTC
Hello.

Using the instructions in ["Instructions for using the CLI to deploy Kubeflow on Google Cloud Platform (GCP)"](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) I was able to create a Kubeflow 0.5.0 cluster:
```
kfctl init ${KFAPP} --platform gcp --project ${PROJECT} --use_basic_auth -V
cd ${KFAPP}
kfctl generate all -V --zone ${ZONE}
kfctl apply all -V
```
Trying to destroy and recreate will not work. After destroying the load balancer and backends will not be cleaned up.
```
kfctl kfctl delete all --delete_storage
kfctl apply all -V
```

Thanks.

**Comment by jlewi** [comment] 2019-05-10 13:57
Duplicate of #3203

**Closed by jlewi** 2019-05-10 13:57 UTC
Labels: kind/bug
