### ISSUE TITLE
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: Could not find namespace kubeflow-anonymous, wait and retry: namespaces "kubeflow-anonymous" not found

### ISSUE THREAD

**Issue by jmsking** [kubeflow/kubeflow#4203] opened 2019-09-27 14:06 UTC
/kind bug

**Question:**
>>i plan to install kubeflow on exist k8s cluster according to the document in https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/, but when i run:
$ kfctl apply all -V
and there are error information as follows:
>>**Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: Could not find namespace kubeflow-anonymous, wait and retry: namespaces "kubeflow-anonymous" not found**

**Environment**
**-----K8s-----**
>>**kubectl version**
>>Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**-----OS-----**
>>$cat /etc/os-release
>>NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

**-----kubeflow-----**
>>$kfctl version
>>kfctl v0.6.2-0-g47a0e4c7

**Any help i will appreciate!**

**Comment by krishnadurai** [comment] 2019-09-27 14:15
@jmsking Looks like this could be duplicate of issue #4090. Can you please confirm?

**Comment by jmsking** [comment] 2019-09-27 14:32
yeahhhhh, i am so sorry for than, i will close this issue

**Closed** 2019-09-27 14:32 UTC
Labels: kind/bug
