### ISSUE TITLE
kfctl apply overrides customized changes

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#4368] opened 2019-10-22 22:44 UTC
/kind bug

**What steps did you take and what happened:**

1. `kfctl build -f https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml`
1. made some dummy changes in `kustomize/`
1. `kfctl apply -f kfctl_gcp_iap.0.7.0.yaml`

**What did you expect to happen:**

Customized changes shouldn't be overridden.

**Anything else you would like to add:**

This is probably because during `kfctl apply` kfctl didn't check whether it's already built.

**Environment:**

- kfctl version: (use `kfctl version`): v0.7.0-rc.5-0-g18fba77a

**Comment by jlewi** [comment] 2019-10-23 04:03
@Jeffwan Do we need to make a similar change for AWS?

It looks like existing.go doesn't do anything for generate.
https://github.com/kubeflow/kubeflow/blob/4ddb254e245a377713181a05ce9e6f47897d86fc/bootstrap/pkg/kfapp/existing_arrikto/existing.go#L108

**Comment by Jeffwan** [comment] 2019-10-24 09:51
@jlewi This actually brings another problem. 

In our case, 
1. kfctl build -f ${remote_file}, kustomize folder is created. 
2. we ask user to change local copy of ${remote_file}. For example, specify role, region, cluster name
3. kfctl apply -f ${local_file} 

We need kustomize to regenerate manifests after step 2. This PR actually block this. 

Checking cloud config makes sense, I am wondering any case user need to update kustomize folder? It supposed be generated from manifest configuration.

**Comment by Jeffwan** [comment] 2019-10-24 09:59
I can confirm that customization on manifest won't be applied due to this change. 

```
kfctl apply -V -f ${CONFIG_FILE}
INFO[0000] Running `eksctl version` ...                  filename="utils/awsutil.go:54"
INFO[0000] output: [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.5.3"}  filename="utils/awsutil.go:62"
INFO[0000]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0000] /Users/shjiaxin/Downloads/kf082/kf070/.cache/manifests exists; not resyncing   filename="kfconfig/types.go:460"
**INFO[0000] folder /Users/shjiaxin/Downloads/kf082/kf070/kustomize exists, skip kustomize.Generate  filename="kustomize/kustomize.go:300"**
```

**Comment by jlewi** [comment] 2019-10-24 12:13
@Jeffwan I think this is working as intended; i.e. `kfctl build` is not intended to regenerate the kustomize  files if they have already been generated. This is by design because this would end up overwriting any changes the users had made to the kustomize files. We want users to provide a signal that the intended behavior is to overwrite the kustomize files. Rather than add an "overwrite" or "force" option the expectation is that users would just remove the kustomize directory and then run build and/or apply to take into account changes to the KFDef file.

So in your case the situation would be as follows

1. kfctl build -f ${remote_file}, kustomize folder is created.
1. we ask user to change local copy of ${remote_file}. For example, specify role, region, cluster name
1. rm -rf kustomize
1. kfctl apply -f ${local_file}

Alternatively users could do

1. curl -L -O http://.../kfctl_aws.yaml
1. we ask user to change local copy of ${remote_file}. For example, specify role, region, cluster name
1. kfctl apply -f ${local_file}

**Comment by Jeffwan** [comment] 2019-10-24 17:22
@jlewi Thanks. Makes sense. I will make doc change for AWS.
Here's the PR for cloud config changes override issue. 
https://github.com/kubeflow/kubeflow/pull/4390

**Comment by Jeffwan** [comment] 2019-10-24 18:16
aws change has been merged. This cane be closed. 

/close

**Closed by Jeffwan** 2019-10-24 18:16 UTC
Labels: area/kfctl, effort/1-day, kind/bug, priority/p0
