### ISSUE TITLE
metadata-grpc-deployment pod keeps losing its connection to the mysql server

### ISSUE THREAD

**Issue by amygdala** [kubeflow/kubeflow#4797] opened 2020-02-25 02:59 UTC
/kind bug
(have a sense that this might be a dup, but if so I failed to find the original. I'm filing in the kf repo (not kfp) because for some reason the 'standalone'/Hosted KFP install doesn't seem to get this error.  However, I can move it there if that would be better.).

With KF 1 RC4:
The `metadata-grpc-deployment` pod keeps losing its connection to the mysql server.  In the Pipelines UI you'll see this:
![image](https://user-images.githubusercontent.com/115093/75210712-aff2d900-5736-11ea-91ae-ecf364efb0cd.png)
The pod logs show:
```
2020-02-23 20:05:05.536198: I ml_metadata/metadata_store/metadata_store_server_main.cc:197] Server listening on 0.0.0.0:8080
2020-02-25 02:46:46.481297: W ml_metadata/metadata_store/metadata_store_service_impl.cc:310] GetArtifacts failed: mysql_query failed: errno: 2006, error: MySQL server has gone away
```

The mysql server has not actually gone away. The workaround is to restart the `metadata-grpc-deployment`.  After which, the restarted pod no longer gets the error (for a period of time).

**Comment by zhenghuiwang** [comment] 2020-02-25 22:06
Duplicate of https://github.com/kubeflow/metadata/issues/198

@amygdala Is the grpc-deployment image version v0.21(which contains the fix)? The fix was cherry-picked to v1.0 manifests 6 days ago. ([Reinstall the latest component](https://www.kubeflow.org/docs/components/metadata/#installing-the-metadata-component) or KF should fix it)

**Comment by amygdala** [comment] 2020-02-25 23:39
(ah... I knew I'd seen a similar bug somewhere, sorry I didn't think to check the metadata repo)
No, it's an older image.  I confirmed that I was using the latest KF 1 RC (4) but it's been > 6 days since I spun up the cluster. I'll try a new deploy.

**Comment by jlewi** [comment] 2020-02-26 13:42
Closing this issue; lets use the duplicate

**Closed by jlewi** 2020-02-26 13:42 UTC
Labels: kind/bug, priority/p1
