### ISSUE TITLE
Documentation on version control of Jupyter notebooks

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/kubeflow#4824] opened 2020-03-04 12:41 UTC
/kind feature

**Why you need this feature:**
Documentation on version control of Jupyter notebooks

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
How do we add version control to Jupyter notebook and build a docker images. Especially one with aws code commit and code pipeline being used for CD after converting to Kale pipelines? Can anyone contribute with this?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jlewi** [comment] 2020-04-06 14:44
Duplicate of #2889

**Closed by jlewi** 2020-04-06 14:44 UTC
Labels: kind/feature
