### ISSUE TITLE
Kubeflow v1.2 release

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kubeflow#5371] opened 2020-10-29 19:00 UTC
/kind process

Time line: 
- RC Release: Nov 7
- Official Release: Nov 16

WGs and projects

Area | release czar | Tracking Issue
 --- | --- | ---
centraldashboard | | https://github.com/kubeflow/kubeflow/pull/5412
docs |@RFMVasconcelos  | kubeflow/website#2322
fairing | @jinchihe  |  |
feast | @woop | |
katib | @andreyvelich  | https://github.com/kubeflow/manifests/pull/1593 |
kfctl | @Jeffwan    | https://github.com/kubeflow/kfctl/issues/421  |
kfserving | @yuzisun @animeshsingh @cliveseldon  | https://github.com/kubeflow/manifests/pull/1600 https://github.com/kubeflow/manifests/pull/1575 |
manifests | @Jeffwan  | kubeflow/manifests#1597
metadata | |
notebooks | @kimwnasptd , @jtfogarty |  | 
pipelines | @Bobgy | https://github.com/kubeflow/manifests/pull/1605 | 
training |  @johnugeorge @gaocegege @terrytangyuan  | |

Platforms
Platforms | release czar | Tracking Issue
 --- | --- | ---
aws | @PatrickXYS   |  | 
azure | @aronchick  | |
ibm | @animeshsingh @adrian555 @shawnzhu | |
gcp | @jlewi @Bobgy  |  |
minikf | @vkoukis | |

**Comment by woop** [comment] 2020-10-30 04:07
@Jeffwan there won't be code level changes for 1.2 on the Feast side. We are targeting 1.3 for those changes and we will drive it through the SIG.

**Comment by jlewi** [comment] 2020-10-30 15:24
@RFMVasconcelos and @8bitmp3 and @joeliedtke What is the plan for the docs? Specifically when do we plan on cutting a 1.1. branch of the docs so that people can start updating master with changes that would only apply to newer releases (e.g. kubeflow/website#2126)

**Comment by RFMVasconcelos** [comment] 2020-11-02 09:37
Sorry for the late reply here! I am happy to work on cutting `v1.1-branch` during this week :)

**Comment by jlewi** [comment] 2020-11-02 13:58
> Interesting I find is we didn't cut v1.1-branch in v1.1 release

This is typical. We usually don't cut the 1.X branch until we are ready to start working on the 1.Y docs on master. This is typicallly because the 1.X docs lag the 1.X release.

**Comment by Jeffwan** [comment] 2020-11-04 01:10
Please add items you plan to put into 1.2 in project https://github.com/orgs/kubeflow/projects/41

WG owner, please help update changelog for 1.2 here
https://docs.google.com/presentation/d/1_PxXWuy_TKEZyuPGZQZ1fBHMAupM3rBPZQow98L0iCY/edit?ts=5fa05fd4#slide=id.g8f86ec6f96_0_76

**Comment by Jeffwan** [comment] 2020-11-09 08:31
I cut v1.2-branch for kfctl and manifest. Please help test against the RC tag. If there's bug and features missing in v1.2-rc.0, feel free to file a cherry-pick PR.

https://github.com/kubeflow/kfctl/releases/tag/v1.2-rc.0
https://github.com/kubeflow/manifests/releases/tag/v1.2-rc.0

**Comment by Jeffwan** [comment] 2020-11-15 18:28
I am cutting another RC release for 1.2. Please let me know anything you want to bring back to 1.2

**Comment by Jeffwan** [comment] 2020-11-17 06:40
Please help log the pending PRs here. That helps make sure release team include critical PR/fix in the official 1.2 release

/cc @kubeflow/release-team

**Comment by berndverst** [comment] 2020-11-18 02:41
@Jeffwan this should go into 1.2. First needs to go into master, and then cherry-picked into 1.2. Thanks!
https://github.com/kubeflow/manifests/pull/1655

**Comment by Bobgy** [comment] 2020-11-18 07:18
@Jeffwan I need to fix https://github.com/kubeflow/manifests/issues/1573 for Kubeflow Pipelines.
WIP on sending a PR

**Comment by Jeffwan** [comment] 2020-11-18 18:28
@berndverst kubeflow/manifests#1655 I left some comments there. I would be better to find some Azure folks to help review the change in the future.

**Comment by Bobgy** [comment] 2020-11-19 06:38
@Jeffwan After verifying the label selector for KFP, I think it matches our resources. We are good to go.

**Comment by Jeffwan** [comment] 2020-11-19 07:00
@Bobgy Great. I will run some tests against v1.2-branch and cut another RC later today.

**Comment by berndverst** [comment] 2020-11-19 07:28
My last PR (cherry picking into manifests/v1.2-branch) is pending for review here: https://github.com/kubeflow/manifests/pull/1661

**Comment by Jeffwan** [comment] 2020-11-19 08:04
I finish [mnist](https://github.com/kubeflow/examples/tree/master/mnist#aws) testing. Everything works for me! 

env:
- kfctl v1.2-branch
- kustomize v1.2-branch 
- kfdef https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_aws.v1.2.0.yaml
- notebook: https://github.com/kubeflow/examples/blob/master/mnist/mnist_aws.ipynb

```
➜  spotcluster k get pods -n admin
NAME                                               READY   STATUS      RESTARTS   AGE
fairing-builder-v2ptl-6q84c                        0/1     Completed   0          5m24s
file-passing-pipelines-2t2lk-1632278589            0/2     Completed   0          23m
file-passing-pipelines-2t2lk-1975393501            0/2     Completed   0          23m
file-passing-pipelines-2t2lk-225698614             0/2     Completed   0          23m
file-passing-pipelines-2t2lk-3086569782            0/2     Completed   0          22m
file-passing-pipelines-2t2lk-3103347401            0/2     Completed   0          22m
file-passing-pipelines-2t2lk-3120125020            0/2     Completed   0          22m
file-passing-pipelines-2t2lk-3136902639            0/2     Completed   0          23m
file-passing-pipelines-2t2lk-3737901737            0/2     Completed   0          23m
file-passing-pipelines-2t2lk-856952097             0/2     Completed   0          23m
ml-pipeline-ui-artifact-84f654dd94-wkxwz           2/2     Running     0          24m
ml-pipeline-visualizationserver-5ff65bf999-bhrr4   2/2     Running     0          24m
mnist-0                                            2/2     Running     0          20m
mnist-model-58cdcdcdcf-h2bfr                       1/1     Running     0          2m33s
mnist-tensorboard-666587dd86-4hq8d                 2/2     Running     0          3m41s
mnist-train-50f7-chief-0                           0/1     Completed   0          4m2s
mnist-train-50f7-worker-0                          0/1     Completed   0          4m2s
mnist-ui-6d66bcbf69-2mcvw                          2/2     Running     0          2m26s
```

**Comment by Jeffwan** [comment] 2020-11-19 08:05
I plan to run some more tests against kfctl_istio_dex.v1.2.0.yaml and kfctl_k8s_istio.yaml. If anyone has time, please help on the tests as well

**Comment by Jeffwan** [comment] 2020-11-19 09:06
Hi Platform owner,

@PatrickXYS @Bobgy @animeshsingh @berndverst @vkoukis @aronchick @nakfour @krishnadurai  @kubeflow/release-team 

I know we have some pending PRs going on here. https://github.com/kubeflow/manifests/issues/1573
Those are mainly label changes and seems we are pretty stable on the v1.2 features.

Currently, I use branch directly instead of tag in v1.2 kfdef. One example is https://github.com/kubeflow/manifests/blob/712afa8ab1ab8a2d88c61773519ba6a2e8941fa8/kfdef/kfctl_aws.v1.2.0.yaml#L113

That means if you test everything ok, the final cut will work for your platform as well. I will change back to stable tag once we officially release v1.2.0.

I don't accept new changes to v1.2-branch in kubeflow/kfclt/maniest repos and I plan to cut official release at end of Nov 19, 2020. Please help sign off release.

**Comment by PatrickXYS** [comment] 2020-11-19 19:17
On AWS side, I've tested latest RC release and confirmed they worked properly.

**Comment by cliveseldon** [comment] 2020-11-19 23:14
I'm looking at the issue https://github.com/kubeflow/manifests/issues/1660 which is stopping Seldon installing with the stacks kustomize folders.

**Comment by Jeffwan** [comment] 2020-11-20 06:58
@cliveseldon Are you able to resolve the issue on Friday? Please help cherry-pick to v1.2 as well. I plan to cut release on Friday morning PDT time.

**Comment by cliveseldon** [comment] 2020-11-20 08:04
@Jeffwan Yes hopefully I can get a fix by then.

**Comment by Bobgy** [comment] 2020-11-20 10:49
@Jeffwan FYI, I tried to upgrade GCP KF 1.1 to KF 1.2. Some components require manual actions to upgrade in addition to apply.
https://github.com/kubeflow/gcp-blueprints/issues/139#issuecomment-731088601
I believe:
1. kfserving changed selector for its statefulset
2. katib changed apiversion of 3 CRDs

I had to delete them manually before applying again to upgrade:
```bash
kubectl delete statefulset kfserving-controller-manager -n kubeflow --wait
kubectl delete crds experiments.kubeflow.org suggestions.kubeflow.org trials.kubeflow.org
```

@kubeflow/wg-automl-leads can I confirm if this is the expected way to upgrade an existing cluster? How can users keep their existing custom resource objects?

**Comment by cliveseldon** [comment] 2020-11-20 10:52
@Jeffwan Add PR for master https://github.com/kubeflow/manifests/pull/1670 and a Cherry-Pick for v1.2.0 branch https://github.com/kubeflow/manifests/pull/1671

**Comment by terrytangyuan** [comment] 2020-11-20 15:32
Looks like @jbottum merged https://github.com/kubeflow/blog/pull/58, reverted it in https://github.com/kubeflow/blog/pull/59, and then merged again in https://github.com/kubeflow/blog/pull/60. Is this expected?

**Comment by PatrickXYS** [comment] 2020-11-20 17:10
https://blog.kubeflow.org/release/official/2020/11/18/kubeflow-1.2-blog-post.html I think this is for a pre-review for community. 

It's a work-around to allow community folks do final-review before officially launch.

@jbottum did a good job in 1.2!

**Comment by PatrickXYS** [comment] 2020-11-20 17:14
> Add PR for master kubeflow/manifests#1670 and a Cherry-Pick for v1.2.0 branch kubeflow/manifests#1671

@cliveseldon @Jeffwan I helped merge two PR,

> I tried to upgrade GCP KF 1.1 to KF 1.2 in an existing cluster via apply. Some components require manual actions to upgrade in addition to apply.

@Bobgy Will GCP be able to propose a fix today? Let's try to avoid release next week.

**Comment by jbottum** [comment] 2020-11-20 17:34
@jlewi understand / appreciate your comment.   publishing can take many steps and we can always edit the post.   I think the blog is written to say...we completed the application development, and users/platform teams are testing.   @terrytangyuan yes, not best practice to post, revert, post again...next time I will bring a pro to help with github!

**Comment by Jeffwan** [comment] 2020-11-20 19:10
@andreyvelich Can you help check can I confirm if this is the expected way to upgrade an existing cluster? How can users keep their existing custom resource objects?

**Comment by andreyvelich** [comment] 2020-11-20 19:16
> @Jeffwan FYI, I tried to upgrade GCP KF 1.1 to KF 1.2 in an existing cluster via apply. Some components require manual actions to upgrade in addition to apply.
> [kubeflow/gcp-blueprints#139 (comment)](https://github.com/kubeflow/gcp-blueprints/issues/139#issuecomment-731088601)
> I believe:
> 
> 1. kfserving changed selector for its statefulset
> 2. katib changed apiversion of 3 CRDs
> 
> I had to delete them manually before applying again to upgrade:
> 
> ```shell
> kubectl delete statefulset kfserving-controller-manager -n kubeflow --wait
> kubectl delete crds experiments.kubeflow.org suggestions.kubeflow.org trials.kubeflow.org
> ```
> 
> @kubeflow/wg-automl-leads can I confirm if this is the expected way to upgrade an existing cluster? How can users keep their existing custom resource objects?

@Bobgy Yes, it is expected since we switched to the v1beta1 in the Kubeflow 1.2.
Users should manually delete all Katib Experiment to be able to run the new release.
/cc @gaocegege @johnugeorge

**Comment by Jeffwan** [comment] 2020-11-20 19:17
@Bobgy @andreyvelich I think we need to address these changes in upgrade documentation and make sure users are aware of this

**Comment by Jeffwan** [comment] 2020-11-20 20:17
https://github.com/kubeflow/kubeflow/releases/tag/v1.2.0
https://github.com/kubeflow/kfctl/releases/tag/v1.2.0
https://github.com/kubeflow/manifests/releases/tag/v1.2.0

/cc @jlewi @jbottum

**Comment by Jeffwan** [comment] 2020-11-20 20:34
@RFMVasconcelos Do you want to update docs to use latest tags?

**Comment by berndverst** [comment] 2020-11-20 21:05
@Jeffwan should we update the various manifests to refer to the tag now instead of the branch? Maybe we can do that for all stacks at once.

**Comment by Jeffwan** [comment] 2020-11-20 21:18
@berndverst yeah, I filed a PR https://github.com/kubeflow/manifests/pull/1672 and please help review it. New coming cherry-picks to v1.2-branch won't affect stable release then

**Comment by Bobgy** [comment] 2020-11-20 23:33
SGTM, I'll document them in upgrade instructions the.

**Comment by Bobgy** [comment] 2020-11-20 23:35
@Jeffwan thank you so much for driving the release!

**Comment by RFMVasconcelos** [comment] 2020-11-23 10:39
@Jeffwan thank for driving this!

Regarding docs, I have created PRs & Issues to get everything up to date - see [kubeflow/website#2322](https://github.com/kubeflow/website/issues/2322). Let me know if I'm missing anything

**Comment by PatrickXYS** [comment] 2020-12-11 03:08
I think we finished all the stories in Kubeflow 1.2,

can we close the issue to celebrate?

**Comment by Bobgy** [comment] 2020-12-11 06:10
/close
Congrats to everyone involved!

**Closed by Bobgy** 2020-12-11 06:10 UTC
Labels: area/1.2.0, area/docs, community/maintenance, effort/2-weeks+, kind/feature, kind/process, platform/aws, priority/p1
