### ISSUE TITLE
Post-submits seem to pass while endpoint_is_ready test is failing

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/kubeflow#4227] opened 2019-10-04 03:39 UTC
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Checked a postsubmit for a successful run.
But the endpoint_is_ready test seems to be failing but is chalked off as a successful run anyway.
Logs: 
```
gcp_util.py                 98 INFO     Trying url: https://kfctl-65e7.endpoints.kubeflow-ci-deployment.cloud.goog
gcp_util.py                117 INFO     https://kfctl-65e7.endpoints.kubeflow-ci-deployment.cloud.goog: IAP not ready, exception caught HTTPSConnectionPool(host='
kfctl-65e7.endpoints.kubeflow-ci-deployment.cloud.goog', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation
 of protocol (_ssl.c:645)'),)), request number: 150
xfail
generated xml file: /mnt/test-data-volume/kubeflow-postsubmit-kfctl-go-iap-endpoint-529de7d-7824-4684/output/artifacts/junit_kubeflow-postsubmit-kfctl-go-iap-endp
oint-529de7d-7824-4684/junit_endpoint-is-ready-test-kfctl_gcp_iap.xml
========================= 1 xfailed in 1505.83 seconds =========================
```

Workflow: http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-postsubmit-kfctl-go-iap-endpoint-529de7d-7824-4684?tab=workflow&nodeId=kubeflow-postsubmit-kfctl-go-iap-endpoint-529de7d-7824-4684-3259484450

**What did you expect to happen:**
All tests to have passed successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by swiftdiaries** [comment] 2019-10-04 03:41
/cc @jlewi @abhi-g 
This needs to be p0

**Comment by richardsliu** [comment] 2019-10-04 03:44
Is the endpoint actually ready? Or is this just a test failure?

**Comment by swiftdiaries** [comment] 2019-10-04 03:46
I'm guessing IAP is taking time to be fully ready and the test finishes before that.
We could try increasing the backoff and retry timeout

**Comment by zhenghuiwang** [comment] 2019-10-11 23:45
I increased the timeout to 50 minutes but the endpoint wasn't ready still.

I guess the problem is still about the SSL certificate quota, which is at its limit right now. So I will later try to clean the usage and rerun this test.

**Comment by zhenghuiwang** [comment] 2019-10-14 21:26
same issue as in https://github.com/kubeflow/kfctl/issues/42

Just tried the endpoint test when the quota is enough.(For last a few days the quota was full 200/200) The IAP endpoint was ready in ~20 mins and all tests passed.

I think we are can close this issue now.

I checked the cron Job on releasing the resources: it does seem to do its job. Some SSLs were held not to be deleted because of being used by some targetHttpsProxy, which were in turn used by some forwarding rules.

A possible problem is that the deletion of forwardingRule is a long running operation. e.g. 

```
INFO|2019-10-11T10:26:09|/src/kubeflow/testing/py/kubeflow/testing/cleanup_ci.py|467| response = {u'status': u'RUNNING', u'kind': u'compute#operation', u'name': u'operation-1570789568790-5949ff243bf5e-90491358-8413ffbb', u'startTime': u'2019-10-11T03:26:09.248-07:00', u'insertTime': u'2019-10-11T03:26:09.227-07:00', u'targetId': u'5379620327702838498', u'targetLink': u'https://www.googleapis.com/compute/v1/projects/kubeflow-ci-deployment/global/forwardingRules/k8s-fws-istio-system-envoy-ingress--49a7244eccc604fa', u'operationType': u'delete', u'progress': 0, u'id': u'2547581075254535726', u'selfLink': u'https://www.googleapis.com/compute/v1/projects/kubeflow-ci-deployment/global/operations/operation-1570789568790-5949ff243bf5e-90491358-8413ffbb', u'user': u'kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com'}
```

We don't know if it is completed or not based on the logs. Maybe some operation failed which causes the SSLs were not deleted in the past few days.

**Comment by swiftdiaries** [comment] 2019-10-15 23:20
Considering we seem to have some leakage, should the cleanup script have retries?

**Comment by jlewi** [comment] 2019-10-16 12:37
@zhenghuiwang Any update on this?

We have a bunch of potential issues affecting IAP

* e.g #4266
* e.g. #4043 

Using the post submits to ensure this is running reliable would be a huge help.

**Closed** 2019-10-17 20:49 UTC
Labels: area/kfctl, kind/bug, platform/gcp, priority/p0
