### ISSUE TITLE
Tests are failing on both master and v0.6-branch

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kubeflow#4114] opened 2019-09-11 22:42 UTC
/kind bug

**What steps did you take and what happened:**
post-submits are failing 100%: [link](https://k8s-testgrid.appspot.com/sig-big-data)

**Anything else you would like to add:**
Test `TestKfctlClientServer_GoKit` is failing on both of branches.
On master `test_endpoint_is_ready` is also failing.

Somehow this doesn't block submissions as presubmits don't include the tests as part of result.

**Comment by jlewi** [comment] 2019-09-16 13:28
I think we are out of SSL quota. It doesn't look like we are cleaning up SSL certificates
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py

We recently enabled GKEManaged certificates on master and I think that might be eating up our quota.

I will add some logic to our cleanup_ci script to cleanup old certificates.

**Comment by jlewi** [comment] 2019-09-16 18:06
After cleaning up the SSL certificates the test_endpoint_is_ready test is passing in the most recent presubmit run
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master

github.com/kubeflow/kubeflow/bootstrap/v3/cmd/bootstrap/app.TestKfctlClientServer_GoKit

Is still failing

**Comment by jlewi** [comment] 2019-09-17 01:28
The test output isn't very helpful.

/usr/local/go/src/runtime/sys_linux_amd64.s:535 +0x21
/usr/local/go/src/runtime/os_linux.go:46 +0x4b
/usr/local/go/src/runtime/lock_futex.go:151 +0xa1
/usr/local/go/src/runtime/proc.go:1936 +0xc1
/usr/local/go/src/runtime/proc.go:2399 +0x54a
/usr/local/go/src/runtime/proc.go:2525 +0x21c
/usr/local/go/src/runtime/proc.go:2605 +0xa1
/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b
/usr/local/go/src/testing/testing.go:917 +0x381
/usr/local/go/src/testing/testing.go:1157 +0x78
/usr/local/go/src/testing/testing.go:865 +0xc0
/usr/local/go/src/testing/testing.go:1155 +0x2a9
/usr/local/go/src/testing/testing.go:1072 +0x162
_testmain.go:64 +0x13e
/go/pkg/mod/k8s.io/klog@v0.3.0/klog.go:975 +0x8b
/go/pkg/mod/k8s.io/klog@v0.3.0/klog.go:404 +0x6c
/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:154 +0x100
/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:32 +0x57
/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctlServer.go:276 +0x96
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctlServer.go:83 +0x21f
/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:60 +0x1e7
/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:24
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctlClient.go:118 +0x395
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctl_test.go:78 +0x7aa
/usr/local/go/src/testing/testing.go:865 +0xc0
/usr/local/go/src/testing/testing.go:916 +0x35a
/usr/local/go/src/runtime/netpoll.go:182 +0x56
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
/usr/local/go/src/net/fd_unix.go:238 +0x42
/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
/usr/local/go/src/net/tcpsock.go:260 +0x48
/usr/local/go/src/net/http/server.go:2859 +0x22d
/usr/local/go/src/net/http/server.go:2456
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/ksServer.go:845 +0x561
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctl_test.go:51 +0x34
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/kfctl_test.go:50 +0x39b
/usr/local/go/src/runtime/proc.go:307
/usr/local/go/src/runtime/time.go:105 +0x159
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/ksServer.go:652 +0x30
/mnt/test-data-volume/kubeflow-presubmit-unittests-4129-4b72708-2160-31b5/src/kubeflow/kubeflow/bootstrap/cmd/bootstrap/app/ksServer.go:841 +0x484
/usr/local/go/src/runtime/netpoll.go:182 +0x56
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
/usr/local/go/src/net/fd_unix.go:202 +0x4f
/usr/local/go/src/net/net.go:177 +0x69
/usr/local/go/src/net/http/transport.go:1524 +0x7b
/usr/local/go/src/bufio/bufio.go:100 +0x10f
/usr/local/go/src/bufio/bufio.go:138 +0x4f
/usr/local/go/src/net/http/transport.go:1677 +0x1a3
/usr/local/go/src/net/http/transport.go:1357 +0xae8
/usr/local/go/src/net/http/transport.go:1958 +0x113
/usr/local/go/src/net/http/transport.go:1358 +0xb0d
/usr/local/go/src/runtime/netpoll.go:182 +0x56
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
/usr/local/go/src/net/fd_unix.go:202 +0x4f
/usr/local/go/src/net/net.go:177 +0x69
/usr/local/go/src/net/http/server.go:787 +0x107
/usr/local/go/src/bufio/bufio.go:100 +0x10f
/usr/local/go/src/bufio/bufio.go:138 +0x4f
/usr/local/go/src/net/http/server.go:964 +0xb5a
/usr/local/go/src/net/http/server.go:1819 +0x6ad
/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by jlewi** [comment] 2019-09-17 01:56
It looks like the problem is here
https://github.com/kubeflow/kubeflow/blob/ae9b2c7513c62b497e06d09e1d1f334e7a3c6146/bootstrap/cmd/bootstrap/app/kfctlClient.go#L118

The code keeps retrying for up to 30 minutes if the conditions is length 0.

It looks like this code was recently added in #4014

**Comment by jlewi** [comment] 2019-09-17 02:05
@kunmingg 

Why is createDeployment waiting for up to 30 minutes?
https://github.com/kubeflow/kubeflow/blame/ae9b2c7513c62b497e06d09e1d1f334e7a3c6146/bootstrap/cmd/bootstrap/app/kfctlClient.go#L83

This waiting is in the client. Which is called from the router.
So if we end up waiting for 30 minutes then the request never returns.

It looks like #4014 was done to monitor the deployment and report metrics.

Why are we monitoring the deployment from the client and not from the server?
i.e. why aren't we recording counters about deployment  in handleDeployment in kfctlServer
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/kfctlServer.go#L98

**Comment by kunmingg** [comment] 2019-09-17 02:16
Server side metrics are template, we can print router side metrics in stackdriver UI, but summing up server side metrics might overload stackdriver UI backend.

For `TestKfctlClientServer_GoKit` case should we return an error from server side? 
Or in `kfdef` append error to `condition`?
Either one should resolve the waiting.

**Comment by jlewi** [comment] 2019-09-17 13:22
kubeflow/testing#412 is tracking why the failed go unit test didn't cause the prow job to be reported as failed.

Here's a passing postsubmit in which the kfctl_test.go test passed
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1173837237868040192

The workflow for basic auth failed but I think that's unrelated to this issue so I'm closing this issue as fixed.

**Closed by jlewi** 2019-09-17 13:22 UTC
Labels: area/kfctl, kind/bug, priority/p1
