### ISSUE TITLE
Test kfctl on master for bugs due to Istio upgrade

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#4117] opened 2019-09-12 04:10 UTC

**Comment by jlewi** [comment] 2019-09-12 05:00
@elviraux Can you provide more context please? Where/when was ISTIO upgraded? Did something break?

**Comment by krishnadurai** [comment] 2019-09-12 05:11
I think what @elviraux is referring to here is kubeflow/manifests#323. Even though its tested against the Web UI, Notebooks, Profiles and Pipelines manually there's still a case something could break.
@elviraux should we have a tracking issue for this or let individuals file separate ones when they encounter it?

**Comment by jlewi** [comment] 2019-09-15 04:15
Can we have an automated test?

We have kubeflow/kubeflow#3496 tracking setting up an E2E test on an existing cluster. So ideally that would be the basis for an E2E test of kfctl_k8s_istio.yaml.

Ideally that E2E test should have sufficient coverage to give us high confidence about ISTIO.

**Comment by krishnadurai** [comment] 2019-09-16 13:26
I think an automated test for Notebooks and Multi-user workflows will be the way to go here since these are the primary features being affected by Istio. I'll pair with @swiftdiaries to see what we can do here.

**Comment by jlewi** [comment] 2019-09-20 15:10
Thanks @krishnadurai 

Some pointer that might be helpful

* I believe @yanniszark is working on #3496
* We have a test for provisioning a notebook here
  * https://github.com/kubeflow/kubeflow/blob/master/kubeflow/jupyter/tests/jupyter_test.py
* @jinchihe wrote an E2E test that runs our xgboost_synthetic notebook using papermill
  * https://github.com/kubeflow/examples/blob/master/test/workflows/components/xgboost_synthetic.jsonnet

**Comment by richardsliu** [comment] 2019-10-07 22:54
@swiftdiaries Any updates on this?

**Comment by jlewi** [comment] 2019-11-04 23:27
@krishnadurai can we close this as a duplicate of kubeflow/kubeflow#3496?
If not what is the unique work this issue is tracking?

**Comment by krishnadurai** [comment] 2019-11-05 19:56
We could close this.
I'll make a separate issue for creating another E2E test for Istio 1.3.1.

/close

**Closed by krishnadurai** 2019-11-05 19:56 UTC
Labels: area/istio, area/kfctl, area/testing, kind/feature, priority/p1
