### ISSUE TITLE
Cannot select which profile to manage in "Manage Contributors" UI

### ISSUE THREAD

**Issue by abdulsalama** [kubeflow/kubeflow#4924] opened 2020-04-06 21:12 UTC
/kind bug

**What steps did you take and what happened:**
When user is admin to multiple profiles and then go to "Manage Contributors" UI, it shows the user as owner on the first profile but contributors on all the others. There is also no way to select which profiles you want to add contributors to, and can only do it on the first profile (in which you are listed as owner).

**What did you expect to happen:**
Users is shown as owner to all these profiles and can select which profile to add contributors to.

**Anything else you would like to add:**
N/A

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): dev_local
- kfctl version: v1.0-0-g94c35cf
- Kubernetes platform: eks
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.4

**Comment by yanniszark** [comment] 2020-04-17 15:31
Hi @abdulsalama !
How are the other profiles created?
What is the profile owner specified on them?
Please check my comment here and tell me if it also applies to you: https://github.com/kubeflow/kubeflow/issues/4938#issuecomment-615310170

**Comment by abdulsalama** [comment] 2020-04-20 15:21
Thanks @yanniszark 
As in the reply to the other comment, I'm also confused about the difference between profile owner and admin if any? There is nothing mentioned about being a profile Admin in the doc. How do I make someone profile admin for example?

In terms of how the profiles are created, one of them was created through the onboarding process. And the others were created directly by applying a profile yaml file using kubectl. All of these profiles share the same owner so I expect when I go to Manage Contributors UI, I should be able to manage contributors to all of them.

**Comment by abdulsalama** [comment] 2020-04-20 15:24
And also the comment in  #4938 (comment), seems to indicate the issue/ask here is about an admin being able to manage all users/namespaces from the UI... But that is not the issue (at least my issue). This issue is all about a specific user being able to manage all his/her profiles since he/she is the owner on all of them.

**Comment by yanniszark** [comment] 2020-04-30 20:14
@abdulsalama I haven't checked this scenario but it sounds like a bug in the CentralDashboard or KFAM.
Can you provide instructions to reproduce? (e.g., how you created the Profiles)

**Comment by abdulsalama** [comment] 2020-05-01 22:11
thanks @yanniszark for following up.

In that specific case, one profile was created through the onboarding process. The other one was created using kubectl:
kubectl apply -f profile.yaml

where profile.yaml is something like this:
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: profile1
spec:
  owner:
    kind: User
    name: foo@example.com

**Comment by yanniszark** [comment] 2020-05-06 11:47
@abdulsalama thanks for reporting!
I reproduced in my MiniKF.
After creating 2 profiles, the namespace selector was correctly showing me both of them:

![namespace_selector](https://user-images.githubusercontent.com/6123106/81172075-3a14b480-8fa6-11ea-921a-3058d450e1df.png)

However the contributor UI only shows allows managing contributors for 1 of them:
![contributor_ui](https://user-images.githubusercontent.com/6123106/81172113-50bb0b80-8fa6-11ea-9839-e16bd7f42f82.png)

So this is a contributor UI issue.
Since the contributor UI is part of the Central Dashboard, I am assigning `area/centraldashboard` to this.

@abdulsalama you can work around this by not using the Contributors UI to manage contributors.

For the Contributor UI, there are also the concerns outlined here: https://docs.google.com/document/d/19cHFmuv-qfutY27aQv1n-u3xEH8rXcSU60xybMbU1Co

/area centraldashboard
/cc @jlewi @avdaredevil @prodonjs

**Comment by avdaredevil** [comment] 2020-05-06 18:22
Hi @yanniszark,

This is a known issue. Unfortunately, while this UI was being developed we were under the impression that there cannot be more than one owned namespace for a given user (hence no need to provide a selector for the namespace for which you would modify contributors).

I believe @Bobgy made an issue / PR on this, I'll let him elaborate on plans to implement this.

The backend is primed for an update to the UI to add the support, however, the UI updates are slightly more involved. While I personally do not have cycles to work on this, I am more than willing to guide a PR to implement this change.

/cc @truptinayak

**Comment by yanniszark** [comment] 2020-05-06 19:00
@avdaredevil thanks a lot for the explanation and status update! :smile: 
I found this issue that @Bobgy created: https://github.com/kubeflow/kubeflow/issues/4569
@Bobgy I think it's the same issue, if you agree let's close this as a duplicate.

**Comment by Bobgy** [comment] 2020-05-07 03:29
@yanniszark Yes, this is a duplicate of #4569.
Let's continue the discussion there.
/close

**Closed by Bobgy** 2020-05-07 03:29 UTC
Labels: area/centraldashboard, area/multiuser, kind/bug, priority/p1

**Comment by thesuperzapper** [comment] 2024-07-16 21:58
This feature has been added in https://github.com/kubeflow/kubeflow/pull/7582

It will be included in Kubeflow 1.9.0.
