### ISSUE TITLE
kfctl binary doesnt download from local kubeflow repo.

### ISSUE THREAD

**Issue by arjunm183** [kubeflow/kubeflow#3476] opened 2019-06-17 08:01 UTC
Kfctl binary doesnt download kubeflow repository which is in github enterprise local repo when used it with -r option.
kfctl init kfv2 -r https://gitcorp.enterprise.com/kubeflow/kubeflow.git

When i see the .cache folder after the initialization it looks like downloaded from the central repository.
Is it possible to provide option for the repo to download from private git repository as well. That would make sense for Enterprise users.

**Comment by jlewi** [comment] 2019-06-17 20:06
Duplicate of #2831

**Closed by jlewi** 2019-06-17 20:06 UTC
