### ISSUE TITLE
Jupyter service on master not working

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3502] opened 2019-06-19 22:13 UTC
When I click "spawn", nothing happens.
Saw this in the pod
```
HTTP response headers: HTTPHeaderDict({'Audit-Id': '888aaf55-53d0-4086-99ba-b64cb2893c23', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 19 Jun 2019 22:10:59 GMT', 'Content-Length': '344'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"podpresets.kubeflow.org is forbidden: User \"system:serviceaccount:kubeflow:jupyter-web-app-service-account\" cannot list podpresets.kubeflow.org in the namespace \"kubeflow\"","reason":"Forbidden","details":{"group":"kubeflow.org","kind":"podpresets"},"code":403}
```

 podpreset has been renamed to poddefaults.kubeflow.org

**Comment by lluunn** [comment] 2019-06-19 22:15
The jupyter webapp image is from May2, needs update.

**Comment by lluunn** [comment] 2019-06-20 01:14
Next error: the statefulset cannot be created
```
Warning  FailedCreate  9s (x14 over 30s)  statefulset-controller  create Pod test1-0 in StatefulSet test1 failed error: pods "test1-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
```

**Comment by lluunn** [comment] 2019-06-20 01:15
@kunmingg is there supposed to be a default-editor service account, and we missed it in kustomize?
Or we changed the name?
I can see there is a service account called jupyter-web-app-notebook-service-account

**Comment by kunmingg** [comment] 2019-06-20 01:26
@lluunn 
You can create a profile and use notebook in profile-namespace.
kubeflow namespace is a system namespace for shared components

**Comment by kunmingg** [comment] 2019-06-20 01:27
`jupyter-web-app-notebook-service-account` deleted in:
https://github.com/kubeflow/manifests/pull/158
It seems not have a consumer.

**Comment by lluunn** [comment] 2019-06-20 01:54
So users are not supposed to do stuff in kubeflow namespace?
Seems like an unnecessary constraint if the user is admin and doesn't need multi-user feature.
cc @jlewi

**Comment by lluunn** [comment] 2019-06-20 01:56
I think jupyter-web-app-jupyter-notebook-role-binding binds the wrong service account name, no prefix.
https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/role-binding.yaml#L10

**Comment by jlewi** [comment] 2019-06-20 03:36
Should we create a profile by default for the user who deploys Kubeflow?

**Comment by kimwnasptd** [comment] 2019-06-20 15:56
cc

**Comment by jlewi** [comment] 2019-06-26 12:40
Is this a duplicate of #3505?

@abhi-g @kimwnasptd can you confirm if this has been fixed in the latest images?

**Comment by abhi-g** [comment] 2019-06-26 13:13
I am trying to verify but running into a different issue. My master is synced at commit dcaeee742984. After deployment the Jupyter Web App is sending an "Internal Server Error" 
<img width="1428" alt="Screen Shot 2019-06-26 at 6 08 58 AM" src="https://user-images.githubusercontent.com/11774566/60182578-6c2b8680-97d9-11e9-85e5-b99df74a4b49.png">

I recall there were some PRs to fix the Manifests. Does kfctl deploy "pinned" manifests or from master?

**Comment by kimwnasptd** [comment] 2019-06-26 13:47
@abhi-g maybe your browser has the previous version of the webapp cached. If you are using Chrome, could you:
1. Click `Command+Option+I`(Mac) or `Control+Shift+I`(Windows) to open the [Dev Tools](https://developers.google.com/web/tools/chrome-devtools/shortcuts)
2. Go to the `Network` tab
3. Check the `disable cache` checkbox
4. Reload the page with the dev tools open

This will force the browser to not use the cached page. 

I'm not sure regarding kfctl and the manifests, maybe @yanniszark could provide more info here. When I was testing the webapp, I was deploying it by:
1. cloning the manifests repo
2. From the `master` branch `cd jupyter/jupyter-web-app/base`
3. `kubectl apply -k .`

Lastly if you've deployed from the manifests, is the pod's image tag set to `dcaeee7`? Also, is there a `jupyter-web-app-config` with [these](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/config-map.yaml) contents?

**Comment by abhi-g** [comment] 2019-06-26 14:05
In my case, gcr.io/kubeflow-images-public/jupyter-web-app:f8d85ad is being
used. Let me verify the manifests at master and redeploy.
I can certainly 'kubectl apply -k' from the manifests repo, but I want to
ensure kfctl is also picking up the correct manifests when deploying...

**Comment by abhi-g** [comment] 2019-06-26 16:38
Verified kubeflow/kubeflow@9bb2c0176506950415cee95c602d66dd88cc3f92
and kubeflow/manifests@cd5c491e9492844a12294e48f0961382c2cd2669
That the jupyter-web-app: dcaeee7 works correctly as intended with the multi-user isolation profiles..

**Closed by abhi-g** 2019-06-26 16:38 UTC
Labels: kind/bug, priority/p0

**Comment by lluunn** [comment] 2019-07-09 19:03
notebook service is still not working in kubeflow namespace right?

**Comment by abhi-g** [comment] 2019-07-10 18:17
I was able to get it to deploy from master last week. Will try
again tomorrow.
