### ISSUE TITLE
TFJob controller cannot terminate job

### ISSUE THREAD

**Issue by bleachzk** [kubeflow/kubeflow#193] opened 2018-02-01 15:38 UTC
I test kubeflow/tf-controller-examples/tf-cnn/tf_job_gpu.yaml by running kubectl:

> kubectl apply -f tf_job_gpu.yaml
> kubectl get job
> NAME                                          DESIRED   SUCCESSFUL   AGE
> inception-171202-163257-gpu-1-ps-272u-0       1         0            7m
>inception-171202-163257-gpu-1-worker-272u-0   1         0            7m

The TFJob controller cannot terminate job when the WORKER is done based on the TerminationPolicy。

WORKER log：

[logs-from-tensorflow-in-inception-171202-163257-gpu-1-worker-272u-0-fdx5x.txt](https://github.com/kubeflow/kubeflow/files/1686081/logs-from-tensorflow-in-inception-171202-163257-gpu-1-worker-272u-0-fdx5x.txt)

**Comment by gaocegege** [comment] 2018-02-02 01:29
@bleachzk Thanks for your issue, and I am not sure if we support TerminationPolicy now, maybe jlewi@ could give us more info

**Comment by jlewi** [comment] 2018-02-02 01:55
@bleachzk Can you please provide the spec/status for your TFJob? Can you also clarify what your expected behavior is and what the observed behavior is?

Its possible you're hitting tensorflow/k8s#128

**Comment by bleachzk** [comment] 2018-02-02 06:15
Worker ran successfully，job should be terminated，but it is still running...

**Pod status：**
![pod status](https://user-images.githubusercontent.com/5548534/35719117-cbb91d1c-0822-11e8-9675-6b20ee3b91b4.PNG)

**worker logs：**
![worker-pod-logs](https://user-images.githubusercontent.com/5548534/35719136-e42a826e-0822-11e8-89f1-08a47a60919f.PNG)

**Job status：**
![job-status](https://user-images.githubusercontent.com/5548534/35719023-2b1b2fd0-0822-11e8-8ab0-59b57fa6902a.PNG)

**Comment by bleachzk** [comment] 2018-02-02 06:15
@jlewi

**Comment by jlewi** [comment] 2018-02-04 19:31
That's tensorflow/k8s#128 

We originally let the jobs continue to run until the TFJob is deleted to make the logs accessible after the job terminated.

We are working on fixing that.

**Comment by jlewi** [comment] 2018-03-09 13:57
Duplicate of kubeflow/tf-operator#128

**Closed** 2018-03-09 13:57 UTC
