### ISSUE TITLE
Cannot not run tensorboard from Jupyter notebooks

### ISSUE THREAD

**Issue by ernestmartinez** [kubeflow/kubeflow#422] opened 2018-03-14 15:53 UTC
I'm running on a MAAS bare metal deployment.

When I try to run tensorboard I get a dialog which states:
Jupyter tensorboard extension error
Check that tensorflow(-gpu)>=1.3 is installed.
Check that jupyter, tensorflow and jupyter_tensorboard have the same python version.
Check that jupyter_tensorboard is installed via pip list. If you want uninstall this extension, run jupyter nbextension disable jupyter_tensorboard/tree --user and jupyter nbextension uninstall jupyter_tensorboard --user;

pip list does not show tensorflow installed. When I tried to pip install tensorflow it error'd with a permission denied on lazy.py.
Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /opt/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-116-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:100

**Comment by jlewi** [comment] 2018-03-14 23:35
We should probably remove that link. This is not the recommended way to run tensorboard. I suggest running tensorboard separately as a K8s deployment.

There is an open issue #297 to add templates to do this.

We should remove the link in JupyterHub to run tensorboard.

**Comment by jlewi** [comment] 2018-03-26 14:01
Duplicate of #297

**Closed** 2018-03-26 14:01 UTC
