### ISSUE TITLE
"Unknown variable: x" in 0.5.0 and 0.5.1 

### ISSUE THREAD

**Issue by padrian2s** [kubeflow/kubeflow#3603] opened 2019-07-03 11:10 UTC
ksonnet version: 0.13.1
jsonnet version: v0.11.2
kubectl version: v1.15.0
client-go version: kubernetes-1.10.4

I'm using a mac distro but also tried on a ubuntu distro (docker pull ubuntu).
I tried kfctl init on master but also with different 0.5.x versions.

I deployed many times the KF but error is somehow new...

When I try to deploy ks components on 0.5.0 or 0.5.1 I get this error:

kfctl apply all -V
INFO[0000] deploying kubeflow application                filename="cmd/apply.go:35"
INFO[0000] reading from /root/dspl/app.yaml              filename="coordinator/coordinator.go:341"
INFO[0000] reading from /root/dspl/app.yaml              filename="coordinator/coordinator.go:341"
INFO[0000] namespace: kubeflow                           filename="ksonnet/ksonnet.go:109"
ERRO[0005] (Will retry) Component ambassador apply failed; Error: find objects: /root/dspl/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

          "withX-Kubernetes-Embedded-Resource":: self + { "x-kubernetes-embedded-resource": x-kubernetes-embedded-resource },
  filename="ksonnet/ksonnet.go:174"
ERRO[0011] (Will retry) Component argo apply failed; Error: find objects: /root/dspl/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

          "withX-Kubernetes-Embedded-Resource":: self + { "x-kubernetes-embedded-resource": x-kubernetes-embedded-resource },
  filename="ksonnet/ksonnet.go:174"
ERRO[0015] (Will retry) Component centraldashboard apply failed; Error: find objects: /root/dspl/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

**Comment by ptrckbnck** [comment] 2019-07-05 18:27
I get the same problem after upgrading minikube v1.1.1 to v1.2.0 which runs Kubernetes v1.15.0 by default. Minikube v1.1.1 runs fine with Kubernetes v1.14.3

**Comment by PercyLau** [comment] 2019-07-08 11:51
I have the same problem on the latest Kubernetes (v1.15.0) installed using kind. 
# kfctl apply all -V prints the following errors:
ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

**Comment by PercyLau** [comment] 2019-07-11 07:27
The problem disappears if follows the current configuration on Kubeflow homepage,
https://www.kubeflow.org/docs/started/getting-started-k8s/

I use kind to manage my local kubernetes cluster. 
https://kind.sigs.k8s.io/

So, all I need to do is to tell kfctl the k8s config path (e.g., ~/.kube/config) generated by kind.

**Comment by jlewi** [comment] 2019-07-15 16:20
Duplicate of #3544

Please see #3544

**Closed by jlewi** 2019-07-15 16:20 UTC
Labels: kind/bug
