### ISSUE TITLE
can not install V0.5.1 successfully on Minikube

### ISSUE THREAD

**Issue by zhcf** [kubeflow/kubeflow#3813] opened 2019-08-02 02:22 UTC
**kfctl.sh apply all failed with No resources found.**

**steps:**
export KUBEFLOW_SRC=/opt/kubeflow
rm ${KUBEFLOW_SRC}
mkdir ${KUBEFLOW_SRC}
cd ${KUBEFLOW_SRC}
export KUBEFLOW_TAG=v0.5.1
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash

KUBEFLOW_REPO=${KUBEFLOW_SRC} ${KUBEFLOW_SRC}/scripts/kfctl.sh init KFAPP  --platform minikube
cd KFAPP
${KUBEFLOW_SRC}/scripts/kfctl.sh generate all
${KUBEFLOW_SRC}/scripts/kfctl.sh apply all
 popd
/opt/kubeflow/KFAPP
set +x
Getting kubeflow namespace ready...[OK]
Bringing kubeflow services up.No resources found.
No resources found.
No resources found.
No resources found.

**Environment:**
- centos 7.6
- minikube 1.2
- k8s 1.14.2
- kuberctl 1.14.2
- ks 0.13.1
- kubeflow 0.5.1

**Comment by cdraper-CS** [comment] 2019-08-02 13:14
Here's how I had to workaround the above, based on the information in #2863. After running generate, I had to edit kfctl.sh to move this in ksApply()

```
  set +x
  if [[ "${PLATFORM}" == "minikube" ]] || [[ "${PLATFORM}" == "docker-for-desktop" ]]; then
    if is_kubeflow_ready; then
      mount_local_fs
      setup_tunnels
    else
      echo -e "${RED}Unable to get kubeflow ready${NC}"
    fi
  fi
  set -x
```

to just after
```
      kubectl apply --validate=false -f default.yaml
```

**Comment by jlewi** [comment] 2019-08-02 21:11
Duplicate of #2863

**Closed by jlewi** 2019-08-02 21:11 UTC
Labels: kind/bug
