### ISSUE TITLE
kfctl init for on prem doesn't work

### ISSUE THREAD

**Issue by Tabrizian** [kubeflow/kubeflow#3589] opened 2019-07-01 19:45 UTC
A fresh installation of kfctl on a new Kubernetes cluster doesn't work.

The error below occurred during ```kfctl apply all -V```
```
ERRO[0007] (Will retry) Component ambassador apply failed; Error: find objects: /home/iman/Documents/Git/kf-deployment-baremetal/ks_app/lib/ksonnet-lib/v1.15.0/k8s.libsonnet:17681:93-94 Unknown variable: x

          "withX-Kubernetes-Embedded-Resource":: self + { "x-kubernetes-embedded-resource": x-kubernetes-embedded-resource },
```

```kfctl version
v20181207-4e7f4ed-198-gaeea303e-dirty-03e65e
```

```
ks version
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by jlewi** [comment] 2019-07-01 23:29
Duplicate of #3544

**Comment by jlewi** [comment] 2019-07-01 23:30
The title says `kfctl init` but error indicates its with `kfctl apply`

**Closed by jlewi** 2019-07-01 23:30 UTC
Labels: kind/bug
