### ISSUE TITLE
Kubeflow quick start misses namespace creation

### ISSUE THREAD

**Issue by Oblynx** [kubeflow/kubeflow#1514] opened 2018-09-12 08:50 UTC
The "Kubeflow quick start" instructions (https://www.kubeflow.org/docs/started/getting-started/) will fail, if the "kubeflow" namespace doesn't already exist in the cluster.
Namespace creation should be added to the "Requirements".

**Comment by jlewi** [comment] 2018-10-11 03:56
Duplicate of #1675

**Closed by jlewi** 2018-10-11 03:56 UTC
