### ISSUE TITLE
Pagination on experiments not working

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/kubeflow#3484] opened 2019-06-18 06:17 UTC
Hi Kubeflow Team,

the pagination on the experiments page is not working properly.  

**Description**
- Open the experiments page
- Switch to next page
- Error appears

More results existing then just one page. 

![2019-06-18 08 12 04](https://user-images.githubusercontent.com/1991664/59657469-159ec680-91a1-11e9-89e0-de50c9af1299.gif)

**Error message:**
`{"error":"Failed to create list options: Invalid input error: page token does not match the supplied sort by and/or filtering criteria. Either specify the same criteria or leave the latter empty if page token is specified.","message":"Failed to create list options: Invalid input error: page token does not match the supplied sort by and/or filtering criteria. Either specify the same criteria or leave the latter empty if page token is specified.","code":3,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"page token does not match the supplied sort by and/or filtering criteria. Either specify the same criteria or leave the latter empty if page token is specified.","error_details":"Failed to create list options: Invalid input error: page token does not match the supplied sort by and/or filtering criteria. Either specify the same criteria or leave the latter empty if page token is specified."}]}`

**Version:**
Kubeflow: Build commit: c938247
Kubeflow created with the UI (GCP)

Best regards
Sascha

**Comment by jlewi** [comment] 2019-06-18 12:48
/assign @rileyjbauer 

@rileyjbauer Can you assign to the right front end person please?

**Comment by rileyjbauer** [comment] 2019-06-19 23:02
Hello, thank you for filing this report!
This was a regression in Kubeflow Pipelines v0.1.16 and was fixed in https://github.com/kubeflow/pipelines/issues/1149 as part of the v0.1.17 release, so all subsequent versions of Kubeflow Pipelines should be working as expected.

**Comment by SaschaHeyer** [comment] 2019-06-20 15:15
Hi @rileyjbauer 
great thank you.

I deployed Kubeflow to GCP Using the UI https://www.kubeflow.org/docs/gke/deploy/deploy-ui/. So I assume the Kubeflow deployment tool is still using an old version?

**Comment by jlewi** [comment] 2019-09-10 13:55
@rileyjbauer Is this still an issue or has it been fixed in the latest release of KF pipelines?

**Comment by jlewi** [comment] 2019-09-16 19:31
@jessiezcc can you find an owner for this?

**Comment by Bobgy** [comment] 2019-09-25 01:35
This has been fixed since v0.1.17.

**Comment by jlewi** [comment] 2019-09-25 21:52
Thanks.
It looks like we are currently shipping KFP 0.23

**Closed by jlewi** 2019-09-25 21:52 UTC
Labels: area/front-end, area/pipelines, kind/bug, priority/p0
