### ISSUE TITLE
kfctl build & apply example flags don't work

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4239] opened 2019-10-07 06:50 UTC
/kind bug

**What steps did you take and what happened:**

Run `kfctl build`
Get suggested output that does not run:

> Error:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file: config file must be the URI of a KfDef spec
> Usage:
>   kfctl build [flags]
> 
> Flags:
>   -f, --file string   Static config file to use. Can be either a local path or a URL.
>                       For example:
>                       --config=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
>                       --config=kfctl_platform_gcp.yaml
>   -h, --help          help for build
>   -V, --verbose       verbose output default is false
> 
> 

`--config` is not the correct name for the flag

**What did you expect to happen:**

I'd expect it to show `--file` where it shows `--config`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): N/A (didn't get that far)
- kfctl version: (use `kfctl version`): 2395c5fc (built from 2395c5fc0d384cf6dd4d7167bbe9010cd1315b54)
- Kubernetes platform: (e.g. `minikube`): N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by jlewi** [comment] 2019-10-07 13:46
/assign @swiftdiaries 

Is this the same issue you were mentioning?

**Comment by swiftdiaries** [comment] 2019-10-07 23:00
Yes, I have a fix out here: https://github.com/kubeflow/kubeflow/pull/4232

**Comment by jbottum** [comment] 2019-10-10 02:16
@swiftdiaries @holdenk if its the same as 4232, can we add this to 0.7 and close it ?

**Comment by holdenk** [comment] 2019-10-10 02:24
I'm not sure? It doesn't look like 4232 changes the help print out, but maybe it's generated differently than I expect.

**Comment by jlewi** [comment] 2019-10-10 04:57
This doesn't look to be fixed at ec929c11b11951f6fd350f6552778f0df26566e6

```
kfctl build 
Error:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file: config file must be the URI of a KfDef spec
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path or a URL.
                      For example:
                      --config=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                      --config=kfctl_platform_gcp.yaml
  -h, --help          help for build
  -V, --verbose       verbose output default is false

 (kubeflow.error): Code 400 with message: Error creating KfApp from config file: config file must be the URI of a KfDef spec
```

The problem is the help string is wrong. The help string is telling people to set "config=..." but it should be "--file="...

We need to fix the help string.

**Comment by jlewi** [comment] 2019-10-10 04:58
Bump to P0 because we should fix before finalizing 0.7.

@swiftdiaries Could you send out a PR to update the help string please?

**Comment by jlewi** [comment] 2019-10-11 07:26
@ryandawsonuk what commit are you using?

/cc @swiftdiaries

**Comment by ryandawsonuk** [comment] 2019-10-11 08:26
[9d4714ed3fef2d14574eb197a280a1c115f6f934](https://github.com/kubeflow/kubeflow/commit/9d4714ed3fef2d14574eb197a280a1c115f6f934)

**Comment by jlewi** [comment] 2019-10-12 18:42
This should be fixed by #4282. Hopefully that will make into RC.1 and then we can verify its fixed and close this bug.

**Comment by ryandawsonuk** [comment] 2019-10-14 16:54
I'm now using commit 67aa5e8bd0e8a429b710df4086f2fd1ccafa02c8. Now when I do `kfctl build -f https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_existing_arrikto.yaml` I get:

```
 (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file: mkdir : no such file or directory
```
And if I instead reference a local kfdef yaml file then I get:
```
FATA[0000] could not get platform existing_arrikto Error  (kubeflow.error): Code 500 with message: AppDir must be specified **  filename="coordinator/coordinator.go:768"
```

**Comment by jlewi** [comment] 2019-10-14 22:29
@ryandawsonuk  for IAP i think that's working as intended you need to set the environment variables like the error message is telling you. 

For existing_arrikto I suspect its related to  #4293

/cc @yanniszark

**Comment by swiftdiaries** [comment] 2019-10-14 23:32
This is a workflow that works but it doesn't use the `existing_arritko` config.
```
export KFAPP=</path/to/directory>
mkdir ${KFAPP}
cd ${KFAPP}
wget https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.yaml
kfctl apply -f $(pwd)/kfctl_k8s_istio.yaml -V
```

**Comment by ryandawsonuk** [comment] 2019-10-15 11:09
@swiftdiaries I'm trying that workflow now. It doesn't error but for me it doesn't generate any yaml either. (Using [2b5707c6fffae3f7a14332673dacad72f1c27ffa](https://github.com/kubeflow/kubeflow/commit/2b5707c6fffae3f7a14332673dacad72f1c27ffa))

**Comment by yanniszark** [comment] 2019-10-15 11:41
Hi @ryandawsonuk!
I have deployed existing_arrikto from the latest master (fedf5d969d8441d057aa04fa5e993e04cd15b77b) with the following:

```
export KFAPP=</path/to/directory>
mkdir ${KFAPP}
cd ${KFAPP}
wget https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_existing_arrikto.yaml
kfctl apply -f $(pwd)/kfctl_existing_arrikto.yaml -V
```

**Comment by jlewi** [comment] 2019-10-16 12:17
I believe the issue is fixed in #4282.

This didn't make it into 0.7.0-rc.1 of kfctl.

So we need to wait for the next RC and then we can verify this is fixed.

**Comment by richardsliu** [comment] 2019-10-17 00:50
On the latest RC:
```
Error: Cannot determine the object kind: config file must be a URI or a path
Usage:
  kfctl build [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path or a URL.
                      For example:
                      --file=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                      --file=kfctl_platform_gcp.yaml
  -h, --help          help for build
  -V, --verbose       verbose output default is false
```
and

```
Error: unknown shorthand flag: 'x' in -x
Usage:
  kfctl apply [all(=default)|k8s|platform] [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path or a URL.
                      For example:
                      --file=https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_platform_existing.yaml
                      --file=kfctl_platform_gcp.yaml
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

unknown shorthand flag: 'x' in -x
```

**Comment by richardsliu** [comment] 2019-10-17 00:51
This can be closed now.
/close

**Closed by richardsliu** 2019-10-17 00:51 UTC
Labels: area/kfctl, kind/bug, priority/p0
