### ISSUE TITLE
Notebook namespace UX issue

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#4273] opened 2019-10-11 03:28 UTC
It's impossible to set the namespace in the notebook instance creation form.

![image](https://user-images.githubusercontent.com/1829149/66622428-6d23d080-eb9c-11e9-9ce2-760d691957eb.png)

**Comment by jlewi** [comment] 2019-10-11 07:52
@Ark-kun you can set it by selecting namespace in the dropdown box on the title bar.

/assign @kimwnasptd

**Comment by mattiasarro** [comment] 2019-10-18 13:55
@jlewi for me that dropdown says "No namespaces"

![Screenshot 2019-10-18 at 2 50 03 pm](https://user-images.githubusercontent.com/53719/67100014-dc11b280-f1b6-11e9-8df6-db58a76c0c75.png)

I'm using `kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80` to access the UI.

**Comment by Ark-kun** [comment] 2019-10-21 21:03
> @Ark-kun you can set it by selecting namespace in the dropdown box on the title bar.

I know. But there is no indication of that.
And the whole idea is strange: why are there two namespace form fields? Why is one of them red, but not editable?

**Comment by jlewi** [comment] 2019-12-09 20:40
@kimwnasptd @avdaredevil can one of you triage this? Is this something we want to get done for 1.0?

**Comment by avdaredevil** [comment] 2019-12-10 01:12
@Ark-kun I'm not sure how you're able to see this page if you don't have access to any namespaces. The UI should be in registration flow otherwise.

@kimwnasptd There's two options we can do to prevent this from happening:
- We default the user to one of the states in the namespace bar (pick a namespace randomly or always default to owned namespace). Will not work if there are no namespaces available
- jupyter-web-app (In iframe mode), will show an empty state that says, "please select a namespace from above to proceed"?

**Comment by kimwnasptd** [comment] 2019-12-10 13:10
@jlewi lets aim for making it clear to the user how/where to select a Namespace when creating a Notebook for 1.0.

@avdaredevil I agree with having JWA to show a more informative message and urge the user to select a namespace from above.

Regarding the Central Dashboard's behavior, I think having some sort of Least-Recently-Used-Namespace/per-user policy would be helpful (just like GCP remembers and sets the last organization I was working in). If we go down with this approach then the centraldashboard could:
1. Select the least recently used namespace from that user
2. If this information is not available, then select the namespace in which this user is an owner.
3. If the user does not own any namespace, then leave this field empty and JWA will provide more helpful guidance when it will need to have a namespace selected.

For the LRU I guess we could do it in the client with something like the [window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) object. WDYT @avdaredevil 

Also, Apoorv could you add the necessary labels since I'm not yet in the maintainers list and I can't currently add labels? I think we should aim for `p1` and get this in for 1.0, also since I'll also update JWA please add and the `area/jupyter` label.

**Comment by avdaredevil** [comment] 2019-12-11 01:53
Hey @kimwnasptd, thanks for the quick reply! I completely agree, and I think that's probably the best way to go.

It seems `area/jupyter` and `area/centraldashboard` are already there from before, and I've also added `area/front-end`.

PS. The `CentralDashboard_SDK` should have the iframe state in it, so you should be able to leverage that state when making the update for namespace selection.

Thanks!

---

/priority p1
/assign @avdaredevil 
/cc @truptinayak

**Comment by jlewi** [comment] 2019-12-16 17:25
@kimwnasptd @avdaredevil Could you please clarify what the needed work is here and who will be doing it?

**Comment by kimwnasptd** [comment] 2019-12-17 14:56
From the JWA part I will change the text from `Namespace` -> `Please select a Namespace from above` in the form input field.

**Comment by avdaredevil** [comment] 2020-01-23 21:45
I tackled the namespace defaulting and validation change in #4659

**Comment by avdaredevil** [comment] 2020-01-23 21:45
I tackled the namespace defaulting and validation change in #4659. Perhaps we can close this?

**Comment by jlewi** [comment] 2020-02-21 13:39
Confirmed its fixed in 1.0.

**Closed by jlewi** 2020-02-21 13:39 UTC
Labels: area/centraldashboard, area/front-end, area/jupyter, kind/feature, priority/p1
